// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { renderCompanyOfficeViewerResponse } from "@workspace/platform/server/company-documents";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const paramsSchema = z.object({ key: z.string().regex(/^[a-z][a-z0-9-]*$/) });

export const GET = createCommandRoute({
  paramsSchema,
  paramsError: "Invalid company document key",
  buildCommand: ({ params, request }) => okCommand({ documentKey: params.key, request }),
  action: renderCompanyOfficeViewerResponse,
});
