// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdminApiAccess, isSuperAdmin } from "@workspace/platform/server/auth";
import { createAdminUser, listAdminUsers } from "@workspace/platform/server/users";
import { jsonErrorResponse } from "@workspace/platform/server/api";

const createAdminUserSchema = z.object({
  username: z.string().trim().min(1, "用户名不能为空").max(64, "用户名过长"),
  employeeId: z.string().trim().optional().nullable(),
});

export async function GET(request: Request) {
  const auth = await requireAdminApiAccess(request);
  if (!auth.ok) return auth.response;
  const payload = auth.user;
  if (!(await isSuperAdmin(payload.userId))) {
    return jsonErrorResponse("无权限", 403);
  }

  return NextResponse.json({ users: await listAdminUsers() });
}

export async function POST(request: Request) {
  const auth = await requireAdminApiAccess(request);
  if (!auth.ok) return auth.response;
  const payload = auth.user;
  if (!(await isSuperAdmin(payload.userId))) {
    return jsonErrorResponse("无权限", 403);
  }

  const parsed = createAdminUserSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return jsonErrorResponse(parsed.error.issues[0]?.message || "用户名为必填", 400);

  const user = await createAdminUser(parsed.data).catch((error) => {
    const message = error instanceof Error ? error.message : "创建用户失败";
    return { error: message };
  });
  if ("error" in user) return jsonErrorResponse(user.error, user.error.includes("已") ? 409 : 400);
  return NextResponse.json({ user });
}
