别嘌醇片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: UV-BPC中间体含量
- part: 二
  items:
  - 性状: 目测
  - 重量差异: 重量差异
  - 溶出度: 溶出度
  - 含量: UV-BPC含量
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 有关物质: 有关物质-BPC
  - 溶出度: 溶出度
  - 脆碎度: 脆碎度
  - 重量差异: 重量差异
  - 含量: UV-BPC含量
  - 微生物限度检查: 微生物限度-计数法
阿替洛尔片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 溶出度: 溶出度
  - 重量差异: 重量差异
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 有关物质: 有关物质
  - 溶出度: 溶出度
  - 重量差异: 重量差异
  - 脆碎度: 脆碎度
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
阿奇霉素胶囊:
- part: 一
  items:
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 装量差异: 装量差异
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 鉴别: 鉴别
  - 有关物质: 有关物质
  - 水分: 水分
  - 溶出度: 溶出度
  - 装量差异: 装量差异
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
鞣酸小檗碱片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: UV-对照法
- part: 二
  items:
  - 性状: 目测
  - 重量差异: 重量差异
  - 崩解时限: 崩解时限
  - 含量: UV-对照法
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别
  - 脆碎度: 脆碎度
  - 重量差异: 重量差异
  - 崩解时限: 崩解时限
  - 含量: UV-对照法
  - 微生物限度检查: 微生物限度-控制菌
克拉霉素 胶囊:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 溶出度: 溶出度
  - 装量差异: 装量差异
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别
  - 有关物质: 有关物质
  - 溶出度: 溶出度
  - 装量差异: 装量差异
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
复方芦丁片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: 复方芦丁含量
- part: 二
  items:
  - 性状: 目测
  - 重量差异: 重量差异
  - 崩解时限: 崩解时限
  - 含量: 复方芦丁含量
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别
  - 脆碎度: 脆碎度
  - 重量差异: 重量差异
  - 崩解时限: 崩解时限
  - 含量: 复方芦丁含量
  - 微生物限度检查: 微生物限度-控制菌
甘草酸二铵胶囊:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: UV-甘草酸二铵含量
- part: 二
  items:
  - 性状: 目测
  - 重量差异: 重量差异
  - 溶出度: 溶出度-甘草酸二铵UV
  - 含量: UV-甘草酸二铵含量
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 重量差异: 重量差异
  - 溶出度: 溶出度-甘草酸二铵UV
  - 含量: UV-甘草酸二铵含量
  - 微生物限度检查: 微生物限度-计数法
氢氯噻嗪片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 溶出度: 溶出度
  - 含量均匀度: 含量均匀度
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 有关物质: 有关物质
  - 溶出度: 溶出度
  - 含量均匀度: 含量均匀度
  - 脆碎度: 脆碎度
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
硝酸异山梨酯片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 鉴别: 鉴别
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 脆碎度: 脆碎度
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
盐酸左氧氟沙星胶囊:
- part: 一
  items:
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 装量差异: 装量差异
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 鉴别: 鉴别
  - 有关物质: 有关物质
  - 溶出度: 溶出度
  - 装量差异: 装量差异
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-控制菌
甲巯咪唑片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: 滴定
- part: 二
  items:
  - 性状: 目测
  - 崩解时限: 崩解时限
  - 含量均匀度: 含量均匀度
  - 含量: 滴定
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 脆碎度: 脆碎度
  - 含量均匀度: 含量均匀度
  - 崩解时限: 崩解时限
  - 含量: 滴定
  - 微生物限度检查: 微生物限度-计数法
泮托拉唑钠肠溶片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: UV-对照法
- part: 二
  items:
  - 性状: 目测
  - 重量差异: 重量差异
  - 酸中释放度: 溶出度
  - 释放度: 溶出度
  - 含量: UV-对照法
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 重量差异: 重量差异
  - 有关物质: 有关物质
  - 酸中释放度: 溶出度
  - 释放度: 溶出度
  - 耐酸力: UV-对照法
  - 含量: UV-对照法
  - 微生物限度检查: 微生物限度-计数法
辛伐他汀片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 含量均匀度: 含量均匀度
  - 有关物质: 有关物质
  - 溶出度: 溶出度
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
螺内酯片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别
  - 有关物质: 有关物质
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 脆碎度: 脆碎度
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
盐酸特拉唑嗪 胶囊:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别-BPC
  - 有关物质: 有关物质
  - 含量均匀度: 含量均匀度
  - 溶出度: 溶出度
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-控制菌
盐酸维拉帕米片:
- part: 一
  items:
  - 性状: 目测
  - 水分: 水分
  - 含量: HPLC
- part: 二
  items:
  - 性状: 目测
  - 装量差异: 装量差异
  - 溶出度: 溶出度
  - 含量: HPLC
- part: 三
  items:
  - 性状: 目测
  - 鉴别: 鉴别
  - 有关物质: 有关物质
  - 溶出度: 溶出度
  - 装量差异: 装量差异
  - 含量: HPLC
  - 微生物限度检查: 微生物限度-计数法
