// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { loadNewsWorkspace } from "@workspace/news/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

export const GET = createCommandRoute({
  buildCommand: ({ user }) => okCommand({ userId: user.userId }),
  action: loadNewsWorkspace,
});
