// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  EmploymentAgreementCommandSchema,
  EmploymentAgreementEmployeeParamsSchema,
  EmploymentAgreementListQuerySchema,
  buildHrRouteCommand,
  executeEmploymentAgreementCommand,
  listEmploymentAgreementsForEmployee,
} from "@workspace/hr/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { workspaceBusinessDate } from "@workspace/platform/server/business-date";
import { directCommandId } from "@workspace/platform/server/direct-command-meta";

export const GET = createCommandRoute({
  paramsSchema: EmploymentAgreementEmployeeParamsSchema,
  paramsError: "员工ID无效",
  querySchema: EmploymentAgreementListQuerySchema,
  queryError: "截至日期无效",
  buildCommand: ({ params, query }) => buildHrRouteCommand({ employeeId: params.id, asOfDate: query.asOf }),
  action: ({ employeeId, asOfDate }) => listEmploymentAgreementsForEmployee(employeeId, asOfDate),
});

export const POST = createCommandRoute({
  paramsSchema: EmploymentAgreementEmployeeParamsSchema,
  paramsError: "员工ID无效",
  bodySchema: EmploymentAgreementCommandSchema,
  bodyError: "协议生命周期命令无效",
  buildCommand: ({ params, body, user, request }) => buildHrRouteCommand({
    employeeId: params.id,
    command: body.kind === "end" && !body.effectiveThrough
      ? { ...body, effectiveThrough: workspaceBusinessDate(new Date()) }
      : body,
    userId: user.userId,
    idempotencyKey: directCommandId(request),
  }),
  action: executeEmploymentAgreementCommand,
});
