// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createCompatibilityProxyHandler } from "@workspace/platform/server/api";

export const runtime = "nodejs";

/** @deprecated Use the Library-owned deploy-unit endpoint. */
export const GET = createCompatibilityProxyHandler(
  "/api/modules/library/integrations/wecom/agent/artifacts",
  { sourcePathPrefix: "/api/integrations/wecom/agent/artifacts" },
);
