// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import {
  buildCreateWorkPlanCommand,
  buildListWorkPlansCommand,
  executeCreateWorkPlanCommand,
  executeListWorkPlansCommand,
} from "@workspace/work/server";

const workPlanSchema = z.object({
  kind: z.string().optional(),
  title: z.string().optional(),
  description: z.string().optional(),
  status: z.enum(["active", "done"]).optional(),
  ownerEmployeeId: z.coerce.number().nullable().optional(),
  collaborationId: z.coerce.number().nullable().optional(),
  okrCycleId: z.coerce.number().nullable().optional(),
  sourcePlanId: z.coerce.number().nullable().optional(),
  parentPeriodPlanId: z.coerce.number().nullable().optional(),
  previousPeriodPlanId: z.coerce.number().nullable().optional(),
  alignmentSourceType: z.string().nullable().optional(),
  alignmentSourcePlanId: z.coerce.number().nullable().optional(),
  alignmentSourceWorkItemId: z.coerce.number().nullable().optional(),
  periodType: z.string().nullable().optional(),
  actualStartDate: z.string().nullable().optional(),
  actualEndDate: z.string().nullable().optional(),
  plannedStartDate: z.string().nullable().optional(),
  plannedEndDate: z.string().nullable().optional(),
  isMilestone: z.boolean().optional(),
  milestoneDate: z.string().nullable().optional(),
  sourceType: z.string().optional(),
  sourceKind: z.string().nullable().optional(),
  sourceMeetingId: z.coerce.number().nullable().optional(),
  sourceMeetingDecisionId: z.coerce.number().nullable().optional(),
  sourceMeetingActionCandidateId: z.coerce.number().nullable().optional(),
  sourceDepartmentId: z.coerce.number().nullable().optional(),
  linkedProjectId: z.coerce.number().nullable().optional(),
  linkedProjectPhaseId: z.coerce.number().nullable().optional(),
  sortOrder: z.coerce.number().optional(),
  targetType: z.string().optional(),
  targetId: z.coerce.number().optional(),
  deptId: z.coerce.number().optional(),
}).strip();

const workPlanQuerySchema = z.object({
  targetType: z.string().nullable().optional(),
  targetId: z.coerce.number().nullable().optional(),
  deptId: z.coerce.number().nullable().optional(),
  kind: z.string().nullable().optional(),
  includeArchived: z.string().optional(),
}).passthrough();

export const GET = createCommandRoute({
  querySchema: workPlanQuerySchema,
  buildCommand: ({ user, query }) => buildListWorkPlansCommand({ user, query }),
  action: executeListWorkPlansCommand,
});

export const POST = createCommandRoute({
  bodySchema: workPlanSchema,
  bodyError: "工作计划参数无效",
  buildCommand: ({ user, body }) => buildCreateWorkPlanCommand({ user, body }),
  action: executeCreateWorkPlanCommand,
});
