// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  buildDeleteFinanceGroupAccountRouteCommand,
  buildUpdateFinanceGroupAccountRouteCommand,
  executeDeleteFinanceGroupAccountRouteCommand,
  executeUpdateFinanceGroupAccountRouteCommand,
} from "@workspace/finance/server/ledger/group-accounts";
import { routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { z } from "zod";

const updateGroupAccountSchema = z.object({
  code: z.string().min(1).max(32),
  name: z.string().min(1).max(100),
  category: z.enum(["asset", "liability", "common", "equity", "cost", "revenue", "expense"]),
  balanceDirection: z.enum(["debit", "credit"]),
  mnemonicCode: z.string().max(64).nullable(),
  currency: z.string().max(32).nullable(),
  parentGroupAccountId: z.number().int().positive().nullable(),
  consolidationRole: z.enum(["none", "intercompanyReceivable", "intercompanyPayable", "intercompanyRevenue", "intercompanyExpense", "investmentInSubsidiary", "shareCapital", "capitalReserve", "dividendReceivable", "dividendPayable", "inventory", "fixedAsset", "cashFlow", "difference"]),
  counterpartyRequirement: z.enum(["none", "optional", "required"]),
  movementType: z.enum(["closingBalance", "periodMovement", "transaction"]),
  translationRateType: z.never().optional(),
  expectedUpdatedAt: z.string().min(1),
});

export const PUT = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  bodySchema: updateGroupAccountSchema,
  bodyError: "集团科目资料不完整",
  buildCommand: ({ params, body, user }) => buildUpdateFinanceGroupAccountRouteCommand({
    userId: user.userId,
    groupAccountId: params.id,
    ...body,
  }),
  action: executeUpdateFinanceGroupAccountRouteCommand,
});

export const DELETE = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "集团科目参数无效",
  buildCommand: ({ params, user }) => buildDeleteFinanceGroupAccountRouteCommand({
    userId: user.userId,
    groupAccountId: params.id,
  }),
  action: executeDeleteFinanceGroupAccountRouteCommand,
});
