// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { serviceResponse } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { failCommand } from "@workspace/platform/server/domain-validation";
import { notificationPublicationRequestSchema } from "@workspace/platform/server/notification-definition-dsl";
import { buildNotificationPublicationCommand } from "@workspace/platform/server/notification-publishing";
import { publishConfiguredNotification } from "@workspace/platform/server/notifications";

const notificationPublicationBodySchema = notificationPublicationRequestSchema.omit({ idempotencyKey: true });

export const POST = createCommandRoute({
  bodySchema: notificationPublicationBodySchema,
  bodyError: "通知发布请求无效",
  buildCommand: ({ request, body, user }) => {
    const idempotencyKey = request.headers.get("idempotency-key")?.trim();
    if (!idempotencyKey) return failCommand("缺少 Idempotency-Key 请求头", 400, "idempotencyKey");
    return buildNotificationPublicationCommand({
      source: { kind: "user-api", id: String(user.userId), label: "个人 API 用户 " + user.userId },
      request: { ...body, idempotencyKey },
    });
  },
  action: async (command) => {
    const result = await publishConfiguredNotification(command);
    if (result.ok === false) return serviceResponse(result);
    return Response.json(result.data, { status: result.data.replayed ? 200 : 201 });
  },
});
