import "server-only";

import {
  FINANCE_BUDGET_DEPARTMENT_MONTHLY_SOURCE,
  FINANCE_BUDGET_RESEARCH_MONTHLY_SOURCE,
  FINANCE_BUDGET_VERSIONS_SOURCE,
  FINANCE_LEDGER_ACCOUNTS_SOURCE,
  FINANCE_ASSETS_ADJUSTMENTS_SOURCE,
  FINANCE_ASSETS_CARDS_SOURCE,
  FINANCE_ASSETS_METRICS_SOURCE,
  FINANCE_ASSETS_PERIOD_ROWS_SOURCE,
  FINANCE_LEDGER_BALANCES_SOURCE,
  FINANCE_LEDGER_COUNTERPARTY_BALANCES_SOURCE,
  FINANCE_LEDGER_GROUP_ACCOUNTS_SOURCE,
  FINANCE_LEDGER_PERIODS_SOURCE,
  FINANCE_LEDGER_RECLASS_RESULTS_SOURCE,
  FINANCE_LEDGER_RECLASS_RULE_CANDIDATES_SOURCE,
  FINANCE_LEDGER_VOUCHERS_SOURCE,
  FINANCE_STATEMENT_LINES_SOURCE,
} from "./workspace-analysis-sources";
import { FINANCE_WORKSPACE_ANALYSIS_CHILD_SOURCE_REGISTRATIONS } from "./workspace-analysis-child-sources";
import { FINANCE_WORKSPACE_ANALYSIS_DERIVED_SOURCE_REGISTRATIONS } from "./workspace-analysis-derived-sources";

export const FINANCE_GENERAL_WORKSPACE_ANALYSIS_SOURCE_REGISTRATIONS = [
  FINANCE_LEDGER_ACCOUNTS_SOURCE,
  FINANCE_LEDGER_BALANCES_SOURCE,
  FINANCE_LEDGER_COUNTERPARTY_BALANCES_SOURCE,
  FINANCE_LEDGER_PERIODS_SOURCE,
  FINANCE_LEDGER_VOUCHERS_SOURCE,
  FINANCE_LEDGER_RECLASS_RESULTS_SOURCE,
  FINANCE_LEDGER_RECLASS_RULE_CANDIDATES_SOURCE,
  FINANCE_LEDGER_GROUP_ACCOUNTS_SOURCE,
  FINANCE_ASSETS_CARDS_SOURCE,
  FINANCE_ASSETS_PERIOD_ROWS_SOURCE,
  FINANCE_ASSETS_ADJUSTMENTS_SOURCE,
  FINANCE_ASSETS_METRICS_SOURCE,
  FINANCE_BUDGET_VERSIONS_SOURCE,
  FINANCE_BUDGET_DEPARTMENT_MONTHLY_SOURCE,
  FINANCE_BUDGET_RESEARCH_MONTHLY_SOURCE,
  FINANCE_STATEMENT_LINES_SOURCE,
  ...FINANCE_WORKSPACE_ANALYSIS_CHILD_SOURCE_REGISTRATIONS,
  ...FINANCE_WORKSPACE_ANALYSIS_DERIVED_SOURCE_REGISTRATIONS,
] as const;
