// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  buildErpDiligenceEvidenceAttachmentRouteCommand,
  deleteErpDiligenceEvidenceAttachment,
  downloadErpDiligenceEvidenceAttachment,
  ErpDiligenceEvidenceAttachmentParamsSchema,
} from "@workspace/administration/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";

export const GET = createCommandRoute({
  paramsSchema: ErpDiligenceEvidenceAttachmentParamsSchema,
  paramsError: "附件标识无效",
  buildCommand: ({ params, user }) => buildErpDiligenceEvidenceAttachmentRouteCommand(params.attachmentUid, user.userId),
  action: downloadErpDiligenceEvidenceAttachment,
});

export const DELETE = createCommandRoute({
  paramsSchema: ErpDiligenceEvidenceAttachmentParamsSchema,
  paramsError: "附件标识无效",
  buildCommand: ({ params, user }) => buildErpDiligenceEvidenceAttachmentRouteCommand(params.attachmentUid, user.userId),
  action: deleteErpDiligenceEvidenceAttachment,
});
