// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { buildHrRouteCommand, getContracts } from "@workspace/hr/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const contractsQuerySchema = z.object({
  company: z.string().optional(),
  department: z.string().catch(""),
  isActive: z.string().nullable().optional(),
  keyword: z.string().optional(),
  position: z.string().catch(""),
  page: z.coerce.number().int().min(1).catch(1),
  pageSize: z.coerce.number().int().min(1).max(500).catch(50),
}).passthrough();

export const GET = createCommandRoute({
  querySchema: contractsQuerySchema,
  queryError: "参数错误",
  buildCommand: ({ query }) => buildHrRouteCommand(query),
  action: getContracts,
});
