export const FINANCE_CAPABILITY_INTERFACE_FILES = {
  "finance/analysis": [
    "server/workspace-analysis-child-sources.ts",
    "server/workspace-analysis-derived-sources.ts",
    "server/workspace-analysis-source-pages.ts",
    "server/workspace-analysis-source-registrations.ts",
    "server/workspace-analysis-sources.ts",
    "ui/analysis/FinanceAnalysisClient.tsx",
  ],
  "finance/assets": [
    "server/assets/close-provider.ts",
    "server/assets/fk-registry.ts",
    "server/assets/service.ts",
    "ui/assets/AssetsClient.tsx",
  ],
  "finance/budget": [
    "server/budget/budget-version.ts",
    "server/budget/service.ts",
    "ui/budget/BudgetTab.tsx",
  ],
  "finance/close": [
    "server/close/canonical-json.ts",
    "server/close/inspection-identity.ts",
  ],
  "finance/cost": [
    "server/cost/cost-structure-products.ts",
    "server/cost/domain/operational-analysis-template-lifecycle.ts",
    "server/cost/domain/operational-analysis-template-validation.ts",
    "server/cost/import.ts",
    "ui/cost/FinanceCostClient.tsx",
    "ui/cost/FinanceDepartmentShipmentView.tsx",
    "ui/cost/FinanceOperationalAnalysisPage.tsx",
    "ui/cost/FinancePersonalShipmentView.tsx",
    "ui/cost/FinanceProjectOperationalAnalysisView.tsx",
  ],
  "finance/import": [
    "server/domain/readable-import-validation.ts",
    "server/import/readable/archive-evidence.ts",
    "server/import/shared.ts",
    "server/import/validation.ts",
  ],
  "finance/ledger": [
    "server/domain/counterparty-classification-validation.ts",
    "server/ledger/accounts.ts",
    "server/ledger/balance-api.ts",
    "server/ledger/counterparty-balances.ts",
    "server/ledger/counterparty-period.ts",
    "server/ledger/group-accounts/company-account-resolver.ts",
    "server/ledger/group-accounts/mapped-local-accounts.ts",
    "server/ledger/group-accounts/policy-version-service.ts",
    "server/ledger/ledger-workbook.ts",
    "server/ledger/periods.ts",
    "server/ledger/reclass-results/list.ts",
    "server/ledger/reclass-rules/materialize-confirmed.ts",
    "server/ledger/route-commands.ts",
    "server/ledger/voucher-service.ts",
    "server/schedules/reclassify.ts",
    "ui/ledger/LedgerClient.tsx",
    "ui/ledger/defaultScope.ts",
    "ui/ledger/voucherCashFlow.ts",
  ],
  "finance/shared-ui": [
    "ui/components/AccountTable.tsx",
    "ui/components/FinanceFilters.tsx",
    "ui/components/VoucherItemTable.tsx",
    "ui/components/finance-page-spec.ts",
    "ui/components/latest-request-gate.ts",
    "ui/formatters.ts",
    "ui/navigation/nav-utils.ts",
    "ui/workbook-download.ts",
  ],
  "finance/statements": [
    "server/domain/consolidation-entry-validation.ts",
    "server/domain/consolidation-rule-validation.ts",
    "server/group-policy-scope.ts",
    "server/statements/config/balance-sheet-lines.ts",
    "server/statements/config/cash-flow-lines.ts",
    "server/statements/config/income-statement-lines.ts",
    "server/statements/config/load-config-reports.ts",
    "server/statements/consolidated-output-service.ts",
    "server/statements/consolidation-overview.ts",
    "server/statements/report-detail.ts",
    "server/statements/report-generator.ts",
    "server/statements/reports/cash-flow-system-amounts.ts",
    "server/statements/reports/direct.ts",
    "server/statements/statement-page-data.ts",
    "ui/statements/StatementsClient.tsx",
    "ui/statements/consolidation-period.ts",
    "ui/statements/finance-period-dataset.ts",
    "ui/statements/useFinancePeriodDataset.ts",
  ],
  "finance/tax": [
    "server/tax/registration-period-scope.ts",
    "server/tax/service.ts",
    "ui/tax/TaxClient.tsx",
  ],
  "finance/treasury": [
    "server/treasury/service.ts",
    "ui/treasury/TreasuryClient.tsx",
  ],
} as const satisfies Readonly<Record<string, readonly string[]>>;
