export const FINANCE_CAPABILITY_INTERFACE_FILES = {
  "finance/analysis": [
    "server/workspace-analysis-child-sources.ts",
    "server/workspace-analysis-derived-sources.ts",
    "server/workspace-analysis-source-pages.ts",
    "server/workspace-analysis-source-registrations.ts",
    "server/workspace-analysis-sources.ts",
    "ui/analysis/FinanceAnalysisClient.tsx",
  ],
  "finance/assets": [
    "server/assets/close-provider.ts",
    "server/assets/fk-registry.ts",
    "server/assets/service.ts",
    "ui/assets/AssetsClient.tsx",
  ],
  "finance/budget": [
    "server/budget/budget-version.ts",
    "server/budget/service.ts",
    "ui/budget/BudgetTab.tsx",
  ],
  "finance/close": [
    "server/close/canonical-json.ts",
    "server/close/inspection-identity.ts",
  ],
  "finance/cost": [
    "server/cost/cost-structure-products.ts",
    "server/cost/domain/operational-analysis-template-lifecycle.ts",
    "server/cost/domain/operational-analysis-template-validation.ts",
    "server/cost/import.ts",
    "ui/cost/FinanceCostClient.tsx",
    "ui/cost/FinanceDepartmentShipmentView.tsx",
    "ui/cost/FinanceOperationalAnalysisPage.tsx",
    "ui/cost/FinancePersonalShipmentView.tsx",
    "ui/cost/FinanceProjectOperationalAnalysisView.tsx",
  ],
  "finance/import": [
    "server/domain/readable-import-validation.ts",
    "server/import/readable/archive-evidence.ts",
    "server/import/shared.ts",
    "server/import/validation.ts",
  ],
  "finance/ledger": [
    "server/domain/counterparty-classification-validation.ts",
    "server/domain/group-chart-validation.ts",
    "server/ledger/account-usage.ts",
    "server/ledger/accounts.ts",
    "server/ledger/balance-api.ts",
    "server/ledger/counterparty-balances.ts",
    "server/ledger/counterparty-period.ts",
    "server/ledger/ledger-workbook.ts",
    "server/ledger/periods.ts",
    "server/ledger/route-commands.ts",
    "server/ledger/voucher-service.ts",
    "ui/ledger/LedgerClient.tsx",
    "ui/ledger/defaultScope.ts",
    "ui/ledger/useLedgerExportAction.ts",
    "ui/ledger/voucherCashFlow.ts",
    "server/ledger/validation.ts",
  ],
  "finance/ledger-group-accounts": [
    "server/ledger/group-accounts/company-account-resolver.ts",
    "server/ledger/group-accounts/mapped-local-accounts.ts",
    "server/ledger/group-accounts/mapping-review.ts",
    "server/ledger/group-accounts/policy-version-service.ts",
    "server/ledger/group-accounts/resolve.ts",
    "server/ledger/group-accounts/source-accounts.ts",
    "ui/ledger/groupAccountMappingPresentation.ts",
  ],
  "finance/ledger-reclassification": [
    "server/ledger/balance-reclass/automatic.ts",
    "server/ledger/balance-reclass/index.ts",
    "server/ledger/reclass-results/derived.ts",
    "server/ledger/reclass-results/list.ts",
    "server/ledger/reclass-results/review.ts",
    "server/ledger/reclass-rules/materialize.ts",
    "server/ledger/reclass-rules/materialize-confirmed.ts",
    "server/ledger/reclass-rules/resolution.ts",
    "server/ledger/reclassify/index.ts",
    "server/schedules/reclassify.ts",
    "ui/ledger/reclassRulePresentation.ts",
  ],
  "finance/shared-ui": [
    "ui/components/AccountTable.tsx",
    "ui/components/FinanceFilters.tsx",
    "ui/components/VoucherItemTable.tsx",
    "ui/components/finance-page-spec.ts",
    "ui/components/latest-request-gate.ts",
    "ui/formatters.ts",
    "ui/navigation/nav-utils.ts",
    "ui/workbook-download.ts",
  ],
  "finance/statements": [
    "server/domain/statement-exchange-rate-validation.ts",
    "server/statements/config/balance-sheet-lines.ts",
    "server/statements/config/cash-flow-lines.ts",
    "server/statements/config/income-statement-lines.ts",
    "server/statements/config/load-config-reports.ts",
    "server/statements/config/fixed-balance-definition.ts",
    "server/statements/group-voucher-numbering.ts",
    "server/statements/report-detail.ts",
    "server/statements/report-generator.ts",
    "server/statements/reports/cash-flow-system-amounts.ts",
    "server/statements/reports/direct.ts",
    "server/statements/statement-page-data.ts",
    "server/statements/shared/mapping-resolver.ts",
    "server/statements/statement-workbook-formulas.ts",
    "ui/statements/ReportLines.tsx",
    "ui/statements/StatementsClient.tsx",
    "ui/statements/finance-period-dataset.ts",
    "ui/statements/useFinancePeriodDataset.ts",
    "ui/statements/statement-assistant-context.ts",
    "ui/statements/statement-ui-types.ts",
    "ui/statements/useConsolidatedReport.ts",
    "ui/statements/useConsolidationDecisionWorkspace.ts",
  ],
  "finance/statement-consolidation": [
    "server/domain/consolidation-batch-delete-validation.ts",
    "server/domain/consolidation-batch-validation.ts",
    "server/domain/consolidation-entry-generation.ts",
    "server/domain/consolidation-entry-validation.ts",
    "server/domain/consolidation-fx-validation.ts",
    "server/domain/consolidation-rule-validation.ts",
    "server/domain/consolidation-scope-selection-validation.ts",
    "server/group-policy-scope.ts",
    "server/statements/consolidated-output-balance-lines.ts",
    "server/statements/consolidated-output-cash-flow.ts",
    "server/statements/consolidated-output-service.ts",
    "server/statements/consolidated-output-snapshots.ts",
    "server/statements/consolidated-line-amounts.ts",
    "server/statements/consolidation-adjustment-comparisons.ts",
    "server/statements/consolidation-comparative.ts",
    "server/statements/consolidation-mutations.ts",
    "server/statements/consolidation-workpaper-workbook.ts",
    "ui/statements/consolidation-columns.ts",
  ],
  "finance/consolidation-lifecycle": [
    "server/statements/consolidation-batch-delete.ts",
    "server/statements/consolidation-batches.ts",
    "server/statements/consolidation-company-directory.ts",
    "server/statements/consolidation-dto.ts",
    "server/statements/consolidation-fingerprints.ts",
    "server/statements/consolidation-lifecycle.ts",
    "server/statements/consolidation-overview.ts",
    "server/statements/consolidation-preparation.ts",
    "server/statements/consolidation-replay.ts",
    "server/statements/consolidation-scope-selections.ts",
    "server/statements/consolidation-snapshots.ts",
    "server/statements/consolidation-source-coverage.ts",
    "server/statements/consolidation-sources.ts",
    "ui/statements/consolidation-period.ts",
  ],
  "finance/statement-exchange-translation": [
    "server/statements/chinamoney-exchange-rates.ts",
    "server/statements/consolidated-output-translation.ts",
    "server/statements/consolidation-frozen-rates.ts",
    "server/statements/consolidation-rate-applications.ts",
    "server/statements/consolidation-remittance-fx-entries.ts",
    "server/statements/exchange-rates.ts",
  ],
  "finance/tax": [
    "server/tax/registration-period-scope.ts",
    "server/tax/service.ts",
    "ui/tax/TaxClient.tsx",
  ],
  "finance/treasury": [
    "server/treasury/service.ts",
    "ui/treasury/TreasuryClient.tsx",
  ],
} as const satisfies Readonly<Record<string, readonly string[]>>;
