export const HR_CAPABILITY_INTERFACE_FILES = {
  "hr/analysis": [
    "ui/analytics/HRAnalyticsClient.tsx",
    "ui/analytics/contract-helpers.ts",
    "ui/analytics/employee/useEmployeeData.ts",
    "ui/analytics/position/usePositionData.ts",
    "ui/analytics/useAnalyticsData.ts",
    "ui/analytics/useHeadcountData.ts",
  ],
  "hr/code-governance": [
    "server/domain/code-governance-validation.ts",
    "ui/code-helpers.ts",
    "ui/code/CodeTab.tsx",
    "ui/code/useCodeTab.ts",
  ],
  "hr/data-quality": [
    "server/audit-entities.ts",
    "server/data-quality-trigger.ts",
    "server/domain/audit-restore-validation.ts",
    "ui/audit/AuditLogModal.tsx",
  ],
  "hr/employment-lifecycle": [
    "server/domain/employment-agreement-attachment-validation.ts",
    "server/domain/employment-agreement-change.ts",
    "server/domain/employment-agreement-temporal-policy.ts",
    "server/domain/employment-agreement-validation.ts",
    "server/domain/employment-validation.ts",
    "server/domain/page-draft-validation.ts",
    "server/employments.ts",
    "utils/employment-selection.ts",
  ],
  "hr/employee-records": [
    "server/domain/employee-business-temporal.ts",
    "server/domain/employee-social-insurance-validation.ts",
    "server/employee-history.ts",
    "server/employee-lifecycle.ts",
    "server/employee-period-corrections.ts",
    "server/employee-period-creates.ts",
    "server/employee-profile.ts",
    "server/employee-position-filters.ts",
    "server/employees.ts",
    "server/roster-generated.ts",
    "server/roster.ts",
    "ui/generated/RosterGeneratedTab.tsx",
    "ui/profile/EmployeeDirectory.tsx",
    "ui/profile/EmployeeProfileClient.tsx",
    "ui/profile/EmployeeProfilePageClient.tsx",
    "ui/profile/ProfileFormControls.tsx",
    "ui/profile/lunar-birthday.ts",
  ],
  "hr/employment-agreements": [
    "server/contract-records.ts",
    "server/contracts.ts",
    "server/employment-agreement-attachments.ts",
    "server/employment-agreements.ts",
  ],
  "hr/social-insurance": [
    "server/employee-social-insurance.ts",
  ],
  "hr/organization": [
    "server/department-approvals.ts",
    "server/department-codes.ts",
    "server/department-manager-positions.ts",
    "server/departments.ts",
    "server/department-reference-adapter.ts",
    "ui/tabs/department-position/department-position-main-content.tsx",
    "ui/tabs/department-position/description-details.ts",
    "ui/tabs/department-position/department-workflow.tsx",
    "ui/tabs/department-position/derived-state.ts",
    "ui/tabs/department-position/organization-mode-panel.tsx",
    "ui/tabs/department-position/types.ts",
    "ui/tabs/department-position/use-department-position-actions.ts",
    "ui/tabs/department-position/use-department-position-data.ts",
    "ui/tabs/department-position/use-department-position-drafts.ts",
    "ui/tabs/department-position/use-department-position-navigation.tsx",
    "ui/tabs/department-position/use-department-position-side-effects.ts",
    "ui/tabs/department-position/use-department-position-tree-renderers.tsx",
    "ui/tabs/department-position/use-department-position-view-renderers.tsx",
    "ui/tabs/department-position/utils.ts",
    "utils/department-code-cascade.ts",
    "utils/department-path.ts",
  ],
  "hr/positions": [
    "server/domain/position-description-revision.ts",
    "server/domain/position-description-template-validation.ts",
    "server/domain/position-description-validation.ts",
    "server/position-codes.ts",
    "server/position-organization-scope.ts",
    "server/position-responsibility-nodes.ts",
    "server/positions.ts",
  ],
  "hr/position-descriptions": [
    "server/domain/position-report-override-validation.ts",
    "server/edp-report-to.ts",
    "server/edps.ts",
    "server/position-description-template-store.ts",
    "server/position-description-reference-adapter.ts",
    "server/position-description-revision-service.ts",
    "server/position-descriptions.ts",
    "server/position-report-overrides.ts",
    "ui/tabs/department-position/use-position-description-templates.ts",
  ],
  "hr/organization-structure": [
    "server/domain/organization-effective-version.ts",
    "server/domain/organization-structure-command.ts",
    "server/organization-structure-route-meta.ts",
    "server/organization-structure-lifecycle-service.ts",
    "ui/organization/OrganizationChartTab.tsx",
  ],
  "hr/performance": [
    "server/performance-access.ts",
    "server/performance.ts",
    "ui/performance/EmployeePerformanceClient.tsx",
    "ui/performance/HrPerformanceClient.tsx",
  ],
  "hr/shared-contracts": [
    "business-temporal.ts",
    "server/field-validation.ts",
    "server/fk-registry.ts",
    "server/hr-crud.ts",
    "server/reference-guards.ts",
    "utils/identity.ts",
  ],
  "hr/shared-ui": [
    "server/autocomplete.ts",
    "ui/components/EthnicityPicker.tsx",
    "ui/components/MajorPicker.tsx",
    "ui/components/ProfessionalTitlePicker.tsx",
    "ui/components/RankPicker.tsx",
    "ui/components/SchoolPicker.tsx",
    "ui/components/hr-toolbar-items.ts",
    "ui/fk-keys.ts",
    "ui/hooks/useScrollToAddedItem.ts",
    "ui/roster-surface.ts",
  ],
} as const satisfies Readonly<Record<string, readonly string[]>>;
