export const PLATFORM_CAPABILITY_INTERFACE_FILES = {
  "platform/agent-runtime": [
    "agent-permission-policy.ts",
    "server/agent-actor-user-policy.ts",
    "server/agent-api-delegation.ts",
    "server/wecom-notification-worker-auth.ts",
    "ui/AgentConversationSurface.tsx",
    "ui/agent-markdown.ts",
  ],
  "platform/business-governance": [
    "action-contract-registry.ts",
    "api-registry.ts",
    "business-action-registry.ts",
    "business-code-config.ts",
    "server/business-codes/index.ts",
    "server/business-temporal-idempotency.ts",
    "server/business-temporal-prisma.ts",
    "server/data-quality-scheduler.ts",
    "ui/business-temporal-records.ts",
    "ui/business-temporal-view.ts",
  ],
  "platform/documents-content": [
    "server/docs-editor-space-adapter.ts",
  ],
  "platform/identity-access": [
    "permission-actions.ts",
    "permission-api-action-policy.ts",
    "resources.ts",
    "server/auth-token.ts",
    "server/auth/admin.ts",
    "server/auth/root.ts",
    "server/business-space-permissions.ts",
    "server/permission-review-scheduler.ts",
    "server/rbac/action-grants.ts",
    "server/rbac/admin-scope.ts",
    "server/user-preferences.ts",
    "server/with-auth.ts",
    "space-registry.ts",
    "space-resource-model.ts",
    "ui/LoginClient.tsx",
    "ui/UserMenu.tsx",
    "ui/space-preferences.ts",
    "ui/space-workbench.ts",
  ],
  "platform/notifications": [
    "server/notification-definition-dsl.ts",
    "server/notification-delivery-outbox.ts",
    "server/notification-publishing-storage.ts",
    "server/notification-workflow.ts",
    "server/notifications.ts",
    "ui/NotificationBell.tsx",
  ],
  "platform/platform-foundation": [
    "integrations/wecom-login-panel.ts",
    "route-runtime-labels.ts",
    "search.ts",
    "server/api-route.ts",
    "server/api.ts",
    "server/business-date.ts",
    "server/delete-guard.ts",
    "server/domain-validation.ts",
    "server/history.ts",
    "server/internal-unit-identity.ts",
    "server/internal-unit-rpc.ts",
    "server/prisma.ts",
    "server/system-config.ts",
    "server/tenant-config.ts",
  ],
  "platform/relations-data": [
    "server/company-directory.ts",
    "server/relation-registry.ts",
    "server/relation-targets.ts",
    "server/resolve-fk.ts",
  ],
  "platform/shared-ui": [
    "icons.tsx",
    "ui/api-client.ts",
    "ui/page-assistant/PageAssistantComposer.tsx",
    "ui/page-assistant/PageAssistantMessages.tsx",
    "ui/page-assistant/agent-stream.ts",
    "ui/page-assistant/conversation-state.ts",
    "ui/page-assistant/proposal-settlement.ts",
    "ui/page-assistant/types.ts",
    "ui/page-assistant/useAgentProfileSelector.ts",
    "ui/responsibility-fields.ts",
  ],
  "platform/shell-navigation": [
    "effective-module-registry.ts",
    "module-lifecycle.ts",
    "module-nav.tsx",
    "module-registry-utils.ts",
    "module-registry.ts",
    "modules.tsx",
    "server/module-runtime.ts",
    "ui/ModuleHome.tsx",
    "ui/NavLink.tsx",
    "ui/PortalClient.tsx",
    "ui/app-shell-page.tsx",
    "ui/portal-page.tsx",
    "ui/useDeployUnitNavigation.ts",
  ],
  "platform/workflow-approvals": [
    "server/approval-commit-authorization.ts",
    "server/approvals.ts",
    "server/approvals/workflow.ts",
    "server/workflow-inbox-projection.ts",
    "server/workflow-inbox-records.ts",
    "server/workflow-todo-providers.ts",
    "server/workflows.ts",
    "ui/WorkflowStatusBadge.tsx",
    "workflow-management-resources.ts",
  ],
} as const satisfies Readonly<Record<string, readonly string[]>>;
