export const WORK_CAPABILITY_INTERFACE_FILES = {
  "work/collaboration": [
    "server/access.ts",
    "server/department-collaboration-notification-actions.ts",
    "server/department-collaboration-route-command.ts",
    "server/department-collaborations.ts",
    "server/department-home.ts",
    "server/department-space-access.ts",
    "server/domain/department-collaboration-validation.ts",
    "server/work-collaboration-references.ts",
    "server/work-owner-eligibility.ts",
    "server/work-owner-scopes.ts",
    "server/work-responsibility-references.ts",
    "server/work-source-departments.ts",
    "server/work-superior-employees.ts",
    "ui/works/work-responsibility-fields.ts",
  ],
  "work/meetings": [
    "server/meetings/access.ts",
    "server/meetings/analysis-sources.ts",
    "server/meetings/application.ts",
    "server/meetings/dto.ts",
    "ui/meetings/MeetingsPage.tsx",
    "ui/meetings/pages.tsx",
  ],
  "work/mutation-impact": [
    "server/domain/work-mutation-impact-validation.ts",
    "server/work-mutation-impact.ts",
  ],
  "work/okr-governance": [
    "server/domain/work-okr-governance-policy.ts",
    "server/domain/work-performance-submission-period.ts",
    "server/domain/work-system-okr-cycle-visibility.ts",
    "server/work-assigned-alignment-options.ts",
    "server/work-assigned-items.ts",
    "server/work-goal-request-guard.ts",
    "server/work-kr-evidence.ts",
    "server/work-okr-control-admin.ts",
    "server/work-okr-control-config.ts",
    "server/work-okr-control.ts",
    "server/work-okr-cycles.ts",
    "server/work-okr-settings.ts",
    "server/work-okr-stage.ts",
    "ui/works/WorkOkrPlanSurface.tsx",
    "ui/works/work-okr-settings-types.ts",
    "ui/works/work-target-presentation.ts",
  ],
  "work/kpi-scorecards": [
    "server/work-kpi-dto.ts",
    "server/work-kpi-mutation-impact-adapters.ts",
    "server/work-kpi-results.ts",
    "server/work-kpi-route-command.ts",
    "server/work-kpi-scorecard.ts",
  ],
  "work/plan-scheduling": [
    "server/domain/work-plan-governance-validation.ts",
    "server/domain/work-plan-item-state.ts",
    "server/domain/work-plan-maintenance-policy.ts",
    "server/work-period-collection.ts",
    "server/work-period-relations.ts",
    "server/work-period-schedule-approval.ts",
    "server/work-period-schedule-mutation-executor.ts",
    "server/work-period-schedule.ts",
    "server/work-pilot-inbound-impact-adapters.ts",
    "server/work-plan-governance.ts",
    "server/work-plan-dto.ts",
    "server/work-plan-route-command.ts",
    "server/work-plans.ts",
    "ui/works/WorkPeriodScheduleMatrix.tsx",
    "ui/works/WorkPlanFields.tsx",
    "ui/works/WorkPlanSections.tsx",
    "ui/works/period-collection-types.ts",
  ],
  "work/projects": [
    "server/domain/project-preference-validation.ts",
    "server/domain/project-validation.ts",
    "server/project-action-runtime.ts",
    "ui/tabs/ProjectTab.tsx",
  ],
  "work/project-governance": [
    "server/project-approvals.ts",
    "server/project-normalization.ts",
    "server/project-preferences.ts",
    "server/projects.ts",
    "server/work-project-mutation-impact-adapters.ts",
  ],
  "work/project-membership": [
    "server/project-access-temporal.ts",
    "server/project-member-department-scope.ts",
    "server/project-member-notification-actions.ts",
    "server/project-members.ts",
    "server/project-membership-mutation-impact-adapters.ts",
    "server/project-membership-lifecycle-service.ts",
    "server/project-space-action-access.ts",
    "server/project-spaces.ts",
  ],
  "work/project-notifications": [
    "server/domain/project-notification-audience-validation.ts",
    "server/domain/project-notification-condition.ts",
    "server/domain/project-notification-rule-validation.ts",
    "server/domain/project-notification-write-validation.ts",
    "server/project-notification-evaluator.ts",
    "server/project-notification-redrive.ts",
    "server/project-notification-route-commands.ts",
    "server/project-notification-rules.ts",
    "server/project-notification-signals.ts",
  ],
  "work/reporting-analysis": [
    "server/domain/work-report-validation.ts",
    "server/domain/work-report-workflow-action.ts",
    "server/domain/work-reporting-policy.ts",
    "server/report-work-items.ts",
    "server/weekly-report-group-notifications.ts",
    "server/work-report-action-runtime.ts",
    "server/work-report-mutation-executor.ts",
    "server/work-report-normalization.ts",
    "ui/works/WorkReportPayload.ts",
    "ui/works/WorkReportingSettingsSection.ts",
    "work-report-periods.ts",
  ],
  "work/workspace-analysis-sources": [
    "server/workspace-analysis-assigned-sources.ts",
    "server/workspace-analysis-collaboration-kpi-sources.ts",
    "server/workspace-analysis-kpi-result-sources.ts",
    "server/workspace-analysis-kpi-scorecard-sources.ts",
    "server/workspace-analysis-period-collection-sources.ts",
    "server/workspace-analysis-project-gantt-sources.ts",
    "server/workspace-analysis-project-plan-detail-sources.ts",
    "server/workspace-analysis-report-sources.ts",
    "server/workspace-analysis-source-access.ts",
  ],
  "work/workspace-analysis-runtime": [
    "server/workspace-analysis-source-executor.ts",
    "server/workspace-analysis-sources.ts",
  ],
  "work/shared-contracts": [
    "business-temporal.ts",
    "server/fk-registry.ts",
    "server/standard-space-seeds.ts",
  ],
  "work/task-spaces": [
    "server/task-spaces.ts",
  ],
  "work/task-workbench": [
    "ui/works/WorkSpaceSidebar.tsx",
    "ui/works/WorkSpaceTopNavigation.ts",
    "ui/works/WorksClient.tsx",
    "ui/works/WorksPage.tsx",
    "ui/works/works-client-helpers.tsx",
  ],
  "work/task-workbench-model": [
    "ui/works/api.ts",
    "ui/works/model.ts",
    "ui/works/space-paths.ts",
    "ui/works/types.ts",
    "ui/works/work-status-filter.ts",
  ],
  "work/task-approvals": [
    "server/task-approval-adapter.ts",
    "server/task-approval-handlers.ts",
    "server/task-approval-helpers.ts",
    "server/task-approval-reference-adapter.ts",
    "server/task-approval-reports.ts",
    "server/task-approvals.ts",
    "server/task-reports.ts",
    "ui/works/WorkApprovalInboxDetail.tsx",
  ],
  "work/task-execution": [
    "server/domain/work-item-relation-state.ts",
    "server/domain/work-item-relation-validation.ts",
    "server/domain/work-item-revision.ts",
    "server/domain/work-item-source-validation.ts",
    "server/domain/work-item-validation.ts",
    "server/work-item-dto.ts",
    "server/work-item-mutation-executor.ts",
    "server/work-item-mutation-guard.ts",
    "server/work-task-route-command.ts",
    "server/work-task-action-runtime.ts",
    "server/work-task-workflow-policy.ts",
    "server/works.ts",
    "ui/works/WorkTaskTable.tsx",
    "ui/works/WorkTaskFields.tsx",
  ],
} as const satisfies Readonly<Record<string, readonly string[]>>;
