// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";

import { jsonErrorResponse } from "@workspace/platform/server/api";
import { isSuperAdmin, requireAdminApiAccess } from "@workspace/platform/server/auth";
import { listDatabaseSchemaCatalog } from "@workspace/settings/server/database-schema";

export async function GET(request: Request) {
  const auth = await requireAdminApiAccess(request);
  if (!auth.ok) return auth.response;
  if (!(await isSuperAdmin(auth.user.userId))) return jsonErrorResponse("无权限", 403);

  try {
    return NextResponse.json(await listDatabaseSchemaCatalog());
  } catch (error) {
    console.error("database schema catalog load failed", error);
    return jsonErrorResponse("加载数据关系失败", 500);
  }
}
