// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";
import { getPermissionGrantData, mergeBusinessSpaceActionsIntoPermissionGrantData } from "@workspace/platform/server/permission-subjects";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";
import {
  getStandardSpacePermissionGrantData,
  queryStandardSpacePermissionFlag,
  resolveStandardSpacePermissionResourceKey,
  setStandardSpacePermissionGrant,
  standardSpacePermissionActionSchema,
  type StandardSpacePermissionTargetType,
} from "@workspace/platform/server/standard-space-permission-route";
import { canManageWorkProjectPermissionResource, normalizeWorkProjectSpaceTargetType, workProjectSpaceScopeId } from "@workspace/work/server";

const paramsSchema = z.object({ targetType: z.enum(["personal", "user", "company", "committee", "department"]), targetId: z.coerce.number().int().positive() });

const workProjectSpacePermissionConfig = {
  registrationKey: "work.projects",
  deniedText: "无权限管理该项目空间",
  canManage: ({ userId, targetType, targetId, resourceKey }: { userId: number; targetType: StandardSpacePermissionTargetType; targetId: number; resourceKey: string }) =>
    canManageWorkProjectPermissionResource(userId, targetType, targetId, resourceKey),
  loadPermissionGrantData: getPermissionGrantData,
  mergeBusinessSpaceActions: mergeBusinessSpaceActionsIntoPermissionGrantData,
};

function normalizeTargetType(targetType: string): StandardSpacePermissionTargetType {
  return normalizeWorkProjectSpaceTargetType(targetType);
}

export const GET = createCommandRoute({
  paramsSchema,
  paramsError: "项目空间参数无效",
  buildCommand: ({ params, user, searchParams }) => {
    const targetType = normalizeTargetType(params.targetType);
    return okCommand({
      userId: user.userId,
      targetType,
      targetId: params.targetId,
      scopeId: workProjectSpaceScopeId(targetType, params.targetId),
      resourceKey: resolveStandardSpacePermissionResourceKey({
        targetType,
        searchParams,
        rootResourceKey: "work.projects",
        spaceResourceKind: "projects",
      }),
      includeNatural: queryStandardSpacePermissionFlag(searchParams, "includeNatural", true),
      includeImplicit: queryStandardSpacePermissionFlag(searchParams, "includeImplicit", true),
      includeStored: queryStandardSpacePermissionFlag(searchParams, "includeStored", true),
    });
  },
  action: (command) => getStandardSpacePermissionGrantData(command, workProjectSpacePermissionConfig),
});

export const PUT = createCommandRoute({
  paramsSchema,
  paramsError: "项目空间参数无效",
  bodySchema: standardSpacePermissionActionSchema,
  bodyError: "权限参数无效",
  buildCommand: ({ params, body, user, searchParams }) => {
    const targetType = normalizeTargetType(params.targetType);
    return okCommand({
      actorUserId: user.userId,
      targetType,
      targetId: params.targetId,
      scopeId: workProjectSpaceScopeId(targetType, params.targetId),
      subjectId: body.subjectId,
      actionKey: body.actionKey,
      value: body.value,
      resourceKey: resolveStandardSpacePermissionResourceKey({
        targetType,
        searchParams,
        rootResourceKey: "work.projects",
        spaceResourceKind: "projects",
      }),
    });
  },
  action: (command) => setStandardSpacePermissionGrant(command, workProjectSpacePermissionConfig),
});
