// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { updateEmployeeProfileEdps, buildHrRouteCommand } from "@workspace/hr/server";
import { routeIdParamsSchema, rowsRequestBodySchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";export const PUT = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "员工ID无效",
  bodySchema: rowsRequestBodySchema,
  bodyError: "参数错误",
  buildCommand: ({ params, body, user }) => buildHrRouteCommand({
    employeeId: params.id,
    rows: body.rows,
    userId: user.userId,
  }),
  action: ({ employeeId, rows, userId }) => updateEmployeeProfileEdps(employeeId, rows, userId),
});
