// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import type { Metadata } from "next";
import "./globals.css";
import AppVersionGuard from "@workspace/platform/ui/AppVersionGuard";
import WorkspacePageAssistantProvider from "@workspace/platform/ui/PageAssistantProvider";
import { FeedbackProvider, UiProvider } from "@workspace/core/ui";
import { getAppVersion } from "@workspace/platform/server/app-version";
import { getCurrentUser } from "@workspace/platform/server/auth";
import { getTenantPublicConfig } from "@workspace/platform/server/tenant-config";
import { TenantConfigProvider } from "@workspace/platform/ui/tenant-config";

export async function generateMetadata(): Promise<Metadata> {
  const tenant = getTenantPublicConfig();
  return {
    title: tenant.identity.appName,
    description: tenant.identity.appDescription,
  };
}

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const appVersion = getAppVersion();
  const tenantConfig = getTenantPublicConfig();
  const user = await getCurrentUser();
  const canUseAgentAssistant = user?.visibleSubmitResourceKeys?.includes("agent") ?? false;

  return (
    <html lang="zh-CN" className="h-full antialiased">
      <body className="min-h-full flex flex-col">
        <TenantConfigProvider config={tenantConfig}>
          <UiProvider>
            <FeedbackProvider>
              <WorkspacePageAssistantProvider enabled={canUseAgentAssistant}>
                <AppVersionGuard version={appVersion} />
                {children}
              </WorkspacePageAssistantProvider>
            </FeedbackProvider>
          </UiProvider>
        </TenantConfigProvider>
      </body>
    </html>
  );
}
