// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";
import { z } from "zod";

import { jsonErrorResponse, routeIdParamsSchema } from "@workspace/platform/server/api";
import { requireApiAccess } from "@workspace/platform/server/auth";
import { callWorkspaceInternalJson } from "@workspace/platform/server/internal-unit-rpc";

const bodySchema = z.object({ action: z.enum(["read", "acknowledge", "reject", "clear"]) });

export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth.response;
  const [rawParams, body] = await Promise.all([context.params, request.json().catch(() => null)]);
  const params = routeIdParamsSchema.safeParse(rawParams);
  const parsedBody = bodySchema.safeParse(body);
  if (!params.success || !parsedBody.success) return jsonErrorResponse("参数错误", 400);
  return NextResponse.json(await callWorkspaceInternalJson({
    callerUnitId: "workspace-shell",
    path: "/api/modules/work/internal/account",
    targetUnitId: "work",
    body: {
      operation: "notification.update",
      userId: auth.user.userId,
      id: params.data.id,
      action: parsedBody.data.action,
    },
  }));
}
