// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  ContractRecordCreateSchema,
  executeCreateContractRecord,
} from "@workspace/administration/server";
import { routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

export const POST = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "无效ID",
  bodySchema: ContractRecordCreateSchema,
  buildCommand: ({ params, body, user }) => okCommand({ contractId: params.id, body, userId: user.userId }),
  action: executeCreateContractRecord,
});
