// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { notificationDefinitionSaveSchema } from "@workspace/platform/server/notification-definition-dsl";
import { createApiRouteHandler, createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";
import { listNotificationPublishingConsoleData } from "@workspace/platform/server/notification-publishing-console";
import { saveNotificationDefinition } from "@workspace/platform/server/notification-publishing";

export const GET = createApiRouteHandler({
  handler: ({ user }) => listNotificationPublishingConsoleData(user.userId),
});

export const POST = createCommandRoute({
  bodySchema: notificationDefinitionSaveSchema,
  bodyError: "通知定义无效",
  buildCommand: ({ body }) => okCommand(body),
  action: (input, { user }) => saveNotificationDefinition(user.userId, input),
});
