// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { deployUnitVersionResponse } from "@workspace/platform/server/deploy-unit-runtime";

export function GET() {
  return deployUnitVersionResponse();
}
