// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { redirect } from "next/navigation";

import { workspacePath } from "@workspace/core/routing";
import { requireRouteAccess } from "@workspace/platform/server/auth";

export default async function WorkPerformancePage() {
  await requireRouteAccess("/work/me");
  redirect(workspacePath("/hr/performance/self"));
}
