// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { evaluatePermissionAction, requireRouteAccess } from "@workspace/platform/server/auth";
import { renderAppShellPage } from "@workspace/platform/ui/app-shell-page";
import { getDefaultInventoryScope } from "@workspace/inventory/server/service";
import { InventoryOperationsClient } from "@workspace/inventory/ui";

export default async function InventoryOperationsPage() {
  const user = await requireRouteAccess("/inventory/operations");
  const [defaultScope, canCreate, canUpdate, canReverse, canLock] = await Promise.all([
    getDefaultInventoryScope(),
    evaluatePermissionAction(user.id, "inventory.operations", "create"),
    evaluatePermissionAction(user.id, "inventory.operations", "update"),
    evaluatePermissionAction(user.id, "inventory.operations", "reverse"),
    evaluatePermissionAction(user.id, "inventory.operations", "lock"),
  ]);
  return renderAppShellPage({
    title: "库存运营",
    backHref: "/inventory",
    user,
    children: <InventoryOperationsClient defaultScope={defaultScope} canCreate={canCreate} canUpdate={canUpdate} canReverse={canReverse} canLock={canLock} />,
  });
}
