// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { evaluatePermissionAction, requireRouteAccess } from "@workspace/platform/server/auth";
import { renderAppShellPage } from "@workspace/platform/ui/app-shell-page";
import { getDefaultFinanceLedgerScope } from "@workspace/finance/server/ledger/periods";
import { LedgerClient } from "@workspace/finance/ui";

export default async function FinanceLedgerPage() {
  const user = await requireRouteAccess("/finance/ledger");
  const [canCreate, canUpdate, canDelete, canRevise, canExport, canApproveLedger, defaultScope] = await Promise.all([
    evaluatePermissionAction(user.id, "finance.ledger", "create"),
    evaluatePermissionAction(user.id, "finance.ledger", "update"),
    evaluatePermissionAction(user.id, "finance.ledger", "delete"),
    evaluatePermissionAction(user.id, "finance.ledger", "revise"),
    evaluatePermissionAction(user.id, "finance.ledger", "export"),
    evaluatePermissionAction(user.id, "finance.ledger", "approve"),
    getDefaultFinanceLedgerScope(),
  ]);

  return renderAppShellPage({
    title: "总账基础",
    backHref: "/finance",
    user,
    children: (
    <LedgerClient
      canCreate={canCreate}
      canUpdate={canUpdate}
      canDelete={canDelete}
      canRevise={canRevise}
      canExport={canExport}
      canApproveLedger={canApproveLedger}
      defaultScope={defaultScope}
      user={user}
    />
    ),
  });
}
