// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";
import {
  buildProjectSubmissionActionRouteCommand,
  executeRejectProjectSubmissionRouteCommand,
} from "@workspace/work/server";
import { routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const bodySchema = z.object({
  comment: z.string().nullable().optional(),
  version: z.coerce.number().nullable().optional(),
}).strict().optional();

export const POST = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "项目确认单 ID 无效",
  bodySchema,
  optionalJsonBody: true,
  bodyError: "驳回参数无效",
  buildCommand: ({ params, body, user }) => buildProjectSubmissionActionRouteCommand({ userId: user.userId, requestId: params.id, body }),
  action: executeRejectProjectSubmissionRouteCommand,
});
