// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { evaluatePermissionAction, requireRouteAccess } from "@workspace/platform/server/auth";
import { renderAppShellPage } from "@workspace/platform/ui/app-shell-page";
import { StatementsClient } from "@workspace/finance/ui";

export default async function FinanceStatementsPage() {
  const user = await requireRouteAccess("/finance/statements");
  const [canCreate, canUpdate, canUpdateConsolidationScope, canDelete, canSubmit, canApprove, canReject, canLock, canExport] = await Promise.all([
    evaluatePermissionAction(user.id, "finance.statements", "create"),
    evaluatePermissionAction(user.id, "finance.statements", "update"),
    evaluatePermissionAction(user.id, "capitalSecurities.governance", "update"),
    evaluatePermissionAction(user.id, "finance.statements", "delete"),
    evaluatePermissionAction(user.id, "finance.statements", "submit"),
    evaluatePermissionAction(user.id, "finance.statements", "approve"),
    evaluatePermissionAction(user.id, "finance.statements", "reject"),
    evaluatePermissionAction(user.id, "finance.statements", "lock"),
    evaluatePermissionAction(user.id, "finance.statements", "export"),
  ]);

  return renderAppShellPage({
    title: "财务报表",
    backHref: "/finance",
    user,
    children: <StatementsClient capabilities={{ canCreate, canUpdate, canUpdateConsolidationScope, canDelete, canSubmit, canApprove, canReject, canLock, canExport }} />,
  });
}
