// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createElement } from "react";
import { LoginClient } from "@workspace/platform/ui";

export default function LoginPage() {
  return createElement(LoginClient);
}
