// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NewsWorkspaceClient } from "@workspace/news/ui";
import { requireRouteAccess } from "@workspace/platform/server/auth";
import { renderAppShellPage } from "@workspace/platform/ui/app-shell-page";

export default async function NewsPage() {
  const user = await requireRouteAccess("/news");
  return renderAppShellPage({
    title: "资讯",
    backHref: "/portal",
    user,
    children: <NewsWorkspaceClient />,
  });
}
