// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";
import { z } from "zod";
import { requireApiAccess } from "@workspace/platform/server/auth";
import { changeUserProfile, getUserAccountProfile } from "@workspace/platform/server/account";
import { jsonErrorResponse } from "@workspace/platform/server/api";

const accountProfileSchema = z.object({
  username: z.string().trim().min(1, "用户名不能为空").max(64, "用户名过长"),
  alias: z.string().trim().max(512, "别名过长").nullable().optional(),
  phone: z.string().trim().max(64, "电话过长").nullable().optional(),
});

export async function GET(request: Request) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth.response;

  return NextResponse.json(await getUserAccountProfile(auth.user.userId));
}

export async function PUT(request: Request) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth.response;

  const body = await request.json().catch(() => null);
  const parsed = accountProfileSchema.safeParse(body);
  if (!parsed.success) {
    return jsonErrorResponse(parsed.error.issues[0]?.message || "参数错误", 400);
  }

  const result = await changeUserProfile(auth.user.userId, parsed.data);
  if (!result.success) {
    return jsonErrorResponse(result.error, result.status);
  }

  return NextResponse.json({ success: true, profile: result.profile });
}
