// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildDeleteConsolidationBatchRouteCommand,
  executeDeleteConsolidationBatchRouteCommand,
} from "@workspace/finance/server/statements/consolidation-route-commands";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const paramsSchema = z.object({
  batchId: z.coerce.number().int().positive(),
});
const deleteSchema = z.object({
  expectedRevision: z.number().int().positive(),
  note: z.string().trim().min(1).max(2000),
});

export const DELETE = createCommandRoute({
  paramsSchema,
  bodySchema: deleteSchema,
  paramsError: "合并批次 ID 无效",
  bodyError: "合并批次删除参数无效",
  buildCommand: ({ params, body, user }) => buildDeleteConsolidationBatchRouteCommand(
    params.batchId,
    body,
    user.userId,
  ),
  action: executeDeleteConsolidationBatchRouteCommand,
});
