// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildHrDepartmentSubmissionActionRouteCommand,
  executeCommentHrDepartmentSubmissionRouteCommand,
} from "@workspace/hr/server";
import { routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const actionBodySchema = z.object({
  comment: z.string().nullable().optional(),
  version: z.coerce.number().nullable().optional(),
});

export const POST = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "流程单 ID 无效",
  bodySchema: actionBodySchema,
  bodyError: "评论参数无效",
  buildCommand: ({ params, body, user }) => buildHrDepartmentSubmissionActionRouteCommand({
    userId: user.userId,
    requestId: params.id,
    body,
  }),
  action: executeCommentHrDepartmentSubmissionRouteCommand,
});
