// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { listConsolidationEntrySourceOptions } from "@workspace/finance/server/statements/consolidation-entry-sources";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const paramsSchema = z.object({ batchId: z.coerce.number().int().positive() });
const querySchema = z.object({
  entitySnapshotId: z.coerce.number().int().positive(),
  sourceKind: z.enum(["auxiliaryBalance", "openItem", "cashFlowAllocation", "workpaper", "voucher"]),
  reportType: z.enum(["balanceSheet", "incomeStatement", "cashFlow"]),
  lineCode: z.string().trim().min(1).max(200),
  periodBasis: z.enum(["current", "comparative"]).catch("current"),
  keyword: z.string().trim().max(200).catch(""),
  fkKey: z.literal("finance.statements.consolidation.entrySource").optional(),
});

export const GET = createCommandRoute({
  paramsSchema,
  querySchema,
  paramsError: "合并批次 ID 无效",
  queryError: "抵销来源查询参数无效",
  buildCommand: ({ params, query, user }) => okCommand({ ...query, batchId: params.batchId, userId: user.userId }),
  action: listConsolidationEntrySourceOptions,
});
