// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";
import { z } from "zod";

import { jsonErrorResponse } from "@workspace/platform/server/api";
import { createInternalApiRoute } from "@workspace/platform/server/api-route";
import { isWorkspaceInternalRequestAuthorized } from "@workspace/platform/server/internal-unit-rpc";
import { getAccessibleProjectWorkspaceEntry } from "@workspace/work/server/access";

const bodySchema = z.object({
  userId: z.number().int().positive(),
  targetType: z.literal("project"),
  targetId: z.number().int().positive(),
});

export const POST = createInternalApiRoute({
  authorize: async ({ request }) => isWorkspaceInternalRequestAuthorized(
    request,
    await request.clone().text(),
    { allowedCallerUnitIds: ["finance"], audienceUnitId: "work" },
  ),
  authorizeError: "Internal service authentication failed",
  handler: async ({ request }) => {
    const body = bodySchema.safeParse(await request.json().catch(() => null));
    if (!body.success) return jsonErrorResponse("Invalid business space access request", 400);
    const access = await getAccessibleProjectWorkspaceEntry({
      userId: body.data.userId,
      projectId: body.data.targetId,
    });
    return NextResponse.json({ actionProfile: access.ok ? "read" : null });
  },
});
