// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildContractAttachmentTargetRouteCommand,
  downloadContractAttachment,
} from "@workspace/administration/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const paramsSchema = z.object({
  id: z.coerce.number().int().positive(),
  attachmentUid: z.string().uuid(),
});

const querySchema = z.object({
  variant: z.enum(["original", "optimized"]).catch("optimized"),
});

export const GET = createCommandRoute({
  paramsSchema,
  paramsError: "附件标识无效",
  querySchema,
  buildCommand: ({ params, query, user }) => {
    const target = buildContractAttachmentTargetRouteCommand(params.id, params.attachmentUid, user.userId);
    return target.ok ? { ...target, data: { ...target.data, variant: query.variant } } : target;
  },
  action: downloadContractAttachment,
});
