// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { handleWecomNotificationClaimRequest } from "@workspace/platform/server/notification-delivery-worker-api";

export const runtime = "nodejs";

export const POST = handleWecomNotificationClaimRequest;
