// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { readRequestExpectedVersion, routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { failCommand, okCommand } from "@workspace/platform/server/domain-validation";
import {
  ContractRevisionCreateSchema,
  executeCreateContractRevision,
} from "@workspace/administration/server";

export const POST = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  bodySchema: ContractRevisionCreateSchema,
  paramsError: "无效ID",
  buildCommand: ({ params, body, request, user }) => {
    const idempotencyKey = request.headers.get("idempotency-key")?.trim();
    return idempotencyKey ? okCommand({
      contractId: params.id,
      body,
      userId: user.userId,
      expectedVersion: readRequestExpectedVersion(request),
      idempotencyKey,
    }) : failCommand("缺少 Idempotency-Key 请求头");
  },
  action: executeCreateContractRevision,
});
