// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createHrWorkspaceAnalysisSourceRoute } from "@workspace/hr/server/analysis";

export const POST = createHrWorkspaceAnalysisSourceRoute();
