// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildHrRouteCommand,
  listPositionReportOverrides,
  savePositionReportOverrides,
  organizationStructureLifecycleMetaFromRequest,
} from "@workspace/hr/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";const nullablePositiveInt = z.preprocess(
  (value) => value === "" || value === undefined ? null : value,
  z.coerce.number().int().positive().nullable(),
);

const nullableHeadcount = z.preprocess(
  (value) => value === "" || value === undefined ? null : value,
  z.coerce.number().int().min(0).nullable(),
);

const reportOverridesQuerySchema = z.object({
  positionId: z.coerce.number().int().positive(),
}).passthrough();

const reportOverrideRowSchema = z.object({
  id: z.coerce.number().int().positive().optional().nullable(),
  version: z.coerce.number().int().min(0).optional().nullable(),
  companyId: z.coerce.number().int().positive(),
  departmentId: z.coerce.number().int().positive(),
  reportToPositionId: nullablePositiveInt.optional(),
  headcount: nullableHeadcount.optional(),
  isActive: z.boolean().optional().nullable(),
});

const reportOverrideBodySchema = z.object({
  positionId: z.coerce.number().int().positive(),
  overrides: z.array(reportOverrideRowSchema),
  lifecycle: z.object({
    kind: z.enum(["schedule", "correct", "end-date", "cancel-future"]).optional(),
    effectiveOn: z.string().optional(),
    reason: z.string().optional().nullable(),
    targetVersionId: z.coerce.number().int().positive().optional().nullable(),
  }).optional(),
});

export const GET = createCommandRoute({
  querySchema: reportOverridesQuerySchema,
  queryError: "岗位ID无效",
  buildCommand: ({ query }) => buildHrRouteCommand({ positionId: query.positionId }),
  action: ({ positionId }) => listPositionReportOverrides(positionId),
});

export const PUT = createCommandRoute({
  bodySchema: reportOverrideBodySchema,
  bodyError: "特殊汇报配置无效",
  buildCommand: ({ request, body, user }) => buildHrRouteCommand({
    ...body,
    lifecycle: organizationStructureLifecycleMetaFromRequest(request, { ...body.lifecycle, expectedSequence: 0 }),
    userId: user.userId,
  }),
  action: ({ positionId, overrides, lifecycle, userId }) =>
    savePositionReportOverrides({ positionId, overrides, lifecycle }, userId),
});
