// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createCommandRoute } from "@workspace/platform/server/api-route";
import {
  buildDeleteFinanceAssetCategoryPolicyRouteCommand,
  buildUpdateFinanceAssetCategoryPolicyRouteCommand,
  executeDeleteFinanceAssetCategoryPolicyRouteCommand,
  executeUpdateFinanceAssetCategoryPolicyRouteCommand,
} from "@workspace/finance/server/assets/route-commands";
import { deleteFinanceAssetCategoryPolicySchema, updateFinanceAssetCategoryPolicySchema } from "@workspace/finance/server/assets/schemas";

export const PUT = createCommandRoute({
  bodySchema: updateFinanceAssetCategoryPolicySchema,
  bodyError: "资产核算政策参数无效",
  buildCommand: ({ body, user }) => buildUpdateFinanceAssetCategoryPolicyRouteCommand(body, user.userId),
  action: executeUpdateFinanceAssetCategoryPolicyRouteCommand,
});

export const DELETE = createCommandRoute({
  bodySchema: deleteFinanceAssetCategoryPolicySchema,
  bodyError: "公司资产核算政策参数无效",
  buildCommand: ({ body, user }) => buildDeleteFinanceAssetCategoryPolicyRouteCommand(body, user.userId),
  action: executeDeleteFinanceAssetCategoryPolicyRouteCommand,
});
