// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildDeleteConsolidationTaxEffectRouteCommand,
  executeDeleteConsolidationTaxEffectRouteCommand,
} from "@workspace/finance/server/statements/consolidation-route-commands";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const paramsSchema = z.object({
  batchId: z.coerce.number().int().positive(),
  entryId: z.coerce.number().int().positive(),
  taxEffectId: z.coerce.number().int().positive(),
});
const deleteSchema = z.object({
  expectedRevision: z.number().int().positive(),
  note: z.string().trim().min(1).max(2000),
});

export const DELETE = createCommandRoute({
  paramsSchema,
  bodySchema: deleteSchema,
  paramsError: "合并批次、抵销分录或税务影响 ID 无效",
  bodyError: "税务影响删除参数无效",
  buildCommand: ({ params, body, user }) => buildDeleteConsolidationTaxEffectRouteCommand(
    params.batchId,
    params.entryId,
    params.taxEffectId,
    body,
    user.userId,
  ),
  action: executeDeleteConsolidationTaxEffectRouteCommand,
});
