// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { queryCompanyPaperDocument } from "@workspace/docs/server/company-documents";
import { createApiRouteHandler } from "@workspace/platform/server/api-route";

const paramsSchema = z.object({ key: z.string().regex(/^[a-z][a-z0-9-]*$/) });
const querySchema = z.object({
  section: z.string().trim().min(1).max(120).optional(),
  q: z.string().trim().min(1).max(200).optional(),
  offset: z.coerce.number().int().min(0).default(0),
  limit: z.coerce.number().int().min(1).max(50).default(20),
}).strict().refine((value) => !(value.section && value.q), "section and q cannot be used together");

export const GET = createApiRouteHandler({
  paramsSchema,
  querySchema,
  paramsError: "Invalid company document key",
  queryError: "Invalid company document query",
  handler: async ({ params, query }) => {
    const result = await queryCompanyPaperDocument(params.key, query);
    return Response.json(result.body, {
      status: result.status,
      headers: { "Cache-Control": "private, no-store" },
    });
  },
});
