import type { PageStylePreviewSamples } from "@workspace/core/ui";

export const pageStylePreviewSamples: PageStylePreviewSamples = {
  previewRows: [
    { id: "1", code: "A001", name: "月度主数据", owner: "张明", type: "标准", scope: "内部", status: "现用", updated: "06-18" },
    { id: "2", code: "A018", name: "季度核对", owner: "李青", type: "复核", scope: "公开", status: "待确认", updated: "06-12" },
    { id: "3", code: "A092", name: "归档样本", owner: "王岚", type: "历史", scope: "内部", status: "归档", updated: "05-30" },
  ],
  optionValues: [
    { value: "全部", label: "全部" },
    { value: "现用", label: "现用" },
    { value: "归档", label: "归档" },
    { value: "内部", label: "内部" },
    { value: "公开", label: "公开" },
    { value: "博士", label: "博士" },
    { value: "硕士", label: "硕士" },
    { value: "本科", label: "本科" },
    { value: "男", label: "男" },
    { value: "女", label: "女" },
    { value: "是", label: "是" },
    { value: "否", label: "否" },
  ],
  referenceValues: [
    { value: "轮执委员会", label: "轮执委员会", searchText: "lun zhi wei yuan hui" },
    { value: "董事长", label: "董事长", searchText: "dong shi zhang" },
    { value: "张明", label: "张明", searchText: "zhang ming" },
    { value: "张慧君", label: "张慧君", searchText: "zhang hui jun" },
    { value: "月度主数据", label: "月度主数据", searchText: "yue du zhu shu ju" },
  ],
  fieldValues: {
    姓名: "张慧君",
    部门: "轮执委员会",
    岗位: "董事长",
    职称: "高级经济师",
    电话: "137 7004 3888",
    毕业院校: "VU管理学院",
    政治面貌: "党员",
    民族: "汉族",
    籍贯: "盐城",
    学历: "博士",
    负责人: "张明",
    直接上级: "张明",
    名称: "月度主数据",
  },
  documentItems: ["01 公司基本情况", "02 生产资料", "03 财务资料", "04 合同资料"],
  qcPaper: {
    title: "一、阿奇霉素胶囊中间体",
    rows: [
      ["检品名称", "阿奇霉素胶囊(中间体)", "包装情况", "桶、塑料袋"],
      ["检验目的", "水分、含量", "检品数量", "12"],
      ["请验部门", "固体制剂车间", "请验日期", "2026 年 06 月 20 日"],
      ["检验日期", "2026 年 06 月 20 日", "报告日期", "2026 年 06 月 20 日"],
    ],
    templateRows: [
      ["检品名称", "阿奇霉素胶囊(中间体)", "包装情况", "桶、塑料袋"],
      ["检验目的", "水分、含量", "检品数量", "i"],
      ["请验部门", "固体制剂车间", "请验日期", "date"],
      ["检验日期", "date", "报告日期", "date"],
    ],
    basis: "《阿奇霉素胶囊中间体质量标准》（MQS074026）、《阿奇霉素胶囊中间体检验标准操作规程》（SOP073426）",
    sectionLabel: "1.1 文件",
    stageTabs: ["检验前确认", "2.1 性状", "2.2 水分", "2.3 含量"],
    products: [
      { name: "阿奇霉素胶囊", count: "11" },
      { name: "阿替洛尔片", count: "14" },
      { name: "别嘌醇片", count: "14" },
      { name: "复方芦丁片", count: "13" },
      { name: "甲硫咪唑片", count: "13" },
    ],
  },
};
