# TYPE      DATABASE               USER                         ADDRESS          METHOD
local       all                    workspace_dev                                 peer map=workspace_dev_admin
local       all                    all                                           reject

hostnossl   all                    all                          172.29.31.0/24   reject
hostssl     workspace_dev          workspace_dev_runtime        172.29.31.0/24   scram-sha-256
hostssl     workspace_dev          workspace_dev_migrator       172.29.31.0/24   scram-sha-256
hostssl     workspace_dev_shadow   workspace_dev_migrator       172.29.31.0/24   scram-sha-256
hostssl     workspace_dev          workspace_dev_backup         172.29.31.0/24   scram-sha-256
hostssl     workspace_dev          workspace_dev_monitor        172.29.31.0/24   scram-sha-256

host        all                    all                          0.0.0.0/0        reject
host        all                    all                          ::0/0            reject
