// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { requireRouteAccess } from "@workspace/platform/server/auth";
import { SettingsUiPage as PlatformSettingsUiPage } from "@workspace/settings/ui/settings";

export default async function SettingsUiRoutePage() {
  const user = await requireRouteAccess("/settings/ui");
  return PlatformSettingsUiPage({ user });
}
