// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildCreateWorkItemRouteCommand,
  buildListWorkItemsRouteCommand,
  executeCreateWorkItemRouteCommand,
  executeListWorkItemsRouteCommand,
} from "@workspace/work/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const optionalNumber = z.preprocess(
  (value) => (value === null || value === undefined || value === "" ? undefined : Number(value)),
  z.number().optional(),
);

const optionalBoolean = z.preprocess(
  (value) => value === true || value === "true",
  z.boolean().optional(),
);

const workItemsQuerySchema = z.object({
  category: z.string().optional(),
  planId: optionalNumber.nullable().optional(),
  periodType: z.string().nullable().optional(),
  periodStart: z.string().nullable().optional(),
  includeArchived: optionalBoolean,
  targetType: z.string().optional(),
  targetId: optionalNumber,
  deptId: optionalNumber,
});

const createWorkItemSchema = z.object({
  planId: z.coerce.number().optional(),
  category: z.string().min(1).optional(),
  itemType: z.string().optional(),
  content: z.string().min(1),
  description: z.string().optional(),
  importance: z.coerce.number().optional(),
  urgency: z.coerce.number().optional(),
  status: z.enum(["active", "paused", "done"]).nullable().optional(),
  krStartValue: z.coerce.number().nullable().optional(),
  krTargetValue: z.coerce.number().nullable().optional(),
  krCurrentValue: z.coerce.number().nullable().optional(),
  krUnit: z.string().nullable().optional(),
  routineTaskType: z.string().nullable().optional(),
  routineRecurrenceType: z.string().nullable().optional(),
  routineRecurrenceTime: z.string().nullable().optional(),
  routineRecurrenceWeekday: z.coerce.number().nullable().optional(),
  routineRecurrenceMonthDay: z.coerce.number().nullable().optional(),
  routineRecurrenceQuarterDay: z.coerce.number().nullable().optional(),
  routineRecurrenceYearMonth: z.coerce.number().nullable().optional(),
  routineRecurrenceYearDay: z.coerce.number().nullable().optional(),
  ownerEmployeeId: z.coerce.number().nullable().optional(),
  collaborationId: z.coerce.number().nullable().optional(),
  actualStartDate: z.string().nullable().optional(),
  actualEndDate: z.string().nullable().optional(),
  plannedStartDate: z.string().nullable().optional(),
  plannedEndDate: z.string().nullable().optional(),
  isMilestone: z.boolean().optional(),
  milestoneDate: z.string().nullable().optional(),
  periodType: z.string().nullable().optional(),
  periodStart: z.string().nullable().optional(),
  periodEnd: z.string().nullable().optional(),
  sourceType: z.string().optional(),
  sourceKind: z.string().nullable().optional(),
  sourceMeetingId: z.coerce.number().nullable().optional(),
  sourceMeetingDecisionId: z.coerce.number().nullable().optional(),
  sourceMeetingActionCandidateId: z.coerce.number().nullable().optional(),
  sourceDepartmentId: z.coerce.number().nullable().optional(),
  linkedProjectId: z.coerce.number().nullable().optional(),
  linkedProjectPhaseId: z.coerce.number().nullable().optional(),
  parentWorkItemId: z.coerce.number().nullable().optional(),
  parentPeriodWorkItemId: z.coerce.number().nullable().optional(),
  previousPeriodWorkItemId: z.coerce.number().nullable().optional(),
  responsibilityNodeId: z.coerce.number().nullable().optional(),
  responsibilityPositionId: z.coerce.number().nullable().optional(),
  evidenceTaskIds: z.array(z.coerce.number()).optional(),
  participants: z.string().optional(),
  sortOrder: z.coerce.number().optional(),
  targetType: z.string().optional(),
  targetId: z.coerce.number().optional(),
  deptId: z.coerce.number().optional(),
}).passthrough();

export const GET = createCommandRoute({
  querySchema: workItemsQuerySchema,
  buildCommand: ({ query, user }) => buildListWorkItemsRouteCommand({
    user,
    query,
  }),
  action: executeListWorkItemsRouteCommand,
});

export const POST = createCommandRoute({
  bodySchema: createWorkItemSchema,
  bodyError: "节点内容不能为空",
  buildCommand: ({ body, user }) => buildCreateWorkItemRouteCommand({
    user,
    body,
  }),
  action: executeCreateWorkItemRouteCommand,
});
