// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  WORKFLOW_FLOW_TYPES,
  WORKFLOW_HANDLER_SOURCES,
  WORKFLOW_POLICY_MODES,
  WORKFLOW_SEPARATION_POLICIES,
} from "@workspace/platform/server/workflows";

const workflowNodeConditionSchema = z.object({
  fieldKind: z.enum(["company", "department"]),
  value: z.string().nullable(),
}).strict();

const workflowNodeAssigneeSchema = z.object({
  fieldKind: z.enum(["relationship", "position", "employee"]),
  value: z.string().nullable(),
}).strict();

type WorkflowPolicyNodeInput = {
  key: string;
  kind: "approval" | "gateway";
  assignees?: Array<z.infer<typeof workflowNodeAssigneeSchema>>;
  approvalMode?: "any_one" | "all";
  gatewayKind?: "exclusive" | "inclusive" | "parallel";
  branches?: WorkflowPolicyGatewayBranchInput[];
};

type WorkflowPolicyGatewayBranchInput = {
  key: string;
  label?: string;
  order?: number;
  conditions?: Array<z.infer<typeof workflowNodeConditionSchema>>;
  assignees?: Array<z.infer<typeof workflowNodeAssigneeSchema>>;
  approvalMode?: "any_one" | "all";
  children?: WorkflowPolicyNodeInput[];
};

const workflowPolicyNodeSchema: z.ZodType<WorkflowPolicyNodeInput> = z.lazy(() => z.discriminatedUnion("kind", [
  z.object({
    key: z.string().trim().min(1),
    kind: z.literal("approval"),
    assignees: z.array(workflowNodeAssigneeSchema).default([]),
    approvalMode: z.enum(["any_one", "all"]).default("any_one"),
  }).strict(),
  z.object({
    key: z.string().trim().min(1),
    kind: z.literal("gateway"),
    gatewayKind: z.enum(["exclusive", "inclusive", "parallel"]).default("exclusive"),
    branches: z.array(workflowPolicyGatewayBranchSchema).min(1).max(3),
  }).strict(),
]));

const workflowPolicyGatewayBranchSchema: z.ZodType<WorkflowPolicyGatewayBranchInput> = z.lazy(() => z.object({
  key: z.string().trim().min(1),
  label: z.string().trim().optional(),
  order: z.coerce.number().int().positive().optional(),
  conditions: z.array(workflowNodeConditionSchema).default([]),
  assignees: z.array(workflowNodeAssigneeSchema).default([]),
  approvalMode: z.enum(["any_one", "all"]).default("any_one"),
  children: z.array(workflowPolicyNodeSchema).default([]),
}).strict());

export const workflowPolicyUpsertSchema = z.object({
  businessActionKey: z.string().trim().min(1),
  mode: z.enum(WORKFLOW_POLICY_MODES),
  flowType: z.enum(WORKFLOW_FLOW_TYPES),
  separationPolicy: z.enum(WORKFLOW_SEPARATION_POLICIES),
  handlerSource: z.enum(WORKFLOW_HANDLER_SOURCES).optional().default("permission"),
  handlerCanRevise: z.boolean().optional().default(true),
  requestCanWithdraw: z.boolean().optional().default(true),
  requestCanResubmit: z.boolean().optional().default(true),
  requestCanCancel: z.boolean().optional().default(true),
  requestCanRevise: z.boolean().optional().default(true),
  workflowNodes: z.array(workflowPolicyNodeSchema).optional().default([]),
}).strict();

export const workflowPolicyDeleteSchema = z.object({
  id: z.coerce.number().int().positive().optional(),
  businessActionKey: z.string().trim().min(1).optional(),
}).strict().refine((value) => value.id || value.businessActionKey, {
  message: "需要提供 id 或业务行为",
});
