// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { listFinanceGroupAccountOptions } from "@workspace/finance/server/ledger/group-accounts";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

export const GET = createCommandRoute({
  querySchema: z.object({
    fkKey: z.literal("finance.groupAccount.parent"),
    keyword: z.string().trim().max(100).default(""),
    lifecycleScope: z.string().optional(),
    category: z.enum(["asset", "liability", "common", "equity", "cost", "revenue", "expense"]),
  }),
  queryError: "集团科目选项参数无效",
  buildCommand: ({ query }) => okCommand({ keyword: query.keyword, category: query.category }),
  action: listFinanceGroupAccountOptions,
});
