import fs from "node:fs";
import path from "node:path";

import { resolveDeployGraph, type DeployGraph, type ResolvedDeployUnit } from "./deploy-graph";
import { createDeployUnitNavigationManifest } from "./deploy-navigation-manifest";

const GENERATED_BANNER = "// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.\n";
const ROUTE_ENTRY_PATTERN = /\/(page|route|layout|loading|error)\.(?:ts|tsx)$/;
const LIBRARY_RUNTIME_SOURCE_TRACE_EXCLUDES = [
  "app/**/*",
  "apps/**/*",
  "docs/**/*",
  "e2e/**/*",
  "generated/**/*",
  "outputs/**/*",
  "packages/**/*",
  "prisma/**/*",
  "scripts/**/*",
  "test-results/**/*",
  "tmp/**/*",
  "*.{cjs,json,md,mjs,ts,tsbuildinfo}",
];

interface GeneratedFile {
  path: string;
  content: string;
}

function walk(directory: string): string[] {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = path.join(directory, entry.name);
    return entry.isDirectory() ? walk(absolutePath) : [absolutePath];
  });
}

function routePathFromSource(repositoryRoot: string, sourceFile: string) {
  const relative = path.relative(path.join(repositoryRoot, "app"), sourceFile).replaceAll(path.sep, "/");
  const segments = relative.split("/");
  segments.pop();
  const publicSegments = segments.filter((segment) => !(segment.startsWith("(") && segment.endsWith(")")));
  return publicSegments.length === 0 ? "/" : `/${publicSegments.join("/")}`;
}

function pathMatchesPrefix(routePath: string, prefix: string) {
  if (prefix === "/") return routePath === "/";
  return routePath === prefix || routePath.startsWith(`${prefix}/`);
}

function ownedRouteEntries(repositoryRoot: string, unit: ResolvedDeployUnit) {
  const appRoot = path.join(repositoryRoot, "app");
  const applicationSources = walk(appRoot).filter((file) => (
    /\.(?:ts|tsx)$/.test(file) && !/\.test\.(?:ts|tsx)$/.test(file)
  ));
  const routeEntries = applicationSources.filter((file) => ROUTE_ENTRY_PATTERN.test(file.replaceAll(path.sep, "/")));
  const selected = new Set<string>();
  const selectedPageDirectories = new Set<string>();

  for (const sourceFile of routeEntries) {
    const normalized = sourceFile.replaceAll(path.sep, "/");
    const routePath = routePathFromSource(repositoryRoot, sourceFile);
    if (normalized.endsWith("/page.tsx") || normalized.endsWith("/page.ts")) {
      if (unit.pageRoutes.some((prefix) => pathMatchesPrefix(routePath, prefix))) {
        selected.add(sourceFile);
        selectedPageDirectories.add(path.dirname(sourceFile));
      }
      continue;
    }
    if (normalized.endsWith("/route.tsx") || normalized.endsWith("/route.ts")) {
      if (unit.apiPrefixes.some((prefix) => pathMatchesPrefix(routePath, prefix))) selected.add(sourceFile);
    }
  }

  for (const sourceFile of routeEntries) {
    const basename = path.basename(sourceFile);
    if (basename !== "layout.tsx" && basename !== "layout.ts" && basename !== "loading.tsx" && basename !== "loading.ts") continue;
    const sourceDirectory = path.dirname(sourceFile);
    if (sourceDirectory === appRoot) continue;
    if ([...selectedPageDirectories].some((pageDirectory) => (
      pageDirectory === sourceDirectory || pageDirectory.startsWith(`${sourceDirectory}${path.sep}`)
    ))) selected.add(sourceFile);
  }

  const selectedDirectories = [...selected]
    .map((file) => path.dirname(file))
    .filter((directory) => directory !== appRoot);
  for (const sourceFile of applicationSources) {
    const sourceDirectory = path.dirname(sourceFile);
    if (selectedDirectories.some((directory) => sourceDirectory === directory || sourceDirectory.startsWith(`${directory}${path.sep}`))) {
      selected.add(sourceFile);
    }
  }
  for (const sharedFile of ["app/layout.tsx", "app/error.tsx"]) {
    const absolutePath = path.join(repositoryRoot, sharedFile);
    if (fs.existsSync(absolutePath)) selected.add(absolutePath);
  }
  return [...selected].sort();
}

function wrapperContent(repositoryRoot: string, sourceFile: string) {
  void repositoryRoot;
  return `${GENERATED_BANNER}${fs.readFileSync(sourceFile, "utf8")}`;
}

function instrumentationContent(unitId: string) {
  if (unitId !== "work") {
    return `${GENERATED_BANNER}import { registerDeployUnitRuntime } from "@workspace/platform/server/deploy-unit-runtime";\n\nexport function register() {\n  return registerDeployUnitRuntime(${JSON.stringify(unitId)});\n}\n`;
  }
  return `${GENERATED_BANNER}import { registerDeployUnitRuntime } from "@workspace/platform/server/deploy-unit-runtime";\n\nexport async function register() {\n  await registerDeployUnitRuntime("work");\n  if (process.env.NEXT_RUNTIME !== "nodejs") return;\n  if (process.env.NEXT_PHASE === "phase-production-build") return;\n  const { startProjectNotificationScheduler } = await import(\n    "@workspace/work/server/project-notification-scheduler"\n  );\n  startProjectNotificationScheduler();\n}\n`;
}

function relativeReference(appRoot: string, compilerProject: string) {
  const withoutConfig = compilerProject.replace(/\/tsconfig\.json$/, "");
  let relative = path.relative(appRoot, withoutConfig).replaceAll(path.sep, "/");
  if (!relative.startsWith(".")) relative = `./${relative}`;
  return relative;
}

function nextConfigContent(unit: ResolvedDeployUnit, graph: DeployGraph) {
  const embeddedNavigationManifest = JSON.stringify(JSON.stringify(createDeployUnitNavigationManifest(graph)));
  const embeddedAssetPrefix = unit.runtime.assetPrefix === null ? "undefined" : JSON.stringify(unit.runtime.assetPrefix);
  const outputFileTracingExcludes = unit.id === "library"
    ? `\n  // Library runtime data lives outside the checkout; keep dynamic fs traces from copying repository sources.\n  outputFileTracingExcludes: {\n    "/*": ${JSON.stringify(LIBRARY_RUNTIME_SOURCE_TRACE_EXCLUDES)},\n  },`
    : "";
  return `${GENERATED_BANNER}import { execFileSync } from "node:child_process";
import path from "node:path";
import type { NextConfig } from "next";

import { resolveDeployUnitTurbopackRoot } from "../../scripts/deploy/deploy-unit-turbopack-root.cjs";

const repositoryRoot = path.resolve(import.meta.dirname, "../..");
const turbopackRoot = resolveDeployUnitTurbopackRoot(repositoryRoot);
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "/workspace";

function localBuildVersion() {
  try {
    const commitSha = execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: repositoryRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (/^[0-9a-f]{40}$/.test(commitSha)) return \`local-\${commitSha}\`;
  } catch {
    // Source archives may not include Git metadata.
  }
  return "local-development";
}

const buildVersion = process.env.NEXT_PUBLIC_BUILD_VERSION
  || process.env.BUILD_VERSION
  || process.env.CNB_COMMIT_SHA
  || process.env.GITHUB_SHA
  || localBuildVersion();
const deploymentId = process.env.NEXT_DEPLOYMENT_ID || buildVersion;
const navigationManifest = process.env.NEXT_PUBLIC_DEPLOY_UNIT_NAVIGATION || ${embeddedNavigationManifest};
const assetPrefix = process.env.NEXT_PUBLIC_ASSET_PREFIX || ${embeddedAssetPrefix};

const nextConfig: NextConfig = {
  output: "standalone",
  // The artifact builder runs every graph-derived package and app scope through
  // the governed project lock before Next starts. Repeating Next's partial
  // project-reference type pass adds no coverage and can exceed its worker heap.
  typescript: { tsconfigPath: "tsconfig.json", ignoreBuildErrors: true },
  env: {
    NEXT_PUBLIC_BUILD_VERSION: buildVersion,
    NEXT_PUBLIC_DEPLOY_UNIT_ID: ${JSON.stringify(unit.id)},
    NEXT_PUBLIC_DEPLOY_UNIT_NAVIGATION: navigationManifest,
  },
  deploymentId,
  images: { unoptimized: true },
  experimental: { turbopackFileSystemCacheForDev: false },
  serverExternalPackages: ["pinyin-pro"],
  basePath,
  assetPrefix,
  allowedDevOrigins: [
    "localhost",
    "127.0.0.1",
    ...(process.env.ALLOWED_DEV_ORIGINS
      ? process.env.ALLOWED_DEV_ORIGINS.split(",").map((value) => value.trim()).filter(Boolean)
      : []),
  ],
  outputFileTracingRoot: repositoryRoot,${outputFileTracingExcludes}
  turbopack: { root: turbopackRoot },
  generateBuildId: async () => buildVersion,
  async headers() {
    return [{
      source: "/:path*",
      headers: [
        { key: "Cache-Control", value: "no-store, no-cache, must-revalidate, proxy-revalidate" },
        { key: "Pragma", value: "no-cache" },
        { key: "Expires", value: "0" },
      ],
    }];
  },
};

export default nextConfig;
`;
}

export function generatedDeployUnitAppFiles(
  unitId: string,
  options: { graph?: DeployGraph; repositoryRoot?: string } = {},
): GeneratedFile[] {
  const repositoryRoot = options.repositoryRoot ?? path.resolve(import.meta.dirname, "../..");
  const graph = options.graph ?? resolveDeployGraph({ repositoryRoot });
  const unit = graph.units.find((candidate) => candidate.id === unitId);
  if (!unit) throw new Error(`Unknown deploy unit: ${unitId}`);
  if (unit.runtime.engine !== "next-standalone") throw new Error(`${unitId} is not a Next deploy unit`);
  const appRoot = path.join(repositoryRoot, unit.runtime.appRoot);
  const appDirectory = path.join(appRoot, "app");
  const contributorCompilerProjects = graph.contributorEdges
    .filter((edge) => edge.sourceUnitId === unit.id)
    .flatMap((edge) => graph.units.find((candidate) => candidate.id === edge.targetUnitId)?.compilerProjects ?? []);
  const compilerProjects = [...new Set([...unit.compilerProjects, ...contributorCompilerProjects])].sort();
  const files: GeneratedFile[] = ownedRouteEntries(repositoryRoot, unit).map((sourceFile) => ({
    path: path.join(appDirectory, path.relative(path.join(repositoryRoot, "app"), sourceFile)),
    content: wrapperContent(repositoryRoot, sourceFile),
  }));

  files.push({
    path: path.join(appRoot, "next.config.ts"),
    content: nextConfigContent(unit, graph),
  });
  files.push({
    path: path.join(appRoot, "next-env.d.ts"),
    content: `/// <reference types="next" />\n/// <reference types="next/image-types/global" />\nimport "./.next/types/routes.d.ts";\n\n// NOTE: This file should not be edited\n// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.\n`,
  });
  files.push({
    path: path.join(appRoot, "instrumentation.ts"),
    content: instrumentationContent(unit.id),
  });
  files.push({
    path: path.join(appRoot, "tsconfig.json"),
    content: `${JSON.stringify({
      extends: "../../tsconfig.base.json",
      compilerOptions: {
        composite: true,
        disableSourceOfProjectReferenceRedirect: true,
        incremental: true,
        noEmit: true,
        tsBuildInfoFile: `../../.cache/tsbuild/apps/${unit.id}.tsbuildinfo`,
        plugins: [{ name: "next" }],
      },
      include: [
        "next-env.d.ts",
        "instrumentation.ts",
        "app/**/*.ts",
        "app/**/*.tsx",
        ".next/types/**/*.ts",
        ".next/dev/types/**/*.ts",
      ],
      exclude: ["node_modules"],
      references: compilerProjects.map((project) => ({ path: relativeReference(appRoot, project) })),
    }, null, 2)}\n`,
  });
  files.push({
    path: path.join(appDirectory, "api/internal/health/route.ts"),
    content: `${GENERATED_BANNER}import { deployUnitHealthResponse } from "@workspace/platform/server/deploy-unit-runtime";\n\nexport function GET() {\n  return deployUnitHealthResponse();\n}\n`,
  });
  files.push({
    path: path.join(appDirectory, "globals.css"),
    content: `/* Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit. */\n${fs.readFileSync(path.join(repositoryRoot, "app/globals.css"), "utf8")}`,
  });
  files.push({
    path: path.join(appDirectory, "api/settings/version/route.ts"),
    content: `${GENERATED_BANNER}import { deployUnitVersionResponse } from "@workspace/platform/server/deploy-unit-runtime";\n\nexport function GET() {\n  return deployUnitVersionResponse();\n}\n`,
  });
  return [...new Map(files.map((file) => [file.path, file])).values()]
    .sort((left, right) => left.path.localeCompare(right.path));
}

function assertOwnedOrMissing(file: GeneratedFile) {
  if (!fs.existsSync(file.path)) return;
  const source = fs.readFileSync(file.path, "utf8");
  if (path.basename(file.path) === "tsconfig.json") {
    try {
      const parsed = JSON.parse(source) as { extends?: unknown; include?: unknown };
      if (parsed.extends === "../../tsconfig.base.json" && Array.isArray(parsed.include)) return;
    } catch {
      // The normal generated-marker check below rejects malformed files.
    }
  }
  if (!source.startsWith(GENERATED_BANNER) && source !== file.content) {
    throw new Error(`Refusing to overwrite non-generated deploy app file: ${file.path}`);
  }
}

export function writeDeployUnitApp(unitId: string) {
  const files = generatedDeployUnitAppFiles(unitId);
  const expectedPaths = new Set(files.map((file) => file.path));
  const repositoryRoot = path.resolve(import.meta.dirname, "../..");
  const generatedRoot = path.join(repositoryRoot, "apps", unitId);
  const generatedAppRoot = path.join(repositoryRoot, "apps", unitId, "app");
  // Next's route validator is derived from the selected app tree. Keeping an
  // older validator after route ownership moves makes an otherwise current
  // generated app fail on paths it no longer owns.
  fs.rmSync(path.join(generatedRoot, ".next", "types"), { recursive: true, force: true });
  fs.rmSync(path.join(generatedRoot, ".next", "dev", "types"), { recursive: true, force: true });
  for (const staleFile of walk(generatedAppRoot)) {
    if (expectedPaths.has(staleFile) || !/\.(?:ts|tsx)$/.test(staleFile)) continue;
    const source = fs.readFileSync(staleFile, "utf8");
    if (source.startsWith(GENERATED_BANNER)) fs.unlinkSync(staleFile);
  }
  for (const file of files) {
    assertOwnedOrMissing(file);
    fs.mkdirSync(path.dirname(file.path), { recursive: true });
    fs.writeFileSync(file.path, file.content);
  }
  return files;
}

export function assertDeployUnitApp(unitId: string) {
  const files = generatedDeployUnitAppFiles(unitId);
  const expectedPaths = new Set(files.map((file) => file.path));
  const generatedAppRoot = path.join(path.resolve(import.meta.dirname, "../.."), "apps", unitId, "app");
  const staleGeneratedFiles = walk(generatedAppRoot).filter((file) => (
    !expectedPaths.has(file)
    && /\.(?:ts|tsx)$/.test(file)
    && fs.readFileSync(file, "utf8").startsWith(GENERATED_BANNER)
  ));
  const mismatches = [
    ...files.filter((file) => !fs.existsSync(file.path) || fs.readFileSync(file.path, "utf8") !== file.content).map((file) => file.path),
    ...staleGeneratedFiles,
  ];
  if (mismatches.length > 0) {
    throw new Error(`${unitId} generated app is stale: ${mismatches.join(", ")}`);
  }
  return files;
}
