// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { domainIssueToResponse, jsonBadRequest, serviceResponse } from "@workspace/platform/server/api";
import { notificationPublicationRequestSchema } from "@workspace/platform/server/notification-definition-dsl";
import { withOpenApiScope } from "@workspace/platform/server/open-api";
import { buildNotificationPublicationCommand } from "@workspace/platform/server/notification-publishing";
import { publishConfiguredNotification } from "@workspace/platform/server/notifications";

const notificationPublicationBodySchema = notificationPublicationRequestSchema.omit({ idempotencyKey: true });

export const POST = withOpenApiScope(
  "workspace.notifications.publications.write",
  "write",
  async (request, { client }) => {
    const idempotencyKey = request.headers.get("idempotency-key")?.trim();
    if (!idempotencyKey) return jsonBadRequest("缺少 Idempotency-Key 请求头");

    const parsed = notificationPublicationBodySchema.safeParse(await request.json().catch(() => null));
    if (!parsed.success) return jsonBadRequest(parsed.error.issues[0]?.message ?? "通知发布请求无效");

    const command = await buildNotificationPublicationCommand({
      source: { kind: "open-api", id: String(client.id), label: client.name },
      request: { ...parsed.data, idempotencyKey },
    });
    if (command.ok === false) return domainIssueToResponse(command.issue);

    const result = await publishConfiguredNotification(command.data);
    if (result.ok === false) return serviceResponse(result);
    return Response.json(result.data, { status: result.data.replayed ? 200 : 201 });
  },
);
