// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { execFileSync } from "node:child_process";
import path from "node:path";
import type { NextConfig } from "next";

const repositoryRoot = path.resolve(import.meta.dirname, "../..");
const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "/workspace";

function localBuildVersion() {
  try {
    const commitSha = execFileSync("git", ["rev-parse", "HEAD"], {
      cwd: repositoryRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    if (/^[0-9a-f]{40}$/.test(commitSha)) return `local-${commitSha}`;
  } catch {
    // Source archives may not include Git metadata.
  }
  return "local-development";
}

const buildVersion = process.env.NEXT_PUBLIC_BUILD_VERSION
  || process.env.BUILD_VERSION
  || process.env.CNB_COMMIT_SHA
  || process.env.GITHUB_SHA
  || localBuildVersion();
const deploymentId = process.env.NEXT_DEPLOYMENT_ID || buildVersion;
const navigationManifest = process.env.NEXT_PUBLIC_DEPLOY_UNIT_NAVIGATION || "{\"schemaVersion\":1,\"units\":[{\"id\":\"workspace-shell\",\"pagePrefixes\":[\"/\",\"/login\",\"/module-disabled\",\"/portal\",\"/settings\",\"/settings/account\",\"/settings/admin\",\"/settings/api\",\"/settings/api/hr-generated\",\"/settings/ui\"]},{\"id\":\"finance\",\"pagePrefixes\":[\"/finance\",\"/finance/analysis\",\"/finance/budget\",\"/finance/cost\",\"/finance/cost/workspace/[targetType]/[targetId]\",\"/finance/ledger\",\"/finance/statements\"]},{\"id\":\"external\",\"pagePrefixes\":[\"/external\",\"/external/customers\",\"/external/related-parties\",\"/external/suppliers\"]},{\"id\":\"inventory\",\"pagePrefixes\":[\"/inventory\",\"/inventory/operations\",\"/inventory/receipts\"]},{\"id\":\"production\",\"pagePrefixes\":[\"/production\",\"/production/products\",\"/production/qc\",\"/production/qc/[batchId]/[stageKey]\",\"/production/qc/[batchId]/[stageKey]/[testName]\"]},{\"id\":\"hr\",\"pagePrefixes\":[\"/hr\",\"/hr/analytics\",\"/hr/performance\",\"/hr/performance/self\",\"/hr/roster\",\"/hr/roster/employees/[id]\"]},{\"id\":\"library\",\"pagePrefixes\":[\"/library\",\"/library/basic-info\",\"/library/basic-info/documents/[id]\"]},{\"id\":\"docs\",\"pagePrefixes\":[\"/docs\",\"/docs/company\",\"/docs/editor\",\"/docs/editor/templates/[templateId]\"]},{\"id\":\"capital-securities\",\"pagePrefixes\":[\"/capital-securities\",\"/capital-securities/governance\",\"/capital-securities/investors\"]},{\"id\":\"work\",\"pagePrefixes\":[\"/work\",\"/work/department\",\"/work/department/[departmentId]\",\"/work/department/[departmentId]/space\",\"/work/me\",\"/work/me/space\",\"/work/meeting\",\"/work/meetings\",\"/work/performance\",\"/work/project\",\"/work/project/[projectId]\",\"/work/project/[projectId]/space\"]},{\"id\":\"administration\",\"pagePrefixes\":[\"/administration\",\"/administration/contracts\",\"/administration/erp-diligence\"]}]}";
const assetPrefix = process.env.NEXT_PUBLIC_ASSET_PREFIX || "/workspace-static/finance";

const nextConfig: NextConfig = {
  output: "standalone",
  // The artifact builder runs every graph-derived package and app scope through
  // the governed project lock before Next starts. Repeating Next's partial
  // project-reference type pass adds no coverage and can exceed its worker heap.
  typescript: { tsconfigPath: "tsconfig.json", ignoreBuildErrors: true },
  env: {
    NEXT_PUBLIC_BUILD_VERSION: buildVersion,
    NEXT_PUBLIC_DEPLOY_UNIT_ID: "finance",
    NEXT_PUBLIC_DEPLOY_UNIT_NAVIGATION: navigationManifest,
  },
  deploymentId,
  images: { unoptimized: true },
  experimental: { turbopackFileSystemCacheForDev: false },
  serverExternalPackages: ["pinyin-pro"],
  basePath,
  assetPrefix,
  allowedDevOrigins: [
    "localhost",
    "127.0.0.1",
    ...(process.env.ALLOWED_DEV_ORIGINS
      ? process.env.ALLOWED_DEV_ORIGINS.split(",").map((value) => value.trim()).filter(Boolean)
      : []),
  ],
  outputFileTracingRoot: repositoryRoot,
  turbopack: { root: repositoryRoot },
  generateBuildId: async () => buildVersion,
  async headers() {
    return [{
      source: "/:path*",
      headers: [
        { key: "Cache-Control", value: "no-store, no-cache, must-revalidate, proxy-revalidate" },
        { key: "Pragma", value: "no-cache" },
        { key: "Expires", value: "0" },
      ],
    }];
  },
};

export default nextConfig;
