// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  EmploymentAgreementAttachmentTargetParamsSchema,
  downloadEmploymentAgreementAttachment,
} from "@workspace/hr/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const querySchema = z.object({
  variant: z.enum(["original", "optimized"]).catch("optimized"),
});

export const GET = createCommandRoute({
  paramsSchema: EmploymentAgreementAttachmentTargetParamsSchema,
  paramsError: "员工、协议或附件标识无效",
  querySchema,
  buildCommand: ({ params, query, user }) => okCommand({
    employeeId: params.id,
    agreementUid: params.agreementUid,
    attachmentUid: params.attachmentUid,
    userId: user.userId,
    variant: query.variant,
  }),
  action: downloadEmploymentAgreementAttachment,
});
