import type { CoreUiComponentRegistration } from "./component-registry-types";
import { generatedCoreUiSurfaceContracts } from "./generated-surface-contracts";

export const page_api_registry_entries = [
  {
    name: "NavigationSurface",
    category: "common",
    subcategory: "common.chrome",
    description: "页面导航 renderer / 正文导航 primitive",
    composes: ["TabBar", "Pagination", "SelectorPanel", "SelectionGrid", "DisclosureSectionHeader"],
  },
  {
    name: "Toolbar",
    category: "common",
    subcategory: "common.chrome",
    description: "PageSurface 内部统一工具栏 renderer",
    composes: ["ActionButton", "SearchInput", "SelectField", "ToolbarOptionGroup", "FieldValueFilter", "DropdownSurface"],
  },
  {
    name: "useFeedback",
    category: "feedback",
    subcategory: "feedback.service",
    description: "统一前端反馈 Hook",
    capabilities: [
      { name: "notify", description: "普通通知消息，Core 统一决定 toast 呈现。" },
      { name: "success", description: "成功反馈，不在业务里手写 Toast。" },
      { name: "error", description: "错误反馈，不在业务里手写错误弹层。" },
      { name: "confirm", description: "通用确认对话框。" },
      { name: "confirmDelete", description: "删除确认语义，Core 统一危险操作文案和样式。" },
    ],
    composes: ["FeedbackProvider", "ConfirmModal", "Toast"],
  },
  {
    name: "NumberCell",
    category: "data",
    subcategory: "data.cell",
    description: "数字单元格",
  },
  {
    name: "OptionPicker",
    category: "common",
    subcategory: "common.selection",
    description: "统一选项选择器，支持平铺枚举、常用项 + 更多搜索，以及先选分类再选值的分组模式。",
    composes: ["PickerShell", "SearchInput", "PickerOptionButton"],
  },
  {
    name: "PageContent",
    category: "page",
    subcategory: "page.frame",
    description: "页面内容容器",
  },
  {
    name: "PageSurface",
    category: "page",
    subcategory: "page.surface",
    description: "唯一页面薄壳 L1 Surface",
    contract: generatedCoreUiSurfaceContracts.PageSurface,
    declares: [
      {
        name: "kind",
        description: "页面级语义：先声明页面 chrome 类型。",
        children: [
          { name: "login", description: "登录专属页；必须在登录路由且包含 content block + login FormSurface，使用封闭居中布局。" },
          { name: "directory", description: "L1/L2 模块目录页；自动校验当前路由深度，禁止 navigation/toolbar/split，使用封闭目录布局。" },
          { name: "standard", description: "标准业务页；才可声明页面内 navigation/toolbar/body/footer。" },
        ],
      },
      {
        name: "navigation",
        description: "标准业务页内部 tab 导航；不承载 login、L1/L2、card 或 level 语义。",
        children: [
          { name: "kind", description: "固定为 tabs。" },
          { name: "items", description: "页面内 tab 项。" },
          { name: "active", description: "当前激活项。" },
        ],
      },
      {
        name: "toolbar",
        description: "页面级唯一工具区：搜索、筛选、刷新、导出、新建等都进入这里。",
        children: [
          { name: "items", description: "工具项列表，具体渲染交给 Toolbar。" },
          { name: "hidden", description: "隐藏页面工具栏。" },
        ],
      },
      {
        name: "body",
        description: "正文架构：先选择完整页或左右分栏，再创建 section 并指定每个 section 的 Surface 类型。",
        children: [
          {
            name: "kind",
            description: "正文模式：complete 表示完整正文；split 表示左侧选择区 + 右侧完整正文。",
            children: [
              { name: "complete", description: "完整正文：可声明标题、分区和 section 树。" },
              { name: "split", description: "左右分栏：left 为选择/导航区，right 复用 complete 正文配置。" },
            ],
          },
          { name: "title", description: "正文标题；页面标题不放在 FormSurface/DataSurface 内。" },
          { name: "description", description: "正文简述。" },
          { name: "sectioning", description: "正文 section 分区模式：none / tabs。" },
          {
            name: "sections",
            description: "正文 section 树；必须先声明 section，再声明它承载 form/data/document/visualization/block/navigation/modal/sections。",
            children: [
              { name: "kind", description: "section 内容类型：form / data / document / visualization / block / navigation / modal / sections。" },
              { name: "form", description: "表单 section：surface 使用 FormSurface，FormSurface 只声明字段如何构成。" },
              { name: "data", description: "数据 section：surface 使用 DataSurface。" },
              { name: "document", description: "文档 section：surface 使用 DocumentSurface。" },
              { name: "visualization", description: "图表 section：surface 使用 VisualizationSurface。" },
              { name: "block", description: "通用内容 section：surface 使用 BlockSurface。" },
              { name: "navigation", description: "导航 section：surface 使用 NavigationSurface。" },
              { name: "modal", description: "弹层 section：用于挂载页面内弹层。" },
              { name: "sections", description: "递归 section：内部继续声明 sections。" },
              { name: "framed", description: "section 是否有外框；默认有框。" },
            ],
          },
          { name: "layout", description: "正文 section 排布：single / split。" },
          { name: "empty", description: "正文为空时的空态。" },
          { name: "commands", description: "正文上方的简短命令；复杂工具归 toolbar。" },
        ],
      },
      {
        name: "footer",
        description: "页脚区域；表格/数据分页统一放在 PageSurface.footer.pagination。",
        children: [
          { name: "pagination", description: "页面底部分页声明。" },
        ],
      },
      { name: "embedded", description: "嵌入式渲染，不输出完整页面框架。" },
    ],
    composes: ["DatabasePageFrame", "WorkspaceSplitPage", "Toolbar", "BlockSurface", "NavigationSurface", "Pagination", "ModuleCard", "EmptyStateCard"],
  },
  {
    name: "PageShell",
    category: "page",
    subcategory: "page.frame",
    description: "页面顶部骨架",
  },
  {
    name: "Pagination",
    category: "common",
    subcategory: "common.chrome",
    description: "分页控件",
  },
  {
    name: "PanelCard",
    category: "common",
    subcategory: "common.block",
    description: "通用面板卡片",
  },
  {
    name: "RatingControl",
    category: "common",
    subcategory: "common.input",
    description: "星级评分",
  },
  {
    name: "SearchableOptionInput",
    category: "common",
    subcategory: "common.selection",
    description: "可搜索选项输入",
    composes: ["getFieldInputClassName"],
  },
  {
    name: "SearchInput",
    category: "common",
    subcategory: "common.input",
    description: "搜索输入框",
  },
  {
    name: "SectionCard",
    category: "common",
    subcategory: "common.block",
    description: "小节卡片",
    composes: ["PanelCard"],
  },
  {
    name: "VisualizationSurface",
    category: "visualization",
    subcategory: "visualization.surface",
    description: "L1 可视化正文 Surface",
    contract: generatedCoreUiSurfaceContracts.VisualizationSurface,
    declares: [
      {
        name: "kind",
        description: "可视化类型：chart / gantt。",
        children: [
          { name: "chart", description: "轻量图表，使用 visual 声明。" },
          { name: "gantt", description: "甘特图，使用 gantt typed spec 声明。" },
        ],
      },
      {
        name: "visual",
        description: "轻量图表声明。",
        children: [
          { name: "barChart", description: "单序列条形图。" },
          { name: "groupedBarChart", description: "分组条形图。" },
          { name: "comparisonBars", description: "实际值与参考值对比。" },
          { name: "tree", description: "树形层级可视化。" },
        ],
      },
      { name: "gantt", description: "甘特图 typed spec：rows / periodStart / zoom / dependencies / onToggle。" },
      { name: "framed", description: "是否使用通用面板外框。" },
      { name: "title", description: "可视化标题。" },
    ],
    composes: ["PanelCard", "VisualizationSurfaceChart", "VisualizationGantt", "VisualizationSurfaceTypes"],
  },
  {
    name: "VisualizationSurfaceChart",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 轻量图表 renderer。",
    composes: [],
  },
  {
    name: "VisualizationSurfaceTypes",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 轻量图与甘特图 public spec types。",
    composes: [],
  },
  {
    name: "VisualizationGantt",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 甘特图 typed spec renderer。",
    composes: ["VisualizationGanttUtils"],
  },
  {
    name: "VisualizationGanttUtils",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 甘特图时间刻度与定位算法。",
    composes: [],
  },
  {
    name: "SelectionGrid",
    category: "common",
    subcategory: "common.selection",
    description: "页面内平铺选项网格",
  },
  {
    name: "SelectField",
    category: "common",
    subcategory: "common.input",
    description: "下拉选择字段",
    composes: ["FieldInputShell", "SearchInput", "DropdownSurface", "CheckboxField"],
  },
  {
    name: "SegmentedCodeInput",
    category: "common",
    subcategory: "common.input",
    description: "分段编码输入控件",
    composes: ["TextField"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
