import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "SelectorPanel",
    category: "common",
    subcategory: "common.selection",
    description: "选择器面板内部 renderer",
    composes: ["PanelCard", "SearchInput", "SelectionGrid", "SelectorList", "SelectorTree", "EmptyStateCard"],
  },
  {
    name: "createSelectorPanelSection",
    category: "common",
    subcategory: "common.selection",
    description: "选择器区块声明助手",
    composes: ["SelectorPanel", "BlockSurface"],
  },
  {
    name: "SwitchField",
    category: "common",
    subcategory: "common.input",
    description: "开关字段",
  },
  {
    name: "TagListInput",
    category: "common",
    subcategory: "common.input",
    description: "标签列表输入",
    composes: [
      "RemovableTag",
      "TagPill",
      "getTagInputShellClassName",
      "getTagInlineInputClassName",
      "getTagPillClassName",
    ],
  },
  {
    name: "TagStringInput",
    category: "common",
    subcategory: "common.input",
    description: "字符串标签输入",
    composes: ["RemovableTag", "TagInlineTextField", "FieldShell"],
  },
  {
    name: "StructuredTable",
    category: "data",
    subcategory: "data.table",
    description: "结构化表格",
  },
  {
    name: "TabBar",
    category: "common",
    subcategory: "common.chrome",
    description: "Tab 切换栏",
    composes: ["ActionButton"],
  },
  {
    name: "TableScrollFrame",
    category: "data",
    subcategory: "data.table",
    description: "表格滚动外壳",
    composes: ["DataTable"],
  },
  {
    name: "TextareaField",
    category: "common",
    subcategory: "common.input",
    description: "多行文本输入",
  },
  {
    name: "TextField",
    category: "common",
    subcategory: "common.input",
    description: "通用文本输入",
    composes: ["FieldInputShell", "getFieldInputClassName"],
  },
  {
    name: "TimeField",
    category: "common",
    subcategory: "common.input",
    description: "时间输入框",
    composes: ["FieldInputShell", "getFieldInputClassName"],
  },
  {
    name: "Toast",
    category: "feedback",
    subcategory: "feedback.renderer",
    description: "底层提示组件（Core 内部使用）",
    composes: ["ConfirmModal"],
  },] as const satisfies readonly CoreUiComponentRegistration[];
