import type { CoreUiComponentRegistration } from "./component-registry-types";
import { generatedCoreUiSurfaceContracts } from "./generated-surface-contracts";

export const page_api_registry_entries = [
  {
    name: "ReadOnlyField",
    category: "common",
    subcategory: "common.input",
    description: "只读字段展示",
    composes: ["FieldInputShell", "getReadOnlyFieldClassName", "getFieldValueClassName"],
  },
  {
    name: "FieldInputShell",
    category: "common",
    subcategory: "common.input",
    description: "字段输入外壳",
    composes: ["FieldShell", "getFieldInputClassName"],
  },
  {
    name: "FieldShell",
    category: "common",
    subcategory: "common.input",
    description: "统一字段壳",
    composes: ["getFieldShellClassName"],
  },
  {
    name: "FieldControl",
    category: "form",
    subcategory: "form.input-adapter",
    description: "统一字段控件选择器",
    composes: ["InputControl"],
  },
  {
    name: "InputControl",
    category: "common",
    subcategory: "common.input",
    description: "字段规格输入控件",
    contract: generatedCoreUiSurfaceContracts.InputControl,
    declares: [
      { name: "control", description: "输入语义：text / number / boolean / choice / reference / temporal / file / collection / rating。" },
      { name: "valueType", description: "字段数据形状：string / number / boolean / date / time / datetime / file / reference / array。" },
      { name: "options", description: "选项来源：none / static / grouped / remote；remote 用于 FK/reference。" },
      { name: "format", description: "展示和输入格式：percent / currency / date / time / datetime。" },
      { name: "mask", description: "输入约束和模板；分段编码使用 mask.kind=editableSegment。" },
    ],
    composes: ["CalendarDateInput", "CheckboxField", "ChoiceGroup", "FileField", "FkFieldInput", "OptionPicker", "PercentField", "RatingControl", "ReadOnlyField", "SearchableOptionInput", "SegmentedCodeInput", "SelectField", "SwitchField", "TagStringInput", "TextField", "TextareaField", "TimeField"],
  },
  {
    name: "PercentField",
    category: "common",
    subcategory: "common.input",
    description: "百分比输入字段",
    composes: ["FieldInputShell", "TextField"],
  },
  {
    name: "FieldGrid",
    category: "form",
    subcategory: "form.layout",
    description: "字段网格信息表",
    composes: [
      "getFieldGridCellClassName",
      "getFieldGridMainRowClassName",
      "getFieldGridHelperRowClassName",
      "getFieldGridLabelClassName",
      "getFieldGridValueClassName",
      "getFieldGroupTitleClassName",
    ],
  },
  {
    name: "TagInlineTextField",
    category: "common",
    subcategory: "common.input",
    description: "标签内联文本输入",
    composes: ["getTagInlineInputClassName"],
  },
  {
    name: "CreatePanel",
    category: "form",
    subcategory: "form.create",
    description: "新建入口内部 renderer（inline | block）",
    composes: ["InlineCreatePanel", "BlockCreatePanel"],
  },
  {
    name: "createCreatePanelBlock",
    category: "form",
    subcategory: "form.create",
    description: "新建区块声明助手",
    composes: ["CreatePanel", "BlockSurface"],
  },
  {
    name: "createActionsBlock",
    category: "common",
    subcategory: "common.block",
    description: "动作区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createAnalysisBlock",
    category: "common",
    subcategory: "common.block",
    description: "分析区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createBlockSurfaceBlock",
    category: "common",
    subcategory: "common.block",
    description: "通用区块 Surface wrapper 声明助手",
    composes: ["BlockSurface"],
  },
  {
    name: "createDocumentBlock",
    category: "document",
    subcategory: "document.surface",
    description: "文档 Surface block 声明助手",
    composes: ["DocumentSurface"],
  },
  {
    name: "createEmptyBlock",
    category: "common",
    subcategory: "common.block",
    description: "空态区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createFieldsBlock",
    category: "form",
    subcategory: "form.surface",
    description: "表单字段 block 声明助手",
    composes: ["FormSurface", "createFormBlock"],
  },
  {
    name: "createFormBlock",
    category: "form",
    subcategory: "form.surface",
    description: "表单 Surface block 声明助手",
    composes: ["FormSurface"],
  },
  {
    name: "createGroupBlock",
    category: "common",
    subcategory: "common.block",
    description: "区块分组声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createHeadingBlock",
    category: "common",
    subcategory: "common.block",
    description: "标题区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createInlineFieldsBlock",
    category: "form",
    subcategory: "form.surface",
    description: "行内字段或筛选字段 block 声明助手",
    composes: ["FormSurface", "createFormBlock"],
  },
  {
    name: "createMessageBlock",
    category: "common",
    subcategory: "common.block",
    description: "消息区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createModuleGridBlock",
    category: "common",
    subcategory: "common.block",
    description: "模块网格区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createPageBody",
    category: "page",
    subcategory: "page.surface",
    description: "页面正文声明助手",
    composes: ["PageSurface"],
  },
  {
    name: "createPageDataBlock",
    category: "data",
    subcategory: "data.surface",
    description: "数据 Surface block 声明助手",
    composes: ["DataSurface"],
  },
  {
    name: "createPageModalBlock",
    category: "page",
    subcategory: "page.surface",
    description: "页面 modal block 声明助手",
    composes: ["PageSurface"],
  },
  {
    name: "createPageSurfaceProps",
    category: "page",
    subcategory: "page.surface",
    description: "页面薄壳 props 声明助手",
    composes: ["PageSurface"],
  },
  {
    name: "createPageTabsNavigation",
    category: "page",
    subcategory: "page.surface",
    description: "页面 tabs 导航声明助手",
    composes: ["PageSurface"],
  },
  {
    name: "createPageTableBlock",
    category: "data",
    subcategory: "data.surface",
    description: "数据表格 block 声明助手",
    composes: ["DataSurface", "createPageDataBlock"],
  },
  {
    name: "createPanelBlock",
    category: "common",
    subcategory: "common.block",
    description: "面板区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createSectionBlock",
    category: "common",
    subcategory: "common.block",
    description: "章节区块声明助手",
    composes: ["BlockSurface", "createBlockSurfaceBlock"],
  },
  {
    name: "createVisualizationBlock",
    category: "visualization",
    subcategory: "visualization.surface",
    description: "可视化 Surface block 声明助手",
    composes: ["VisualizationSurface"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
