import type { CoreUiComponentRegistration } from "./component-registry-types";
import { generatedCoreUiSurfaceContracts } from "./generated-surface-contracts";

export const page_api_registry_entries = [
  {
    name: "AmountCell",
    category: "data",
    subcategory: "data.cell",
    description: "金额单元格",
    composes: ["NumberCell"],
  },
  {
    name: "BlockSurface",
    category: "common",
    subcategory: "common.block",
    description: "通用正文区块 Surface",
    contract: generatedCoreUiSurfaceContracts.BlockSurface,
    declares: [
      {
        name: "kind",
        description: "区块类型。",
        children: [
          { name: "content", description: "短正文内容。" },
          { name: "message", description: "状态消息。" },
          { name: "heading", description: "正文标题。" },
          { name: "empty", description: "空态。" },
          { name: "actions", description: "动作组。" },
          { name: "group", description: "区块分组。" },
          { name: "panel", description: "面板区块。" },
          { name: "section", description: "小节区块。" },
          { name: "moduleGrid", description: "模块卡片网格。" },
        ],
      },
      { name: "content", description: "短内容或区块正文；复杂组件应拆成专用 Surface。" },
      { name: "blocks", description: "分组、panel、section 内的子区块。" },
      { name: "actions", description: "区块局部动作。" },
      { name: "presentation", description: "区块语义与展示外壳，如 tone、level、layout、bodyClassName。" },
    ],
    composes: ["PanelCard", "SectionCard", "ModuleCard", "EmptyStateCard", "CommandButton", "AnalysisBlock"],
  },
  {
    name: "DataSurface",
    category: "data",
    subcategory: "data.surface",
    description: "L1 正文数据 Surface",
    contract: generatedCoreUiSurfaceContracts.DataSurface,
    declares: [
      {
        name: "kind",
        description: "数据视图类型。",
        children: [
          { name: "table", description: "行列数据表。" },
          { name: "structured", description: "结构化表格。" },
          { name: "records", description: "可展开记录列表。" },
          { name: "metrics", description: "指标摘要。" },
        ],
      },
      { name: "rows", description: "表格或结构化数据行。" },
      { name: "columns", description: "表格列和单元格声明。" },
      { name: "records", description: "可展开记录列表。" },
      { name: "metrics", description: "指标摘要。" },
      { name: "actions", description: "数据块局部动作；页面级动作放 PageSurface.toolbar。" },
    ],
    composes: ["DataTable", "TableScrollFrame", "StructuredTable", "DisclosureRecordCard", "MetricCard", "CodeBlock", "Badge", "NumberCell", "AmountCell", "InputControl", "SelectionGrid", "CommandButton", "EmptyStateCard", "PanelCard"],
  },
  {
    name: "AnalysisBlock",
    category: "common",
    subcategory: "common.block",
    description: "分析内容块",
    composes: ["PanelCard", "Toolbar"],
  },
  {
    name: "AutoSizeTextField",
    category: "common",
    subcategory: "common.input",
    description: "自适应文本输入",
  },
  {
    name: "CalendarDateInput",
    category: "common",
    subcategory: "common.input",
    description: "日期输入框",
    composes: ["FieldInputShell", "getFieldInputClassName"],
  },
  {
    name: "CheckboxChip",
    category: "common",
    subcategory: "common.input",
    description: "复选标签",
    composes: ["CheckboxField"],
  },
  {
    name: "CheckboxField",
    category: "common",
    subcategory: "common.input",
    description: "复选框",
  },
  {
    name: "ChoiceGroup",
    category: "common",
    subcategory: "common.input",
    description: "纸面选择组",
  },
  {
    name: "CodeBlock",
    category: "common",
    subcategory: "common.display",
    description: "代码块展示",
  },
  {
    name: "CommandButton",
    category: "common",
    subcategory: "common.action",
    description: "文字命令按钮",
    composes: ["getToolbarActionClassName"],
  },
  {
    name: "ConfirmModal",
    category: "feedback",
    subcategory: "feedback.renderer",
    description: "底层确认弹窗（Core 内部 / 专用弹窗使用）",
    composes: ["ActionButton", "getToolbarActionClassName"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
