/* eslint-disable max-lines */
// Auto-generated by scripts/generate-core-ui-surface-contracts.ts
// Do not edit by hand. Run `npm run core-ui:contracts` after changing Surface prop types.
import type { CoreUiCapabilityDescriptor } from "./component-registry-types";

export const generatedCoreUiSurfaceContracts = {
  BlockSurface: [
    {
      name: "kind",
      description: "可选值：actions / analysis / content / empty / group / heading / message / moduleGrid / panel / section。",
      children: [
        {
          name: "actions",
          description: "actions 分支声明。",
          children: [
            {
              name: "actions",
              description: "类型：BlockSurfaceCommandSpec[]。",
            },
          ],
        },
        {
          name: "analysis",
          description: "analysis 分支声明。",
          children: [
            {
              name: "title",
              description: "类型：ReactNode。",
            },
            {
              name: "subtitle",
              description: "类型：ReactNode。",
            },
            {
              name: "toolbarItems",
              description: "类型：SurfaceToolbarItems。",
            },
            {
              name: "actions",
              description: "类型：BlockSurfaceCommandSpec[]。",
            },
            {
              name: "content",
              description: "类型：ReactNode。",
            },
          ],
        },
        {
          name: "content",
          description: "content 分支声明。",
          children: [
            {
              name: "content",
              description: "类型：ReactNode。",
            },
          ],
        },
        {
          name: "empty",
          description: "empty 分支声明。",
          children: [
            {
              name: "content",
              description: "类型：ReactNode。",
            },
            {
              name: "presentation",
              description: "可选值：card / plain。",
              children: [
                {
                  name: "card",
                  description: "字面量取值。",
                },
                {
                  name: "plain",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "compact",
              description: "类型：boolean。",
            },
          ],
        },
        {
          name: "group",
          description: "group 分支声明。",
          children: [
            {
              name: "blocks",
              description: "类型：BlockSurfaceProps[]。",
            },
            {
              name: "layout",
              description: "可选值：grid / stack。",
              children: [
                {
                  name: "grid",
                  description: "字面量取值。",
                },
                {
                  name: "stack",
                  description: "字面量取值。",
                },
              ],
            },
          ],
        },
        {
          name: "heading",
          description: "heading 分支声明。",
          children: [
            {
              name: "title",
              description: "类型：ReactNode。",
            },
            {
              name: "subtitle",
              description: "类型：ReactNode。",
            },
            {
              name: "level",
              description: "可选值：1 / 2 / 3。",
              children: [
                {
                  name: "1",
                  description: "字面量取值。",
                },
                {
                  name: "2",
                  description: "字面量取值。",
                },
                {
                  name: "3",
                  description: "字面量取值。",
                },
              ],
            },
          ],
        },
        {
          name: "message",
          description: "message 分支声明。",
          children: [
            {
              name: "content",
              description: "类型：ReactNode。",
            },
            {
              name: "tone",
              description: "可选值：danger / default / muted / success / warning。",
              children: [
                {
                  name: "danger",
                  description: "字面量取值。",
                },
                {
                  name: "default",
                  description: "字面量取值。",
                },
                {
                  name: "muted",
                  description: "字面量取值。",
                },
                {
                  name: "success",
                  description: "字面量取值。",
                },
                {
                  name: "warning",
                  description: "字面量取值。",
                },
              ],
            },
          ],
        },
        {
          name: "moduleGrid",
          description: "moduleGrid 分支声明。",
          children: [
            {
              name: "title",
              description: "类型：ReactNode。",
            },
            {
              name: "summary",
              description: "类型：ReactNode。",
            },
            {
              name: "leading",
              description: "类型：ReactNode。",
            },
            {
              name: "afterGrid",
              description: "类型：ReactNode。",
            },
            {
              name: "fullScreen",
              description: "类型：boolean。",
            },
            {
              name: "centered",
              description: "类型：boolean。",
            },
            {
              name: "items",
              description: "类型：BlockSurfaceModuleGridItemSpec[]。",
            },
          ],
        },
        {
          name: "panel",
          description: "panel 分支声明。",
          children: [
            {
              name: "title",
              description: "类型：ReactNode。",
            },
            {
              name: "subtitle",
              description: "类型：ReactNode。",
            },
            {
              name: "actions",
              description: "类型：BlockSurfaceCommandSpec[]。",
            },
            {
              name: "content",
              description: "类型：ReactNode。",
            },
            {
              name: "blocks",
              description: "类型：BlockSurfaceProps[]。",
            },
            {
              name: "itemRef",
              description: "类型：((instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly) | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | RefObject<HTMLDivElement | null>。",
              children: [
                {
                  name: "current",
                  description: "The current value of the ref.",
                },
              ],
            },
          ],
        },
        {
          name: "section",
          description: "section 分支声明。",
          children: [
            {
              name: "title",
              description: "类型：ReactNode。",
            },
            {
              name: "subtitle",
              description: "类型：ReactNode。",
            },
            {
              name: "actions",
              description: "类型：BlockSurfaceCommandSpec[]。",
            },
            {
              name: "content",
              description: "类型：ReactNode。",
            },
            {
              name: "blocks",
              description: "类型：BlockSurfaceProps[]。",
            },
            {
              name: "itemRef",
              description: "类型：((instance: HTMLDivElement | null) => void | (() => VoidOrUndefinedOnly) | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | RefObject<HTMLDivElement | null>。",
              children: [
                {
                  name: "current",
                  description: "The current value of the ref.",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "key",
      description: "类型：string。",
    },
  ],
  DataSurface: [
    {
      name: "kind",
      description: "可选值：metrics / records / structured / table。",
      children: [
        {
          name: "metrics",
          description: "metrics 分支声明。",
          children: [
            {
              name: "metrics",
              description: "类型：DataSurfaceMetricSpec[]。",
            },
          ],
        },
        {
          name: "records",
          description: "records 分支声明。",
          children: [
            {
              name: "records",
              description: "类型：DataSurfaceRecordSpec<T>[]。",
            },
          ],
        },
        {
          name: "structured",
          description: "structured 分支声明。",
          children: [
            {
              name: "rows",
              description: "类型：DataSurfaceStructuredCellSpec[][]。",
            },
            {
              name: "structuredScroll",
              description: "类型：boolean。",
            },
            {
              name: "colWidths",
              description: "类型：(string | number)[]。",
            },
            {
              name: "rowHeights",
              description: "类型：(string | number)[]。",
            },
            {
              name: "frame",
              description: "可选值：bordered / clipped / plain。",
              children: [
                {
                  name: "bordered",
                  description: "字面量取值。",
                },
                {
                  name: "clipped",
                  description: "字面量取值。",
                },
                {
                  name: "plain",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "scroll",
              description: "类型：DataSurfaceScrollSpec。",
              children: [
                {
                  name: "x",
                  description: "类型：boolean。",
                },
                {
                  name: "y",
                  description: "可选值：auto / hidden。",
                  children: [
                    {
                      name: "auto",
                      description: "字面量取值。",
                    },
                    {
                      name: "hidden",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "maxHeight",
                  description: "可选值：lg / md / sm。",
                  children: [
                    {
                      name: "lg",
                      description: "字面量取值。",
                    },
                    {
                      name: "md",
                      description: "字面量取值。",
                    },
                    {
                      name: "sm",
                      description: "字面量取值。",
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          name: "table",
          description: "table 分支声明。",
          children: [
            {
              name: "rows",
              description: "类型：T[]。",
            },
            {
              name: "columns",
              description: "类型：DataSurfaceColumnSpec<T>[]。",
            },
            {
              name: "rowKey",
              description: "类型：(row: T, index: number) => string | number。",
            },
            {
              name: "visibleColumns",
              description: "类型：string[]。",
            },
            {
              name: "loading",
              description: "类型：boolean。",
            },
            {
              name: "emptyText",
              description: "类型：string。",
            },
            {
              name: "onRowClick",
              description: "类型：(row: T) => void。",
            },
            {
              name: "rowState",
              description: "类型：(row: T) => DataSurfaceRowState。",
            },
            {
              name: "frame",
              description: "可选值：bordered / clipped / plain。",
              children: [
                {
                  name: "bordered",
                  description: "字面量取值。",
                },
                {
                  name: "clipped",
                  description: "字面量取值。",
                },
                {
                  name: "plain",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "scroll",
              description: "类型：DataSurfaceScrollSpec。",
              children: [
                {
                  name: "x",
                  description: "类型：boolean。",
                },
                {
                  name: "y",
                  description: "可选值：auto / hidden。",
                  children: [
                    {
                      name: "auto",
                      description: "字面量取值。",
                    },
                    {
                      name: "hidden",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "maxHeight",
                  description: "可选值：lg / md / sm。",
                  children: [
                    {
                      name: "lg",
                      description: "字面量取值。",
                    },
                    {
                      name: "md",
                      description: "字面量取值。",
                    },
                    {
                      name: "sm",
                      description: "字面量取值。",
                    },
                  ],
                },
              ],
            },
            {
              name: "expandedRowKey",
              description: "类型：string | number。",
            },
            {
              name: "expandedRowKeys",
              description: "类型：(string | number)[] | Set<string | number>。",
            },
            {
              name: "expandedRowContent",
              description: "类型：(row: T) => ReactNode。",
            },
            {
              name: "rowActions",
              description: "类型：(row: T) => DataSurfaceRowActionSpec[]。",
            },
            {
              name: "rowEditActions",
              description: "类型：(row: T) => DataSurfaceRowEditActionSpec<T>。",
            },
            {
              name: "actionsColumn",
              description: "类型：DataSurfaceActionsColumnSpec。",
              children: [
                {
                  name: "key",
                  description: "类型：string。",
                },
                {
                  name: "label",
                  description: "类型：ReactNode。",
                },
                {
                  name: "align",
                  description: "可选值：center / left / right。",
                  children: [
                    {
                      name: "center",
                      description: "字面量取值。",
                    },
                    {
                      name: "left",
                      description: "字面量取值。",
                    },
                    {
                      name: "right",
                      description: "字面量取值。",
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "title",
      description: "类型：ReactNode。",
    },
    {
      name: "subtitle",
      description: "类型：ReactNode。",
    },
    {
      name: "actions",
      description: "类型：DataSurfaceCommandSpec[]。",
    },
    {
      name: "empty",
      description: "类型：ReactNode。",
    },
    {
      name: "framed",
      description: "类型：boolean。",
    },
    {
      name: "wrap",
      description: "类型：boolean。",
    },
    {
      name: "presentation",
      description: "类型：DataSurfacePresentationSpec。",
      children: [
        {
          name: "density",
          description: "可选值：compact / normal。",
          children: [
            {
              name: "compact",
              description: "字面量取值。",
            },
            {
              name: "normal",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "grid",
          description: "可选值：cells / none / rows。",
          children: [
            {
              name: "cells",
              description: "字面量取值。",
            },
            {
              name: "none",
              description: "字面量取值。",
            },
            {
              name: "rows",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "header",
          description: "可选值：plain / strong / tinted。",
          children: [
            {
              name: "plain",
              description: "字面量取值。",
            },
            {
              name: "strong",
              description: "字面量取值。",
            },
            {
              name: "tinted",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "rowHover",
          description: "可选值：interactive / neutral / none。",
          children: [
            {
              name: "interactive",
              description: "字面量取值。",
            },
            {
              name: "neutral",
              description: "字面量取值。",
            },
            {
              name: "none",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "stripe",
          description: "可选值：none / subtle。",
          children: [
            {
              name: "none",
              description: "字面量取值。",
            },
            {
              name: "subtle",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "cellWrap",
          description: "可选值：nowrap / wrap。",
          children: [
            {
              name: "nowrap",
              description: "字面量取值。",
            },
            {
              name: "wrap",
              description: "字面量取值。",
            },
          ],
        },
      ],
    },
  ],
  DocumentSurface: [
    {
      name: "kind",
      description: "可选值：pages。",
      children: [
        {
          name: "pages",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "pages",
      description: "类型：DocumentSurfacePageSpec[]。",
    },
  ],
  FormSurface: [
    {
      name: "kind",
      description: "可选值：detail / fields / filters / inline / login。",
      children: [
        {
          name: "detail",
          description: "detail 分支声明。",
        },
        {
          name: "fields",
          description: "fields 分支声明。",
        },
        {
          name: "filters",
          description: "filters 分支声明。",
        },
        {
          name: "inline",
          description: "inline 分支声明。",
        },
        {
          name: "login",
          description: "login 分支声明。",
        },
      ],
    },
    {
      name: "fields",
      description: "类型：FormSurfaceItemSpec<T>[]。",
    },
    {
      name: "field",
      description: "类型：FormSurfaceFieldSpec。",
      children: [
        {
          name: "kind",
          description: "可选值：field。",
          children: [
            {
              name: "field",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "key",
          description: "类型：string。",
        },
        {
          name: "label",
          description: "类型：ReactNode。",
        },
        {
          name: "spec",
          description: "类型：InputFieldSpec。",
          children: [
            {
              name: "valueType",
              description: "可选值：array / boolean / date / datetime / file / number / reference / string / time。",
              children: [
                {
                  name: "array",
                  description: "字面量取值。",
                },
                {
                  name: "boolean",
                  description: "字面量取值。",
                },
                {
                  name: "date",
                  description: "字面量取值。",
                },
                {
                  name: "datetime",
                  description: "字面量取值。",
                },
                {
                  name: "file",
                  description: "字面量取值。",
                },
                {
                  name: "number",
                  description: "字面量取值。",
                },
                {
                  name: "reference",
                  description: "字面量取值。",
                },
                {
                  name: "string",
                  description: "字面量取值。",
                },
                {
                  name: "time",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "control",
              description: "可选值：boolean / choice / collection / file / number / rating / reference / temporal / text。",
              children: [
                {
                  name: "boolean",
                  description: "字面量取值。",
                },
                {
                  name: "choice",
                  description: "字面量取值。",
                },
                {
                  name: "collection",
                  description: "字面量取值。",
                },
                {
                  name: "file",
                  description: "字面量取值。",
                },
                {
                  name: "number",
                  description: "字面量取值。",
                },
                {
                  name: "rating",
                  description: "字面量取值。",
                },
                {
                  name: "reference",
                  description: "字面量取值。",
                },
                {
                  name: "temporal",
                  description: "字面量取值。",
                },
                {
                  name: "text",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "options",
              description: "类型：InputOptions。",
              children: [
                {
                  name: "source",
                  description: "可选值：grouped / none / remote / static。",
                  children: [
                    {
                      name: "grouped",
                      description: "字面量取值。",
                    },
                    {
                      name: "none",
                      description: "字面量取值。",
                    },
                    {
                      name: "remote",
                      description: "字面量取值。",
                    },
                    {
                      name: "static",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "items",
                  description: "类型：InputOption[]。",
                },
                {
                  name: "mode",
                  description: "可选值：auto / autocomplete / dropdown / picker。",
                  children: [
                    {
                      name: "auto",
                      description: "字面量取值。",
                    },
                    {
                      name: "autocomplete",
                      description: "字面量取值。",
                    },
                    {
                      name: "dropdown",
                      description: "字面量取值。",
                    },
                    {
                      name: "picker",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "visibleCount",
                  description: "类型：number。",
                },
                {
                  name: "commonValues",
                  description: "类型：string[]。",
                },
                {
                  name: "searchPlaceholder",
                  description: "类型：string。",
                },
                {
                  name: "unsetLabel",
                  description: "类型：string。",
                },
                {
                  name: "groupLabel",
                  description: "类型：string。",
                },
                {
                  name: "optionLabel",
                  description: "类型：string。",
                },
                {
                  name: "changeGroupLabel",
                  description: "类型：string。",
                },
                {
                  name: "groups",
                  description: "类型：PickerGroupItem[]。",
                },
                {
                  name: "fkKey",
                  description: "类型：string。",
                },
                {
                  name: "endpoint",
                  description: "类型：string。",
                },
                {
                  name: "returnField",
                  description: "可选值：id / name / subtitle。",
                  children: [
                    {
                      name: "id",
                      description: "字面量取值。",
                    },
                    {
                      name: "name",
                      description: "字面量取值。",
                    },
                    {
                      name: "subtitle",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "lifecycleScope",
                  description: "可选值：active / all / archived。",
                  children: [
                    {
                      name: "active",
                      description: "字面量取值。",
                    },
                    {
                      name: "all",
                      description: "字面量取值。",
                    },
                    {
                      name: "archived",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "queryParams",
                  description: "类型：Record<string, string | number | boolean | null | undefined>。",
                },
              ],
            },
            {
              name: "format",
              description: "可选值：currency / date / datetime / number / percent / text / time。",
              children: [
                {
                  name: "currency",
                  description: "字面量取值。",
                },
                {
                  name: "date",
                  description: "字面量取值。",
                },
                {
                  name: "datetime",
                  description: "字面量取值。",
                },
                {
                  name: "number",
                  description: "字面量取值。",
                },
                {
                  name: "percent",
                  description: "字面量取值。",
                },
                {
                  name: "text",
                  description: "字面量取值。",
                },
                {
                  name: "time",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "mask",
              description: "类型：InputMask。",
            },
            {
              name: "multiline",
              description: "类型：boolean。",
            },
            {
              name: "multiple",
              description: "类型：boolean。",
            },
            {
              name: "presentation",
              description: "可选值：checkbox / choice / switch。",
              children: [
                {
                  name: "checkbox",
                  description: "字面量取值。",
                },
                {
                  name: "choice",
                  description: "字面量取值。",
                },
                {
                  name: "switch",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "precision",
              description: "可选值：date / datetime / time。",
              children: [
                {
                  name: "date",
                  description: "字面量取值。",
                },
                {
                  name: "datetime",
                  description: "字面量取值。",
                },
                {
                  name: "time",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "itemControl",
              description: "可选值：text。",
              children: [
                {
                  name: "text",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "state",
              description: "可选值：disabled / hidden / normal / readonly / required。",
              children: [
                {
                  name: "disabled",
                  description: "字面量取值。",
                },
                {
                  name: "hidden",
                  description: "字面量取值。",
                },
                {
                  name: "normal",
                  description: "字面量取值。",
                },
                {
                  name: "readonly",
                  description: "字面量取值。",
                },
                {
                  name: "required",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "validation",
              description: "类型：InputValidation。",
              children: [
                {
                  name: "required",
                  description: "类型：boolean。",
                },
                {
                  name: "min",
                  description: "类型：number。",
                },
                {
                  name: "max",
                  description: "类型：number。",
                },
                {
                  name: "pattern",
                  description: "类型：string。",
                },
              ],
            },
            {
              name: "usage",
              description: "可选值：filter / form / search / table。",
              children: [
                {
                  name: "filter",
                  description: "字面量取值。",
                },
                {
                  name: "form",
                  description: "字面量取值。",
                },
                {
                  name: "search",
                  description: "字面量取值。",
                },
                {
                  name: "table",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "dependencies",
              description: "类型：InputDependencies。",
              children: [
                {
                  name: "cascadeFrom",
                  description: "类型：string | string[]。",
                },
                {
                  name: "filters",
                  description: "类型：Record<string, unknown>。",
                },
                {
                  name: "queryParams",
                  description: "类型：Record<string, string | number | boolean | null | undefined>。",
                },
              ],
            },
          ],
        },
        {
          name: "value",
          description: "类型：{}。",
        },
        {
          name: "onChange",
          description: "类型：(value: unknown, option?: unknown) => void。",
        },
        {
          name: "required",
          description: "类型：boolean。",
        },
        {
          name: "hint",
          description: "类型：ReactNode。",
        },
        {
          name: "error",
          description: "类型：ReactNode。",
        },
        {
          name: "span",
          description: "可选值：full / wide。",
          children: [
            {
              name: "full",
              description: "字面量取值。",
            },
            {
              name: "wide",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "rows",
          description: "类型：number。",
        },
        {
          name: "displayValue",
          description: "类型：string。",
        },
        {
          name: "placeholder",
          description: "类型：string。",
        },
        {
          name: "size",
          description: "可选值：lg / md / sm。",
          children: [
            {
              name: "lg",
              description: "字面量取值。",
            },
            {
              name: "md",
              description: "字面量取值。",
            },
            {
              name: "sm",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "density",
          description: "可选值：compact / normal。",
          children: [
            {
              name: "compact",
              description: "字面量取值。",
            },
            {
              name: "normal",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "inputMode",
          description: "可选值：decimal / email / none / numeric / search / tel / text / url。",
          children: [
            {
              name: "decimal",
              description: "字面量取值。",
            },
            {
              name: "email",
              description: "字面量取值。",
            },
            {
              name: "none",
              description: "字面量取值。",
            },
            {
              name: "numeric",
              description: "字面量取值。",
            },
            {
              name: "search",
              description: "字面量取值。",
            },
            {
              name: "tel",
              description: "字面量取值。",
            },
            {
              name: "text",
              description: "字面量取值。",
            },
            {
              name: "url",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "type",
          description: "可选值：email / number / password / tel / text / url。",
          children: [
            {
              name: "email",
              description: "字面量取值。",
            },
            {
              name: "number",
              description: "字面量取值。",
            },
            {
              name: "password",
              description: "字面量取值。",
            },
            {
              name: "tel",
              description: "字面量取值。",
            },
            {
              name: "text",
              description: "字面量取值。",
            },
            {
              name: "url",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "minLength",
          description: "类型：number。",
        },
        {
          name: "maxLength",
          description: "类型：number。",
        },
        {
          name: "step",
          description: "类型：string | number。",
        },
        {
          name: "onKeyDown",
          description: "类型：KeyboardEventHandler<HTMLInputElement>。",
        },
        {
          name: "onBlur",
          description: "类型：FocusEventHandler<HTMLInputElement>。",
        },
        {
          name: "onFocus",
          description: "类型：FocusEventHandler<HTMLInputElement>。",
        },
        {
          name: "autoFocus",
          description: "类型：boolean。",
        },
        {
          name: "inputRef",
          description: "类型：((instance: HTMLInputElement | null) => void | (() => VoidOrUndefinedOnly) | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | RefObject<HTMLInputElement | null>。",
          children: [
            {
              name: "current",
              description: "The current value of the ref.",
            },
          ],
        },
        {
          name: "readOnly",
          description: "类型：boolean。",
        },
        {
          name: "ariaLabel",
          description: "类型：string。",
        },
        {
          name: "dataFieldKey",
          description: "类型：string。",
        },
        {
          name: "title",
          description: "类型：string。",
        },
        {
          name: "textAlign",
          description: "可选值：center / left / right。",
          children: [
            {
              name: "center",
              description: "字面量取值。",
            },
            {
              name: "left",
              description: "字面量取值。",
            },
            {
              name: "right",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "visualState",
          description: "可选值：default / error / info。",
          children: [
            {
              name: "default",
              description: "字面量取值。",
            },
            {
              name: "error",
              description: "字面量取值。",
            },
            {
              name: "info",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "resize",
          description: "可选值：both / none / vertical。",
          children: [
            {
              name: "both",
              description: "字面量取值。",
            },
            {
              name: "none",
              description: "字面量取值。",
            },
            {
              name: "vertical",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "choiceType",
          description: "可选值：checkbox / radio。",
          children: [
            {
              name: "checkbox",
              description: "字面量取值。",
            },
            {
              name: "radio",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "choiceName",
          description: "类型：string。",
        },
        {
          name: "accept",
          description: "类型：string。",
        },
        {
          name: "multiple",
          description: "类型：boolean。",
        },
        {
          name: "fileVariant",
          description: "可选值：button / inline。",
          children: [
            {
              name: "button",
              description: "字面量取值。",
            },
            {
              name: "inline",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "resetOnChange",
          description: "类型：boolean。",
        },
        {
          name: "showFileName",
          description: "类型：boolean。",
        },
        {
          name: "buttonLabel",
          description: "类型：ReactNode。",
        },
        {
          name: "onFilesChange",
          description: "类型：(files: FileList | null) => void。",
        },
        {
          name: "autocompletePresentation",
          description: "可选值：inline / popover。",
          children: [
            {
              name: "inline",
              description: "字面量取值。",
            },
            {
              name: "popover",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "onQueryChange",
          description: "类型：(query: string) => void。",
        },
        {
          name: "loading",
          description: "类型：boolean。",
        },
        {
          name: "emptyText",
          description: "类型：string。",
        },
        {
          name: "confirmDelete",
          description: "类型：(options?: Partial<ConfirmOptions>) => Promise<boolean>。",
        },
        {
          name: "confirmRemove",
          description: "类型：boolean。",
        },
        {
          name: "removeConfirmMessage",
          description: "类型：(item: string) => string。",
        },
        {
          name: "removeConfirmTitle",
          description: "类型：string。",
        },
        {
          name: "ratingLabel",
          description: "类型：string。",
        },
        {
          name: "ratingMax",
          description: "类型：number。",
        },
        {
          name: "showRatingLabel",
          description: "类型：boolean。",
        },
      ],
    },
    {
      name: "columns",
      description: "可选值：1 / 2 / 3。",
      children: [
        {
          name: "1",
          description: "字面量取值。",
        },
        {
          name: "2",
          description: "字面量取值。",
        },
        {
          name: "3",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "mode",
      description: "可选值：detail / edit / mixed / view。",
      children: [
        {
          name: "detail",
          description: "字面量取值。",
        },
        {
          name: "edit",
          description: "字面量取值。",
        },
        {
          name: "mixed",
          description: "字面量取值。",
        },
        {
          name: "view",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "actions",
      description: "类型：FormSurfaceCommandSpec[]。",
    },
    {
      name: "onSubmit",
      description: "类型：() => void。",
    },
  ],
  InputControl: [
    {
      name: "spec",
      description: "类型：InputFieldSpec。",
      children: [
        {
          name: "valueType",
          description: "可选值：array / boolean / date / datetime / file / number / reference / string / time。",
          children: [
            {
              name: "array",
              description: "字面量取值。",
            },
            {
              name: "boolean",
              description: "字面量取值。",
            },
            {
              name: "date",
              description: "字面量取值。",
            },
            {
              name: "datetime",
              description: "字面量取值。",
            },
            {
              name: "file",
              description: "字面量取值。",
            },
            {
              name: "number",
              description: "字面量取值。",
            },
            {
              name: "reference",
              description: "字面量取值。",
            },
            {
              name: "string",
              description: "字面量取值。",
            },
            {
              name: "time",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "control",
          description: "可选值：boolean / choice / collection / file / number / rating / reference / temporal / text。",
          children: [
            {
              name: "boolean",
              description: "字面量取值。",
            },
            {
              name: "choice",
              description: "字面量取值。",
            },
            {
              name: "collection",
              description: "字面量取值。",
            },
            {
              name: "file",
              description: "字面量取值。",
            },
            {
              name: "number",
              description: "字面量取值。",
            },
            {
              name: "rating",
              description: "字面量取值。",
            },
            {
              name: "reference",
              description: "字面量取值。",
            },
            {
              name: "temporal",
              description: "字面量取值。",
            },
            {
              name: "text",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "options",
          description: "类型：InputOptions。",
          children: [
            {
              name: "source",
              description: "可选值：grouped / none / remote / static。",
              children: [
                {
                  name: "grouped",
                  description: "字面量取值。",
                },
                {
                  name: "none",
                  description: "字面量取值。",
                },
                {
                  name: "remote",
                  description: "字面量取值。",
                },
                {
                  name: "static",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "items",
              description: "类型：InputOption[]。",
            },
            {
              name: "mode",
              description: "可选值：auto / autocomplete / dropdown / picker。",
              children: [
                {
                  name: "auto",
                  description: "字面量取值。",
                },
                {
                  name: "autocomplete",
                  description: "字面量取值。",
                },
                {
                  name: "dropdown",
                  description: "字面量取值。",
                },
                {
                  name: "picker",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "visibleCount",
              description: "类型：number。",
            },
            {
              name: "commonValues",
              description: "类型：string[]。",
            },
            {
              name: "searchPlaceholder",
              description: "类型：string。",
            },
            {
              name: "unsetLabel",
              description: "类型：string。",
            },
            {
              name: "groupLabel",
              description: "类型：string。",
            },
            {
              name: "optionLabel",
              description: "类型：string。",
            },
            {
              name: "changeGroupLabel",
              description: "类型：string。",
            },
            {
              name: "groups",
              description: "类型：PickerGroupItem[]。",
            },
            {
              name: "fkKey",
              description: "类型：string。",
            },
            {
              name: "endpoint",
              description: "类型：string。",
            },
            {
              name: "returnField",
              description: "可选值：id / name / subtitle。",
              children: [
                {
                  name: "id",
                  description: "字面量取值。",
                },
                {
                  name: "name",
                  description: "字面量取值。",
                },
                {
                  name: "subtitle",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "lifecycleScope",
              description: "可选值：active / all / archived。",
              children: [
                {
                  name: "active",
                  description: "字面量取值。",
                },
                {
                  name: "all",
                  description: "字面量取值。",
                },
                {
                  name: "archived",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "queryParams",
              description: "类型：Record<string, string | number | boolean | null | undefined>。",
            },
          ],
        },
        {
          name: "format",
          description: "可选值：currency / date / datetime / number / percent / text / time。",
          children: [
            {
              name: "currency",
              description: "字面量取值。",
            },
            {
              name: "date",
              description: "字面量取值。",
            },
            {
              name: "datetime",
              description: "字面量取值。",
            },
            {
              name: "number",
              description: "字面量取值。",
            },
            {
              name: "percent",
              description: "字面量取值。",
            },
            {
              name: "text",
              description: "字面量取值。",
            },
            {
              name: "time",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "mask",
          description: "类型：InputMask。",
        },
        {
          name: "multiline",
          description: "类型：boolean。",
        },
        {
          name: "multiple",
          description: "类型：boolean。",
        },
        {
          name: "presentation",
          description: "可选值：checkbox / choice / switch。",
          children: [
            {
              name: "checkbox",
              description: "字面量取值。",
            },
            {
              name: "choice",
              description: "字面量取值。",
            },
            {
              name: "switch",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "precision",
          description: "可选值：date / datetime / time。",
          children: [
            {
              name: "date",
              description: "字面量取值。",
            },
            {
              name: "datetime",
              description: "字面量取值。",
            },
            {
              name: "time",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "itemControl",
          description: "可选值：text。",
          children: [
            {
              name: "text",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "state",
          description: "可选值：disabled / hidden / normal / readonly / required。",
          children: [
            {
              name: "disabled",
              description: "字面量取值。",
            },
            {
              name: "hidden",
              description: "字面量取值。",
            },
            {
              name: "normal",
              description: "字面量取值。",
            },
            {
              name: "readonly",
              description: "字面量取值。",
            },
            {
              name: "required",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "validation",
          description: "类型：InputValidation。",
          children: [
            {
              name: "required",
              description: "类型：boolean。",
            },
            {
              name: "min",
              description: "类型：number。",
            },
            {
              name: "max",
              description: "类型：number。",
            },
            {
              name: "pattern",
              description: "类型：string。",
            },
          ],
        },
        {
          name: "usage",
          description: "可选值：filter / form / search / table。",
          children: [
            {
              name: "filter",
              description: "字面量取值。",
            },
            {
              name: "form",
              description: "字面量取值。",
            },
            {
              name: "search",
              description: "字面量取值。",
            },
            {
              name: "table",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "dependencies",
          description: "类型：InputDependencies。",
          children: [
            {
              name: "cascadeFrom",
              description: "类型：string | string[]。",
            },
            {
              name: "filters",
              description: "类型：Record<string, unknown>。",
            },
            {
              name: "queryParams",
              description: "类型：Record<string, string | number | boolean | null | undefined>。",
            },
          ],
        },
      ],
    },
    {
      name: "value",
      description: "类型：{}。",
    },
    {
      name: "displayValue",
      description: "类型：string。",
    },
    {
      name: "onChange",
      description: "类型：(value: unknown, option?: unknown) => void。",
    },
    {
      name: "placeholder",
      description: "类型：string。",
    },
    {
      name: "size",
      description: "可选值：lg / md / sm。",
      children: [
        {
          name: "lg",
          description: "字面量取值。",
        },
        {
          name: "md",
          description: "字面量取值。",
        },
        {
          name: "sm",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "density",
      description: "可选值：compact / normal。",
      children: [
        {
          name: "compact",
          description: "字面量取值。",
        },
        {
          name: "normal",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "rows",
      description: "类型：number。",
    },
    {
      name: "inputMode",
      description: "可选值：decimal / email / none / numeric / search / tel / text / url。",
      children: [
        {
          name: "decimal",
          description: "字面量取值。",
        },
        {
          name: "email",
          description: "字面量取值。",
        },
        {
          name: "none",
          description: "字面量取值。",
        },
        {
          name: "numeric",
          description: "字面量取值。",
        },
        {
          name: "search",
          description: "字面量取值。",
        },
        {
          name: "tel",
          description: "字面量取值。",
        },
        {
          name: "text",
          description: "字面量取值。",
        },
        {
          name: "url",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "type",
      description: "可选值：email / number / password / tel / text / url。",
      children: [
        {
          name: "email",
          description: "字面量取值。",
        },
        {
          name: "number",
          description: "字面量取值。",
        },
        {
          name: "password",
          description: "字面量取值。",
        },
        {
          name: "tel",
          description: "字面量取值。",
        },
        {
          name: "text",
          description: "字面量取值。",
        },
        {
          name: "url",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "minLength",
      description: "类型：number。",
    },
    {
      name: "maxLength",
      description: "类型：number。",
    },
    {
      name: "step",
      description: "类型：string | number。",
    },
    {
      name: "onKeyDown",
      description: "类型：KeyboardEventHandler<HTMLInputElement>。",
    },
    {
      name: "onBlur",
      description: "类型：FocusEventHandler<HTMLInputElement>。",
    },
    {
      name: "onFocus",
      description: "类型：FocusEventHandler<HTMLInputElement>。",
    },
    {
      name: "autoFocus",
      description: "类型：boolean。",
    },
    {
      name: "inputRef",
      description: "类型：((instance: HTMLInputElement | null) => void | (() => VoidOrUndefinedOnly) | DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES[keyof DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES]) | RefObject<HTMLInputElement | null>。",
      children: [
        {
          name: "current",
          description: "The current value of the ref.",
        },
      ],
    },
    {
      name: "readOnly",
      description: "类型：boolean。",
    },
    {
      name: "ariaLabel",
      description: "类型：string。",
    },
    {
      name: "dataFieldKey",
      description: "类型：string。",
    },
    {
      name: "title",
      description: "类型：string。",
    },
    {
      name: "textAlign",
      description: "可选值：center / left / right。",
      children: [
        {
          name: "center",
          description: "字面量取值。",
        },
        {
          name: "left",
          description: "字面量取值。",
        },
        {
          name: "right",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "visualState",
      description: "可选值：default / error / info。",
      children: [
        {
          name: "default",
          description: "字面量取值。",
        },
        {
          name: "error",
          description: "字面量取值。",
        },
        {
          name: "info",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "resize",
      description: "可选值：both / none / vertical。",
      children: [
        {
          name: "both",
          description: "字面量取值。",
        },
        {
          name: "none",
          description: "字面量取值。",
        },
        {
          name: "vertical",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "choiceType",
      description: "可选值：checkbox / radio。",
      children: [
        {
          name: "checkbox",
          description: "字面量取值。",
        },
        {
          name: "radio",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "choiceName",
      description: "类型：string。",
    },
    {
      name: "accept",
      description: "类型：string。",
    },
    {
      name: "multiple",
      description: "类型：boolean。",
    },
    {
      name: "fileVariant",
      description: "可选值：button / inline。",
      children: [
        {
          name: "button",
          description: "字面量取值。",
        },
        {
          name: "inline",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "resetOnChange",
      description: "类型：boolean。",
    },
    {
      name: "showFileName",
      description: "类型：boolean。",
    },
    {
      name: "buttonLabel",
      description: "类型：ReactNode。",
    },
    {
      name: "onFilesChange",
      description: "类型：(files: FileList | null) => void。",
    },
    {
      name: "autocompletePresentation",
      description: "可选值：inline / popover。",
      children: [
        {
          name: "inline",
          description: "字面量取值。",
        },
        {
          name: "popover",
          description: "字面量取值。",
        },
      ],
    },
    {
      name: "onQueryChange",
      description: "类型：(query: string) => void。",
    },
    {
      name: "loading",
      description: "类型：boolean。",
    },
    {
      name: "emptyText",
      description: "类型：string。",
    },
    {
      name: "confirmDelete",
      description: "类型：(options?: Partial<ConfirmOptions>) => Promise<boolean>。",
    },
    {
      name: "confirmRemove",
      description: "类型：boolean。",
    },
    {
      name: "removeConfirmMessage",
      description: "类型：(item: string) => string。",
    },
    {
      name: "removeConfirmTitle",
      description: "类型：string。",
    },
    {
      name: "ratingLabel",
      description: "类型：string。",
    },
    {
      name: "ratingMax",
      description: "类型：number。",
    },
    {
      name: "showRatingLabel",
      description: "类型：boolean。",
    },
  ],
  NavigationSurface: [
    {
      name: "kind",
      description: "可选值：disclosure / pagination / selector / selector / steps / tabs。",
      children: [
        {
          name: "disclosure",
          description: "disclosure 分支声明。",
          children: [
            {
              name: "title",
              description: "类型：string。",
            },
            {
              name: "count",
              description: "类型：number。",
            },
            {
              name: "expanded",
              description: "类型：boolean。",
            },
            {
              name: "onToggle",
              description: "类型：() => void。",
            },
          ],
        },
        {
          name: "pagination",
          description: "pagination 分支声明。",
          children: [
            {
              name: "pagination",
              description: "类型：NavigationSurfacePaginationSpec。",
              children: [
                {
                  name: "page",
                  description: "类型：number。",
                },
                {
                  name: "totalPages",
                  description: "类型：number。",
                },
                {
                  name: "total",
                  description: "类型：number。",
                },
                {
                  name: "onPageChange",
                  description: "类型：(page: number) => void。",
                },
                {
                  name: "compact",
                  description: "类型：boolean。",
                },
              ],
            },
          ],
        },
        {
          name: "selector",
          description: "selector 分支声明。",
          children: [
            {
              name: "selector",
              description: "类型：NavigationSurfaceSelectorSpec<T>。",
              children: [
                {
                  name: "actions",
                  description: "类型：ReactNode。",
                },
                {
                  name: "size",
                  description: "可选值：md / sm。",
                  children: [
                    {
                      name: "md",
                      description: "字面量取值。",
                    },
                    {
                      name: "sm",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "title",
                  description: "类型：ReactNode。",
                },
                {
                  name: "loading",
                  description: "类型：boolean。",
                },
                {
                  name: "emptyText",
                  description: "类型：ReactNode。",
                },
                {
                  name: "subtitle",
                  description: "类型：ReactNode。",
                },
                {
                  name: "filter",
                  description: "类型：{ kind: 'search'; value: string; onChange: (value: string) => void; placeholder?: string; }。",
                  children: [
                    {
                      name: "kind",
                      description: "可选值：search。",
                      children: [
                        {
                          name: "search",
                          description: "字面量取值。",
                        },
                      ],
                    },
                    {
                      name: "value",
                      description: "类型：string。",
                    },
                    {
                      name: "onChange",
                      description: "类型：(value: string) => void。",
                    },
                    {
                      name: "placeholder",
                      description: "类型：string。",
                    },
                  ],
                },
                {
                  name: "mode",
                  description: "可选值：grid / list / tree。",
                  children: [
                    {
                      name: "grid",
                      description: "字面量取值。",
                    },
                    {
                      name: "list",
                      description: "字面量取值。",
                    },
                    {
                      name: "tree",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "renderItem",
                  description: "类型：(item: T, ctx: SelectorListItemContext) => Omit<SelectorCardProps, 'onClick'> | (item: T, ctx: SelectorTreeItemContext) => Omit<TreeNodeCardProps, 'active' | 'onClick' | 'toggle' | 'children'>。",
                },
                {
                  name: "items",
                  description: "类型：T[]。",
                },
                {
                  name: "selectedId",
                  description: "类型：string | number。",
                },
                {
                  name: "onSelect",
                  description: "类型：(item: T) => void。",
                },
                {
                  name: "getKey",
                  description: "类型：(item: T) => string | number。",
                },
                {
                  name: "groupBy",
                  description: "类型：(item: T) => string | null | undefined。",
                },
                {
                  name: "loadingText",
                  description: "类型：ReactNode。",
                },
                {
                  name: "framed",
                  description: "类型：boolean。",
                },
                {
                  name: "getChildren",
                  description: "类型：(item: T) => T[] | undefined。",
                },
                {
                  name: "expandedIds",
                  description: "类型：Iterable<string | number>。",
                },
                {
                  name: "defaultExpandedIds",
                  description: "类型：Iterable<string | number>。",
                },
                {
                  name: "onToggle",
                  description: "类型：(id: string | number, expanded: boolean) => void。",
                },
                {
                  name: "collapsible",
                  description: "类型：boolean。",
                },
                {
                  name: "ariaLabel",
                  description: "类型：string。",
                },
                {
                  name: "disabled",
                  description: "类型：boolean。",
                },
                {
                  name: "columns",
                  description: "可选值：1 / 2 / 3 / 4。",
                  children: [
                    {
                      name: "1",
                      description: "字面量取值。",
                    },
                    {
                      name: "2",
                      description: "字面量取值。",
                    },
                    {
                      name: "3",
                      description: "字面量取值。",
                    },
                    {
                      name: "4",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "layout",
                  description: "可选值：auto / fixed。",
                  children: [
                    {
                      name: "auto",
                      description: "字面量取值。",
                    },
                    {
                      name: "fixed",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "minItemWidth",
                  description: "可选值：lg / md / sm。",
                  children: [
                    {
                      name: "lg",
                      description: "字面量取值。",
                    },
                    {
                      name: "md",
                      description: "字面量取值。",
                    },
                    {
                      name: "sm",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "truncate",
                  description: "标签超长时单行省略；默认为 true，传 false 可恢复自动换行",
                },
                {
                  name: "getLabel",
                  description: "类型：(item: T, index: number) => string。",
                },
                {
                  name: "getCode",
                  description: "类型：(item: T, index: number) => string | undefined。",
                },
              ],
            },
          ],
        },
        {
          name: "selector",
          description: "selector 分支声明。",
          children: [
            {
              name: "grid",
              description: "类型：NavigationSurfaceGridSpec。",
              children: [
                {
                  name: "options",
                  description: "类型：SelectionGridOption[]。",
                },
                {
                  name: "value",
                  description: "类型：string。",
                },
                {
                  name: "onChange",
                  description: "类型：(value: string) => void。",
                },
                {
                  name: "mode",
                  description: "可选值：action / readOnly / select。",
                  children: [
                    {
                      name: "action",
                      description: "字面量取值。",
                    },
                    {
                      name: "readOnly",
                      description: "字面量取值。",
                    },
                    {
                      name: "select",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "onItemClick",
                  description: "类型：(option: SelectionGridOption) => void。",
                },
                {
                  name: "columns",
                  description: "可选值：1 / 2 / 3 / 4。",
                  children: [
                    {
                      name: "1",
                      description: "字面量取值。",
                    },
                    {
                      name: "2",
                      description: "字面量取值。",
                    },
                    {
                      name: "3",
                      description: "字面量取值。",
                    },
                    {
                      name: "4",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "layout",
                  description: "可选值：auto / fixed。",
                  children: [
                    {
                      name: "auto",
                      description: "字面量取值。",
                    },
                    {
                      name: "fixed",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "minItemWidth",
                  description: "可选值：lg / md / sm。",
                  children: [
                    {
                      name: "lg",
                      description: "字面量取值。",
                    },
                    {
                      name: "md",
                      description: "字面量取值。",
                    },
                    {
                      name: "sm",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "truncate",
                  description: "类型：boolean。",
                },
                {
                  name: "disabled",
                  description: "类型：boolean。",
                },
                {
                  name: "emptyText",
                  description: "类型：ReactNode。",
                },
                {
                  name: "ariaLabel",
                  description: "类型：string。",
                },
              ],
            },
          ],
        },
        {
          name: "steps",
          description: "steps 分支声明。",
          children: [
            {
              name: "steps",
              description: "类型：NavigationSurfaceStepSpec[]。",
            },
            {
              name: "active",
              description: "类型：string。",
            },
            {
              name: "activeChild",
              description: "类型：string。",
            },
            {
              name: "onChange",
              description: "类型：(key: string) => void。",
            },
            {
              name: "onChildChange",
              description: "类型：(key: string) => void。",
            },
            {
              name: "variant",
              description: "可选值：large / small。",
              children: [
                {
                  name: "large",
                  description: "字面量取值。",
                },
                {
                  name: "small",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "ariaLabel",
              description: "类型：string。",
            },
          ],
        },
        {
          name: "tabs",
          description: "tabs 分支声明。",
          children: [
            {
              name: "label",
              description: "类型：ReactNode。",
            },
            {
              name: "tabs",
              description: "类型：NavigationSurfaceTabsSpec。",
              children: [
                {
                  name: "onChange",
                  description: "类型：(key: string) => void。",
                },
                {
                  name: "ariaLabel",
                  description: "类型：string。",
                },
                {
                  name: "active",
                  description: "类型：string。",
                },
                {
                  name: "variant",
                  description: "可选值：large / micro / mid / small。",
                  children: [
                    {
                      name: "large",
                      description: "字面量取值。",
                    },
                    {
                      name: "micro",
                      description: "字面量取值。",
                    },
                    {
                      name: "mid",
                      description: "字面量取值。",
                    },
                    {
                      name: "small",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "tabs",
                  description: "类型：TabDef[]。",
                },
                {
                  name: "accordion",
                  description: "类型：false | true。",
                },
                {
                  name: "kind",
                  description: "可选值：page / table。",
                  children: [
                    {
                      name: "page",
                      description: "字面量取值。",
                    },
                    {
                      name: "table",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "leadingActions",
                  description: "类型：TabBarAction[]。",
                },
                {
                  name: "trailingActions",
                  description: "类型：TabBarAction[]。",
                },
                {
                  name: "activeChild",
                  description: "类型：string。",
                },
                {
                  name: "onChildChange",
                  description: "类型：(key: string) => void。",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
  PageSurface: [
    {
      name: "kind",
      description: "可选值：analysis / detail / list / settings / split。",
      children: [
        {
          name: "analysis",
          description: "analysis 分支声明。",
        },
        {
          name: "detail",
          description: "detail 分支声明。",
        },
        {
          name: "list",
          description: "list 分支声明。",
        },
        {
          name: "settings",
          description: "settings 分支声明。",
        },
        {
          name: "split",
          description: "split 分支声明。",
          children: [
            {
              name: "sideOpen",
              description: "类型：boolean。",
            },
            {
              name: "drawerOpen",
              description: "类型：boolean。",
            },
            {
              name: "onSideOpenChange",
              description: "类型：(open: boolean) => void。",
            },
            {
              name: "onDrawerOpenChange",
              description: "类型：(open: boolean) => void。",
            },
            {
              name: "sideLabel",
              description: "类型：string。",
            },
            {
              name: "side",
              description: "类型：PageSurfaceSideSpec。",
              children: [
                {
                  name: "blocks",
                  description: "类型：PageSurfaceBlockSpec[]。",
                },
                {
                  name: "drawerBlocks",
                  description: "类型：PageSurfaceBlockSpec[]。",
                },
              ],
            },
            {
              name: "showSideControls",
              description: "类型：boolean。",
            },
            {
              name: "splitRatio",
              description: "类型：readonly [number, number]。",
            },
          ],
        },
      ],
    },
    {
      name: "header",
      description: "类型：PageSurfaceHeaderSpec。",
      children: [
        {
          name: "hidden",
          description: "类型：boolean。",
        },
        {
          name: "title",
          description: "类型：ReactNode。",
        },
        {
          name: "backHref",
          description: "类型：string。",
        },
        {
          name: "backLabel",
          description: "类型：ReactNode。",
        },
        {
          name: "leading",
          description: "类型：ReactNode。",
        },
        {
          name: "actions",
          description: "类型：ReactNode。",
        },
      ],
    },
    {
      name: "navigation",
      description: "类型：PageSurfaceNavigationSpec。",
      children: [
        {
          name: "kind",
          description: "可选值：cards / tabs。",
          children: [
            {
              name: "cards",
              description: "字面量取值。",
            },
            {
              name: "tabs",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "level",
          description: "可选值：1 / 2。",
          children: [
            {
              name: "1",
              description: "字面量取值。",
            },
            {
              name: "2",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "items",
          description: "类型：PageSurfaceNavigationItemSpec[]。",
        },
        {
          name: "active",
          description: "类型：string。",
        },
        {
          name: "activeChild",
          description: "类型：string。",
        },
        {
          name: "onChange",
          description: "类型：(key: string) => void。",
        },
        {
          name: "onChildChange",
          description: "类型：(key: string) => void。",
        },
        {
          name: "hidden",
          description: "类型：boolean。",
        },
      ],
    },
    {
      name: "toolbar",
      description: "类型：PageSurfaceToolbarSpec。",
      children: [
        {
          name: "items",
          description: "类型：SurfaceToolbarItems。",
        },
        {
          name: "onSubmit",
          description: "类型：() => void。",
        },
        {
          name: "hidden",
          description: "类型：boolean。",
        },
      ],
    },
    {
      name: "footer",
      description: "类型：PageSurfaceFooterSpec。",
      children: [
        {
          name: "hidden",
          description: "类型：boolean。",
        },
        {
          name: "pagination",
          description: "类型：PageSurfacePaginationSpec。",
          children: [
            {
              name: "page",
              description: "类型：number。",
            },
            {
              name: "totalPages",
              description: "类型：number。",
            },
            {
              name: "total",
              description: "类型：number。",
            },
            {
              name: "onPageChange",
              description: "类型：(page: number) => void。",
            },
            {
              name: "compact",
              description: "类型：boolean。",
            },
          ],
        },
      ],
    },
    {
      name: "body",
      description: "类型：PageSurfaceBodySpec。",
      children: [
        {
          name: "layout",
          description: "可选值：single / split。",
          children: [
            {
              name: "single",
              description: "字面量取值。",
            },
            {
              name: "split",
              description: "字面量取值。",
            },
          ],
        },
        {
          name: "blocks",
          description: "类型：PageSurfaceBlockSpec[]。",
        },
        {
          name: "empty",
          description: "类型：PageSurfaceEmptySpec。",
          children: [
            {
              name: "presentation",
              description: "可选值：card / plain。",
              children: [
                {
                  name: "card",
                  description: "字面量取值。",
                },
                {
                  name: "plain",
                  description: "字面量取值。",
                },
              ],
            },
            {
              name: "content",
              description: "类型：ReactNode。",
            },
            {
              name: "compact",
              description: "类型：boolean。",
            },
          ],
        },
        {
          name: "commands",
          description: "类型：PageSurfaceCommandSpec[]。",
        },
      ],
    },
    {
      name: "embedded",
      description: "类型：boolean。",
    },
  ],
  VisualizationSurface: [
    {
      name: "kind",
      description: "可选值：chart / gantt。",
      children: [
        {
          name: "chart",
          description: "chart 分支声明。",
          children: [
            {
              name: "visual",
              description: "类型：VisualizationSpec。",
              children: [
                {
                  name: "kind",
                  description: "可选值：barChart / comparisonBars / groupedBarChart / tree。",
                  children: [
                    {
                      name: "barChart",
                      description: "字面量取值。",
                    },
                    {
                      name: "comparisonBars",
                      description: "字面量取值。",
                    },
                    {
                      name: "groupedBarChart",
                      description: "字面量取值。",
                    },
                    {
                      name: "tree",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "title",
                  description: "类型：string。",
                },
                {
                  name: "bars",
                  description: "类型：VisualizationBarSpec[]。",
                },
                {
                  name: "min",
                  description: "类型：number。",
                },
                {
                  name: "max",
                  description: "类型：number。",
                },
                {
                  name: "height",
                  description: "类型：number。",
                },
                {
                  name: "emptyText",
                  description: "类型：string。",
                },
                {
                  name: "legend",
                  description: "类型：VisualizationLegendSpec[]。",
                },
                {
                  name: "groups",
                  description: "类型：VisualizationGroupedBarGroupSpec[]。",
                },
                {
                  name: "sections",
                  description: "类型：VisualizationComparisonBarSectionSpec[]。",
                },
                {
                  name: "nodes",
                  description: "类型：VisualizationTreeNodeSpec[]。",
                },
                {
                  name: "maxHeight",
                  description: "类型：number。",
                },
              ],
            },
          ],
        },
        {
          name: "gantt",
          description: "gantt 分支声明。",
          children: [
            {
              name: "gantt",
              description: "类型：VisualizationGanttSpec。",
              children: [
                {
                  name: "kind",
                  description: "可选值：gantt。",
                  children: [
                    {
                      name: "gantt",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "rows",
                  description: "类型：VisualizationGanttRowSpec[]。",
                },
                {
                  name: "periodStart",
                  description: "类型：string | Date。",
                },
                {
                  name: "zoom",
                  description: "可选值：month / quarter / year。",
                  children: [
                    {
                      name: "month",
                      description: "字面量取值。",
                    },
                    {
                      name: "quarter",
                      description: "字面量取值。",
                    },
                    {
                      name: "year",
                      description: "字面量取值。",
                    },
                  ],
                },
                {
                  name: "leftHeader",
                  description: "类型：ReactNode。",
                },
                {
                  name: "emptyText",
                  description: "类型：ReactNode。",
                },
                {
                  name: "dependencies",
                  description: "类型：VisualizationGanttDependencySpec[]。",
                },
                {
                  name: "onToggle",
                  description: "类型：(key: string) => void。",
                },
              ],
            },
            {
              name: "empty",
              description: "类型：ReactNode。",
            },
          ],
        },
      ],
    },
    {
      name: "title",
      description: "类型：ReactNode。",
    },
    {
      name: "subtitle",
      description: "类型：ReactNode。",
    },
    {
      name: "framed",
      description: "类型：boolean。",
    },
  ],
} as const satisfies Record<string, readonly CoreUiCapabilityDescriptor[]>;
