// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createElement } from "react";
import { requireAdminManageAccess } from "@workspace/platform/server/auth";
import { AdminManagePageView } from "@workspace/settings/ui/SystemPages";

export default async function AdminPage() {
  const user = await requireAdminManageAccess();
  return createElement(AdminManagePageView, { user });
}
