import type { ActionContractMetadata } from "./action-contract";
import {
  getWorkGoalActionDescriptor,
  type WorkGoalActionKey,
} from "./work-goal-action-descriptors";

const WORK_TASKS_RESOURCE = {
  resourceKey: "work.tasks",
  moduleKey: "work",
  scopeTypes: ["personal", "company", "committee", "department"],
  directPermissionAction: "update",
  submitPermissionAction: "submit",
  processPermissionAction: "approve",
} as const;

const WORK_TASKS_WORKFLOW_MUTATION = {
  handlerCanRevise: true,
  requestCanWithdraw: true,
  requestCanRevise: true,
  requestCanCancel: true,
  requestCanResubmit: true,
} as const;

const WORK_TASKS_WORKFLOW_CONFIGURATION = {
  nodeKinds: ["approval"],
  assigneeKinds: ["permission_holders", "direct_manager", "department_owner", "position", "employee"],
  approvalModes: ["any_one", "all"],
  separationPolicies: ["auto_pass_if_authorized", "independent_required"],
  allowNodeAddRemove: true,
  allowBypassConditions: true,
  maxNodes: 8,
} as const;

const WORK_TASKS_WORKFLOW_ROUTES = [
  "POST /api/modules/work/tasks/submissions",
  "POST /api/modules/work/tasks/submissions/:id/submit",
  "POST /api/modules/work/tasks/submissions/:id/approve",
] as const;

function workGoalContract(input: {
  key: WorkGoalActionKey; activeEntity: string;
  target: ActionContractMetadata["payload"]["target"]; targetIdKey?: string; statusField?: string;
  commitMode: NonNullable<ActionContractMetadata["persistence"]>["commitMode"]; adapterKey: string;
  surfaceKey?: string; snapshotPath?: string; workflowRole?: "submitter" | "processor" | "observer" | "none";
  editPolicy?: "editable" | "readonly" | "workflowConfigured"; validatorKey: string; commitKey: string;
  nodeKey: string; payloadNotes: string; persistenceNotes: string;
  formNotes: string; domainNotes: string; displayTitleTemplate: string; displaySummaryTemplate: string;
  directRoutes?: readonly string[];
}): ActionContractMetadata {
  const descriptor = getWorkGoalActionDescriptor(input.key);
  const validatorKeys = input.validatorKey.split(" | ");
  const commitKeys = input.commitKey.split(" | ");
  const domain = validatorKeys.length === 1
    ? { validatorKey: validatorKeys[0], commitKey: commitKeys[0], notes: input.domainNotes }
    : {
        bindings: validatorKeys.map((validatorKey, index) => ({
          validatorKey,
          commitKey: commitKeys[index],
        })) as [{ validatorKey: string; commitKey: string }, ...Array<{ validatorKey: string; commitKey: string }>],
        notes: input.domainNotes,
      };
  return {
    key: descriptor.key,
    version: 1,
    kind: "write",
    label: descriptor.label,
    targetKind: descriptor.targetKind,
    resource: WORK_TASKS_RESOURCE,
    payload: {
      cardinality: "single",
      shape: "full_record",
      target: input.target,
      ...(input.targetIdKey ? { targetIdKey: input.targetIdKey } : {}),
      notes: input.payloadNotes,
    },
    persistence: {
      strategy: "approval_payload",
      activeEntity: input.activeEntity,
      draftEntity: "ApprovalRequest",
      supportedPersistenceModes: ["active", "workflowDraft"],
      defaultMode: "workflowDraft",
      ...(input.statusField ? { statusField: input.statusField } : {}),
      commitMode: input.commitMode,
      notes: input.persistenceNotes,
    },
    form: {
      adapterKey: input.adapterKey,
      payloadVersion: 1,
      ...(input.surfaceKey ? { surfaceKey: input.surfaceKey } : {}),
      ...(input.snapshotPath ? { snapshotPath: input.snapshotPath } : {}),
      supportedPersistenceModes: ["active", "workflowDraft"],
      supportedModes: ["direct", "workflow"],
      ...(input.workflowRole ? { workflowRole: input.workflowRole } : {}),
      ...(input.editPolicy ? { editPolicy: input.editPolicy } : {}),
      notes: input.formNotes,
    },
    domain,
    api: {
      directRoutes: input.directRoutes ?? ["POST /api/modules/work/tasks/submissions"],
      workflowRoutes: WORK_TASKS_WORKFLOW_ROUTES,
      envelopeVersion: 1,
    },
    workflow: {
      kind: "configurable",
      defaultExecutionMode: "workflow",
      canDisable: true,
      whenDisabled: "direct_write",
      entrySemantics: "form_finalization",
      statuses: ["draft", "submitted", "committing", "withdrawn", "rejected", "approved", "cancelled", "failed"],
      transitions: ["submit", "withdraw", "cancel", "resubmit", "approve", "reject"],
      mutationPolicy: WORK_TASKS_WORKFLOW_MUTATION,
      routing: { handlerSource: "permission", separationPolicy: "auto_pass_if_authorized", approvalMode: "any_one" },
      defaultDefinition: {
        version: 1,
        nodes: [{
          key: input.nodeKey,
          label: descriptor.label,
          kind: "approval",
          assignee: { kind: "permission_holders", resourceKey: "work.tasks", action: "approve" },
          approvalMode: "any_one",
          separationPolicy: "auto_pass_if_authorized",
          bypassable: true,
        }],
      },
      configuration: WORK_TASKS_WORKFLOW_CONFIGURATION,
      validateOn: ["draft", "submit", "commit"],
      notes: "目标/结果治理动作：新请求读取当前有效 WorkflowPolicy；流程关闭时复用同一校验和提交直接确认，流程开启时由 ApprovalRequest 冻结请求快照。目标/结果申报窗口只约束首次申报，目标修订和结果更正使用各自独立策略；所有动作都只记录业务事实，不迁移 WorkPlan 阶段。",
    },
    display: {
      titleTemplate: input.displayTitleTemplate,
      summaryTemplate: input.displaySummaryTemplate,
      hrefPattern: "/settings/account?tab=inbox",
    },
  };
}

export const WORK_GOAL_ACTION_CONTRACTS = [
  workGoalContract({
    key: "work.tasks.goal.department.objective.submit",
    directRoutes: ["PUT /api/modules/work/tasks/plans/:id/kpi-scorecard"],
    activeEntity: "WorkPlan|WorkReport",
    target: "mixed",
    commitMode: "native_transition",
    adapterKey: "work.tasks.goal.initial",
    surfaceKey: "work.tasks.goalInitial",
    snapshotPath: "latestPayload.data.approvalSnapshot",
    workflowRole: "processor",
    editPolicy: "workflowConfigured",
    validatorKey: "packages/work/server/task-approval-okr.validateObjectivePlanApprovalPayload | packages/work/server/task-approval-reports.validateReportApprovalPayload",
    commitKey: "packages/work/server/task-approval-okr.commitObjectivePlanApproval | packages/work/server/task-approval-reports.commitWorkReportApproval",
    nodeKey: "work-task-goal-department-objective-submit",
    payloadNotes: "尚无目标确认事实时，组织目标首次申报可提交 WorkPlan 目标事实快照或周期目标表快照；reportStage=kr 的周期目标表仍使用本动作。",
    persistenceNotes: "流程数据存在 ApprovalRequest.latestPayload；目标计划通过后记录目标确认事实，不修改 WorkPlan.status 或 okrStage；周期目标表通过后保存正式 WorkReport。",
    formNotes: "目标申报详情按 payload entityType 复用目标计划 renderer 或周期目标表格。",
    domainNotes: "提交和通过均校验目标事实、目标/考核表工作空间、周期和管控 scope；流程开启时，首次申报才校验目标申报窗口。",
    displayTitleTemplate: "部门目标申报：{title}",
    displaySummaryTemplate: "{title}",
  }),
  workGoalContract({
    key: "work.tasks.goal.personal.objective.submit",
    directRoutes: ["PUT /api/modules/work/tasks/plans/:id/kpi-scorecard"],
    activeEntity: "WorkPlan|WorkReport",
    target: "mixed",
    commitMode: "native_transition",
    adapterKey: "work.tasks.goal.initial",
    surfaceKey: "work.tasks.goalInitial",
    snapshotPath: "latestPayload.data.approvalSnapshot",
    workflowRole: "processor",
    editPolicy: "workflowConfigured",
    validatorKey: "packages/work/server/task-approval-okr.validateObjectivePlanApprovalPayload | packages/work/server/task-approval-reports.validateReportApprovalPayload",
    commitKey: "packages/work/server/task-approval-okr.commitObjectivePlanApproval | packages/work/server/task-approval-reports.commitWorkReportApproval",
    nodeKey: "work-task-goal-personal-objective-submit",
    payloadNotes: "尚无目标确认事实时，个人目标首次申报可提交 WorkPlan 目标事实快照或周期目标表快照，审批归属解析到管控部门。",
    persistenceNotes: "流程数据存在 ApprovalRequest.latestPayload；目标计划通过后记录目标确认事实，不修改 WorkPlan.status 或 okrStage；周期目标表通过后保存正式 WorkReport。",
    formNotes: "个人目标申报详情按 payload entityType 复用目标计划 renderer 或周期目标表格。",
    domainNotes: "提交和通过均校验目标事实、个人所属管控部门、目标/考核表周期和审批快照；流程开启时，首次申报才校验目标申报窗口。",
    displayTitleTemplate: "个人目标申报：{title}",
    displaySummaryTemplate: "{title}",
  }),
  workGoalContract({
    key: "work.tasks.goal.department.report.submit",
    directRoutes: ["PUT /api/modules/work/tasks/reports"],
    activeEntity: "WorkReport",
    target: "mixed",
    targetIdKey: "reportId",
    statusField: "status",
    commitMode: "copy_to_active",
    adapterKey: "work.tasks.report",
    validatorKey: "packages/work/server/task-approval-reports.validateReportApprovalPayload",
    commitKey: "packages/work/server/task-approval-reports.commitWorkReportApproval",
    nodeKey: "work-task-goal-department-report-submit",
    payloadNotes: "尚无结果确认事实时，组织结果首次申报提交周期、报告口径和汇报明细。",
    persistenceNotes: "流程数据存在 ApprovalRequest.latestPayload；通过后保存正式 WorkReport 作为结果确认事实，并保留本次请求快照，不修改 WorkPlan 阶段。",
    formNotes: "结果申报审批复用汇报表格 payload。",
    domainNotes: "提交和通过均校验汇报对象、周期、报告口径和工作空间边界；流程开启时，首次申报才校验结果申报窗口。",
    displayTitleTemplate: "部门考核结果：{periodStart}",
    displaySummaryTemplate: "{reportStage} · {periodType}",
  }),
  workGoalContract({
    key: "work.tasks.goal.personal.report.submit",
    directRoutes: ["PUT /api/modules/work/tasks/reports"],
    activeEntity: "WorkReport",
    target: "mixed",
    targetIdKey: "reportId",
    statusField: "status",
    commitMode: "copy_to_active",
    adapterKey: "work.tasks.report",
    validatorKey: "packages/work/server/task-approval-reports.validateReportApprovalPayload",
    commitKey: "packages/work/server/task-approval-reports.commitWorkReportApproval",
    nodeKey: "work-task-goal-personal-report-submit",
    payloadNotes: "尚无结果确认事实时，个人结果首次申报提交周期、报告口径和汇报明细。",
    persistenceNotes: "流程数据存在 ApprovalRequest.latestPayload；通过后保存正式 WorkReport 作为结果确认事实，并保留本次请求快照，不修改 WorkPlan 阶段。",
    formNotes: "个人结果申报审批复用汇报表格 payload。",
    domainNotes: "提交和通过均校验汇报对象、周期、报告口径和工作空间边界；流程开启时，首次申报才校验结果申报窗口。",
    displayTitleTemplate: "个人考核结果：{periodStart}",
    displaySummaryTemplate: "{reportStage} · {periodType}",
  }),
  workGoalContract({
    key: "work.tasks.goal.department.objective.revise",
    activeEntity: "WorkPlan",
    target: "existing_record",
    targetIdKey: "planId",
    statusField: "status",
    commitMode: "apply_patch",
    adapterKey: "work.tasks.revision",
    validatorKey: "packages/work/server/task-approval-adapter.validateRevisionApprovalPayload",
    commitKey: "packages/work/server/task-approval-adapter.commitRevisionApproval",
    nodeKey: "work-task-goal-department-objective-revise",
    payloadNotes: "已有组织目标确认事实时使用本修订 payload，changeTarget=okr_plan。",
    persistenceNotes: "修订草稿存在 ApprovalRequest.latestPayload；通过后写回正式 WorkPlan；既有目标确认事实继续作为动作选择依据，不迁移 WorkPlan.status 或 okrStage。",
    formNotes: "修订表单复用目标计划 UI，并在审批详情展示差异和原因。",
    domainNotes: "新请求读取当前目标修订策略，已有请求使用冻结快照；提交和通过均校验原计划、工作空间、来源边界和项目可见性，且不受首次目标申报窗口约束。",
    displayTitleTemplate: "部门目标修订：{title}",
    displaySummaryTemplate: "{reason}",
  }),
  workGoalContract({
    key: "work.tasks.goal.personal.objective.revise",
    activeEntity: "WorkPlan",
    target: "existing_record",
    targetIdKey: "planId",
    statusField: "status",
    commitMode: "apply_patch",
    adapterKey: "work.tasks.revision",
    validatorKey: "packages/work/server/task-approval-adapter.validateRevisionApprovalPayload",
    commitKey: "packages/work/server/task-approval-adapter.commitRevisionApproval",
    nodeKey: "work-task-goal-personal-objective-revise",
    payloadNotes: "已有个人目标确认事实时使用本修订 payload，changeTarget=okr_plan。",
    persistenceNotes: "修订草稿存在 ApprovalRequest.latestPayload；通过后写回正式 WorkPlan；既有目标确认事实继续作为动作选择依据，不迁移 WorkPlan.status 或 okrStage。",
    formNotes: "个人目标修订表单复用目标计划 UI，并在审批详情展示差异和原因。",
    domainNotes: "新请求读取当前目标修订策略，已有请求使用冻结快照；提交和通过均校验原计划、工作空间、来源边界和项目可见性，且不受首次目标申报窗口约束。",
    displayTitleTemplate: "个人目标修订：{title}",
    displaySummaryTemplate: "{reason}",
  }),
  workGoalContract({
    key: "work.tasks.goal.department.report.correct",
    activeEntity: "WorkReport",
    target: "existing_record",
    targetIdKey: "reportId",
    statusField: "status",
    commitMode: "apply_patch",
    adapterKey: "work.tasks.revision",
    validatorKey: "packages/work/server/task-approval-adapter.validateRevisionApprovalPayload",
    commitKey: "packages/work/server/task-approval-adapter.commitRevisionApproval",
    nodeKey: "work-task-goal-department-report-correct",
    payloadNotes: "已有组织结果确认事实时使用本更正 payload，changeTarget=work_report。",
    persistenceNotes: "更正草稿存在 ApprovalRequest.latestPayload；通过后保存更正后的 WorkReport 结果事实，不迁移 WorkPlan 阶段；不可变 KPI 结果快照由结果快照接口独立保留。",
    formNotes: "考核结果更正表单复用汇报 UI，并在审批详情展示差异和原因。",
    domainNotes: "新请求读取当前结果更正策略，已有请求使用冻结快照；提交和通过均校验原汇报、周期、报告口径和工作空间边界，且不受首次结果申报窗口约束。",
    displayTitleTemplate: "部门考核结果更正：{periodStart}",
    displaySummaryTemplate: "{reason}",
  }),
  workGoalContract({
    key: "work.tasks.goal.personal.report.correct",
    activeEntity: "WorkReport",
    target: "existing_record",
    targetIdKey: "reportId",
    statusField: "status",
    commitMode: "apply_patch",
    adapterKey: "work.tasks.revision",
    validatorKey: "packages/work/server/task-approval-adapter.validateRevisionApprovalPayload",
    commitKey: "packages/work/server/task-approval-adapter.commitRevisionApproval",
    nodeKey: "work-task-goal-personal-report-correct",
    payloadNotes: "已有个人结果确认事实时使用本更正 payload，changeTarget=work_report。",
    persistenceNotes: "更正草稿存在 ApprovalRequest.latestPayload；通过后保存更正后的 WorkReport 结果事实，不迁移 WorkPlan 阶段；不可变 KPI 结果快照由结果快照接口独立保留。",
    formNotes: "个人考核结果更正表单复用汇报 UI，并在审批详情展示差异和原因。",
    domainNotes: "新请求读取当前结果更正策略，已有请求使用冻结快照；提交和通过均校验原汇报、周期、报告口径和工作空间边界，且不受首次结果申报窗口约束。",
    displayTitleTemplate: "个人考核结果更正：{periodStart}",
    displaySummaryTemplate: "{reason}",
  }),
] as const;
