import {
  defineActionContractMetadataList,
  type ActionContractMetadata,
  type ActionMutationDomainBindingReference,
} from "./action-contract";
import {
  registeredActionFacts,
  registeredGovernance,
  registeredImport,
  registeredLifecycle,
  registeredWrite,
} from "./action-contract-registry-helpers";

const d = (validatorKey: string, commitKey: string): ActionMutationDomainBindingReference => ({ validatorKey, commitKey });

const libraryExport: ActionContractMetadata = {
  ...registeredActionFacts("library.basicInfo.document.export"),
  kind: "exchange",
  payload: { cardinality: "single", shape: "full_record", target: "existing_record", targetIdKey: "id" },
  exchange: { direction: "export", transport: "file", result: "file" },
  domain: {
    bindings: [
      { executeKey: "packages/library/server/route-commands.executeDownloadLibraryDocumentCommand" },
      { executeKey: "packages/library/server/route-commands.executeDownloadLibraryDocumentVersionCommand" },
      { executeKey: "packages/library/server/route-commands.executeLibraryPathFileCommand" },
    ],
  },
};

const libraryDocumentSetExport: ActionContractMetadata = {
  ...registeredActionFacts("library.basicInfo.documentSet.export"),
  kind: "exchange",
  payload: {
    cardinality: "batch",
    shape: "full_record",
    target: "new_record",
    batch: { itemKey: "selection", atomicity: "all_or_nothing" },
  },
  exchange: {
    direction: "export",
    transport: "file",
    result: "file",
    contentTypes: ["application/zip"],
    notes: "The command creates an export job; the resulting file is downloaded through the requester-bound export URL.",
  },
  domain: {
    validatorKey: "packages/library/server/route-commands.buildCreateLibraryExportRouteCommand",
    executeKey: "packages/library/server/route-commands.executeCreateLibraryExportCommand",
  },
};

export const SMALL_MODULE_ACTION_CONTRACT_METADATA = defineActionContractMetadataList([
  {
    ...registeredActionFacts("agent.businessApi.mutation.execute"),
    kind: "remote_effect",
    payload: {
      cardinality: "single",
      shape: "full_record",
      target: "new_record",
      notes: "确认时使用 AgentProposal 中冻结的 method、path 和 JSON body；目标必须仍命中受保护的 /api/modules/** business contract。",
    },
    remoteEffect: {
      provider: "Workspace protected business API",
      operation: "execute_registered_mutation",
      localAuditEntity: "AgentProposal",
      outcomeAfterDispatchFailure: "unknown",
      retryPolicy: "reconcile_before_retry",
      notes: "HTTP dispatch 开始后发生异常时，目标业务单元可能已接受写入；AgentProposal 记录不确定失败，禁止自动重试，必须先通过对应业务 API 核对。",
    },
    domain: d(
      "packages/platform/server/agent/business-api-connector.validateAgentBusinessApiMutationProposalPayload",
      "packages/platform/server/agent/business-api-connector.executeAgentBusinessApiMutationProposal",
    ),
  },
  {
    ...registeredActionFacts("docs.editor.template.draft.save"),
    kind: "write",
    resource: {
      resourceKey: "docs.editor",
      moduleKey: "docs",
      scopeTypes: ["personal", "company", "committee", "department"],
      directPermissionAction: "update",
      submitPermissionAction: "submit",
      processPermissionAction: "approve",
    },
    payload: { cardinality: "single", shape: "full_record", target: "existing_record", targetIdKey: "templateId", versionKey: "version" },
    persistence: { strategy: "approval_payload", activeEntity: "DocumentTemplate", draftEntity: "ApprovalRequest", supportedPersistenceModes: ["active", "workflowDraft"], defaultMode: "active", commitMode: "apply_patch" },
    domain: d("packages/platform/server/docs-editor/domain/document-template-validation.buildSaveDraftCommand", "packages/platform/server/docs-editor/service.saveDraft"),
    workflow: {
      kind: "configurable",
      defaultExecutionMode: "direct",
      canDisable: true,
      whenDisabled: "direct_write",
      entrySemantics: "form_finalization",
      statuses: ["draft", "submitted", "withdrawn", "rejected", "approved", "failed"],
      transitions: ["submit", "withdraw", "resubmit", "approve", "reject"],
      mutationPolicy: { handlerCanRevise: false, requestCanWithdraw: true, requestCanRevise: true, requestCanCancel: true, requestCanResubmit: true },
      routing: { handlerSource: "permission", separationPolicy: "auto_pass_if_authorized", approvalMode: "any_one" },
      defaultDefinition: { version: 1, nodes: [{ key: "docs-template-draft-save-approval", label: "模板草稿保存审批", kind: "approval", assignee: { kind: "permission_holders", resourceKey: "docs.editor", action: "approve" }, approvalMode: "any_one", separationPolicy: "auto_pass_if_authorized", bypassable: true }] },
      configuration: { nodeKinds: ["approval"], assigneeKinds: ["permission_holders", "direct_manager", "department_owner", "position", "employee"], approvalModes: ["any_one", "all"], separationPolicies: ["auto_pass_if_authorized", "independent_required"], allowNodeAddRemove: true, allowBypassConditions: true, maxNodes: 8 },
      validateOn: ["draft", "submit", "commit"],
    },
  },
  {
    ...registeredActionFacts("production.qc.batch.review"),
    kind: "workflow",
    payload: { cardinality: "single", shape: "field_patch", target: "existing_record", targetIdKey: "batchId", versionKey: "expectedVersion" },
    persistence: { strategy: "active_table_state", activeEntity: "ProductionQcBatch", supportedPersistenceModes: ["active"], defaultMode: "active", commitMode: "native_transition" },
    domain: d("packages/production/server/qc/route-commands.buildQcBatchApproveReviewCommand", "packages/production/server/qc/route-commands.executeQcBatchPatchCommand"),
    workflow: {
      kind: "native",
      defaultExecutionMode: "native",
      canDisable: false,
      whenDisabled: "unavailable",
      entrySemantics: "domain_transition",
      statuses: ["draft", "submitted", "approved"],
      transitions: ["submit", "approve"],
      mutationPolicy: { handlerCanRevise: false, requestCanWithdraw: false, requestCanRevise: false, requestCanCancel: false, requestCanResubmit: false },
      routing: { handlerSource: "permission", separationPolicy: "independent_required", approvalMode: "any_one" },
      defaultDefinition: { version: 1, nodes: [{ key: "qc-batch-review", label: "QC 批次复核", kind: "review", assignee: { kind: "permission_holders", resourceKey: "production.qc", action: "approve" }, approvalMode: "any_one", separationPolicy: "independent_required", bypassable: false }] },
      configuration: { nodeKinds: ["review"], assigneeKinds: ["permission_holders"], approvalModes: ["any_one"], separationPolicies: ["independent_required"], allowNodeAddRemove: false, allowBypassConditions: false, maxNodes: 1 },
      validateOn: ["submit", "commit"],
    },
  },
  registeredWrite({
    key: "library.basicInfo.directory.create",
    activeEntity: "LibraryDirectory",
    domain: d("packages/library/server/route-commands.buildCreateLibraryDirectoryRouteCommand", "packages/library/server/route-commands.executeCreateLibraryDirectoryCommand"),
    shape: "full_record",
    target: "new_record",
    commitMode: "activate",
  }),
  registeredWrite({
    key: "library.basicInfo.directory.rename",
    activeEntity: "LibraryDirectory",
    domain: d("packages/library/server/route-commands.buildRenameLibraryDirectoryRouteCommand", "packages/library/server/route-commands.executeRenameLibraryDirectoryCommand"),
    targetIdKey: "path",
  }),
  registeredLifecycle({
    key: "library.basicInfo.directory.delete",
    activeEntity: "LibraryDirectory",
    operation: "delete",
    targetIdKey: "path",
    deleteMode: "hard",
    referencePolicy: "domain",
    domain: d("packages/library/server/route-commands.buildDeleteLibraryDirectoryRouteCommand", "packages/library/server/route-commands.executeDeleteLibraryDirectoryCommand"),
  }),
  registeredImport({
    key: "library.basicInfo.document.import",
    activeEntity: "LibraryDocument",
    transport: "file",
    domain: d("packages/library/server/route-commands.buildUploadLibraryDocumentRouteCommand", "packages/library/server/route-commands.executeUploadLibraryDocumentCommand"),
  }),
  registeredWrite({
    key: "library.basicInfo.document.review",
    activeEntity: "LibraryDocument",
    domain: d("packages/library/server/route-commands.buildReviewLibraryDocumentRouteCommand", "packages/library/server/route-commands.executeReviewLibraryDocumentCommand"),
    targetIdKey: "id",
    commitMode: "activate",
  }),
  registeredWrite({
    key: "library.basicInfo.document.metadata.save",
    activeEntity: "LibraryDocument",
    domain: d("packages/library/server/domain/metadata-validation.buildUpdateDocumentMetadataCommand", "packages/library/server/route-commands.executeUpdateLibraryDocumentCommand"),
    targetIdKey: "id",
  }),
  registeredGovernance({
    key: "library.basicInfo.document.confidentiality.configure",
    activeEntity: "LibraryDocument",
    subject: "policy",
    domain: d("packages/library/server/domain/metadata-validation.buildUpdateDocumentMetadataCommand", "packages/library/server/route-commands.executeUpdateLibraryDocumentCommand"),
  }),
  registeredLifecycle({
    key: "library.basicInfo.document.archive",
    activeEntity: "LibraryDocument",
    operation: "archive",
    domain: d("packages/library/server/domain/metadata-validation.buildSetDocumentLifecycleCommand", "packages/library/server/route-commands.executeSetLibraryDocumentLifecycleCommand"),
  }),
  registeredLifecycle({
    key: "library.basicInfo.document.delete",
    activeEntity: "LibraryDocument",
    operation: "delete",
    deleteMode: "hard",
    referencePolicy: "domain",
    domain: d("packages/library/server/route-commands.buildDeleteLibraryDocumentRouteCommand", "packages/library/server/route-commands.executeDeleteLibraryDocumentCommand"),
  }),
  libraryExport,
  libraryDocumentSetExport,
  registeredImport({
    key: "library.basicInfo.documentVersion.import",
    activeEntity: "LibraryDocumentVersion",
    transport: "file",
    domain: d("packages/library/server/route-commands.buildUploadLibraryDocumentVersionCommand", "packages/library/server/route-commands.executeUploadLibraryDocumentVersionCommand"),
  }),
  registeredImport({
    key: "library.basicInfo.generatedDocument.import",
    activeEntity: "LibraryDocument",
    transport: "generated",
    domain: d("packages/library/server/route-commands.buildGenerateLibraryDocumentCommand", "packages/library/server/route-commands.executeGenerateLibraryDocumentCommand"),
  }),
  registeredImport({
    key: "library.basicInfo.scan.import",
    activeEntity: "LibraryDocument",
    transport: "scan",
    atomicity: "best_effort",
    domain: d("packages/library/server/route-commands.buildScanLibraryCommand", "packages/library/server/route-commands.executeScanLibraryCommand"),
  }),
  registeredWrite({
    key: "docs.editor.template.copy",
    activeEntity: "DocumentTemplate",
    domain: d("packages/platform/server/docs-editor/domain/document-template-validation.buildCopyTemplateCommand", "packages/platform/server/docs-editor/service.copyTemplate"),
    shape: "full_record",
    target: "new_record",
    commitMode: "activate",
  }),
  registeredLifecycle({
    key: "docs.editor.template.archive",
    activeEntity: "DocumentTemplate",
    operation: "archive",
    versionKey: "version",
    domain: d("packages/platform/server/docs-editor/domain/document-template-validation.buildTemplateIdCommand", "packages/platform/server/docs-editor/service.archiveTemplate"),
  }),
  registeredLifecycle({
    key: "docs.editor.template.draft.delete",
    activeEntity: "DocumentTemplate",
    operation: "delete",
    versionKey: "version",
    deleteMode: "hard",
    referencePolicy: "domain",
    domain: d("packages/platform/server/docs-editor/domain/document-template-validation.buildTemplateIdCommand", "packages/platform/server/docs-editor/service.deleteDraft"),
  }),
  registeredWrite({
    key: "production.qc.batch.create",
    activeEntity: "ProductionQcBatch",
    strategy: "active_table_state",
    domain: d("packages/production/server/qc/domain/qc-validation.buildCreateQcBatchCommand", "packages/production/server/qc/batches.createQcBatch"),
    shape: "full_record",
    target: "new_record",
    commitMode: "activate",
  }),
  registeredLifecycle({
    key: "production.qc.batch.delete",
    activeEntity: "ProductionQcBatch",
    strategy: "active_table_state",
    operation: "delete",
    targetIdKey: "batchId",
    versionKey: "expectedVersion",
    deleteMode: "hard",
    auditPolicy: "event",
    referencePolicy: "none",
    domain: d("packages/production/server/qc/route-commands.buildDeleteQcBatchRouteCommand", "packages/production/server/qc/route-commands.executeDeleteQcBatchCommand"),
  }),
  registeredWrite({ key: "inventory.operations.document.create", activeEntity: "InventoryDocument", domain: d("packages/inventory/server/route-commands.buildCreateInventoryDocumentRouteCommand", "packages/inventory/server/route-commands.executeCreateInventoryDocumentRouteCommand"), shape: "full_record", target: "new_record", commitMode: "activate" }),
  registeredLifecycle({ key: "inventory.operations.document.post", activeEntity: "InventoryDocument", operation: "custom", domain: d("packages/inventory/server/route-commands.buildInventoryDocumentLifecycleRouteCommand", "packages/inventory/server/route-commands.executeInventoryDocumentLifecycleRouteCommand") }),
  registeredLifecycle({ key: "inventory.operations.document.reverse", activeEntity: "InventoryDocument", operation: "custom", domain: d("packages/inventory/server/route-commands.buildInventoryDocumentLifecycleRouteCommand", "packages/inventory/server/route-commands.executeInventoryDocumentLifecycleRouteCommand") }),
  registeredLifecycle({ key: "inventory.operations.closing.linkVoucher", activeEntity: "InventoryPeriodClose", operation: "close", domain: d("packages/inventory/server/route-commands.buildLinkInventoryVoucherRouteCommand", "packages/inventory/server/route-commands.executeLinkInventoryVoucherRouteCommand") }),
  registeredGovernance({
    key: "capitalSecurities.governance.organization.create",
    activeEntity: "Department",
    subject: "organization",
    scope: "organization",
    domain: d("packages/platform/server/organization-units.buildGovernanceOrganizationCreateCommand", "packages/platform/server/organization-units.createGovernanceOrganization"),
  }),
  registeredGovernance({
    key: "capitalSecurities.governance.organization.save",
    activeEntity: "Department",
    subject: "organization",
    scope: "organization",
    domain: d("packages/platform/server/organization-units.buildGovernanceOrganizationUpdateCommand", "packages/platform/server/organization-units.updateGovernanceOrganization"),
  }),
  registeredWrite({
    key: "capitalSecurities.governance.company.create",
    activeEntity: "Company",
    domain: d("packages/capital-securities/server/domain/company-governance-validation.buildCompanyCreateCommand", "packages/capital-securities/server/company-governance.createCompany"),
    shape: "full_record",
    target: "new_record",
    commitMode: "activate",
  }),
  registeredWrite({
    key: "capitalSecurities.governance.company.update",
    activeEntity: "Company",
    domain: d("packages/capital-securities/server/domain/company-governance-validation.buildCompanyUpdateCommand", "packages/capital-securities/server/company-governance.updateCompany"),
    shape: "full_record",
    target: "existing_record",
    targetIdKey: "id",
  }),
  registeredLifecycle({
    key: "capitalSecurities.governance.ownershipProjection.rebuild",
    activeEntity: "OwnershipInterest",
    operation: "custom",
    domain: d(
      "packages/capital-securities/server/domain/ownership-projection-rebuild.buildOwnershipProjectionRebuildCommand",
      "packages/capital-securities/server/ownership-projection.rebuildOwnershipProjection",
    ),
  }),
  registeredWrite({
    key: "capitalSecurities.governance.consolidationScope.update",
    activeEntity: "ShareCapitalEvent",
    domain: d(
      "packages/capital-securities/server/domain/consolidation-inclusion-validation.buildSetConsolidationInclusionCommand",
      "packages/capital-securities/server/consolidation-inclusion.setConsolidationInclusion",
    ),
    shape: "full_record",
    target: "new_record",
    commitMode: "native_transition",
  }),
]);
