import type { ApiMethod } from "./api-contract-types";
import { OPERATIONAL_BUSINESS_ACTION_REGISTRATIONS } from "./business-action-registry-operational";
import { WORK_GOAL_ACTION_DESCRIPTORS } from "./work-goal-action-descriptors";

const PERMISSION_ONLY = { eligibility: "permission_only" } as const;
const OPTIONAL_APPROVAL_AUTO = {
  eligibility: "workflow_optional",
  flowType: "approval",
  separationPolicy: "auto_pass_if_authorized",
  submitPermissionAction: "submit",
  processPermissionAction: "approve",
} as const;
const ASSESSMENT_WORKFLOW = { workflowCategoryKey: "assessment" } as const;

const LIBRARY_BASIC_INFO = {
  moduleKey: "library",
  resourceKey: "library.basicInfo",
  originHrefPattern: "/library/basic-info",
} as const;

const FINANCE_LEDGER = {
  moduleKey: "finance",
  resourceKey: "finance.ledger",
  originHrefPattern: "/finance/ledger",
} as const;

const FINANCE_BUDGET = {
  moduleKey: "finance",
  resourceKey: "finance.budget",
  originHrefPattern: "/finance/budget",
} as const;

const FINANCE_COST = {
  moduleKey: "finance",
  resourceKey: "finance.cost",
  originHrefPattern: "/finance/cost",
} as const;

const FINANCE_IMPORT = {
  moduleKey: "finance",
  resourceKey: "finance.import",
  originHrefPattern: "/finance/import",
} as const;

const INVENTORY_OPERATIONS = {
  moduleKey: "inventory",
  resourceKey: "inventory.operations",
  originHrefPattern: "/inventory/operations",
} as const;

const HR_PERFORMANCE = {
  moduleKey: "hr",
  resourceKey: "hr.performance",
  originHrefPattern: "/work/performance",
} as const;

const CAPITAL_SECURITIES_GOVERNANCE = {
  moduleKey: "capitalSecurities",
  resourceKey: "capitalSecurities.governance",
  originHrefPattern: "/capital-securities/governance",
} as const;

const STANDARD_SPACE_SCOPES = ["personal", "department", "committee", "company"] as const;

const WORK_PROJECTS = {
  moduleKey: "work",
  resourceKey: "work.projects",
  scopeTypes: STANDARD_SPACE_SCOPES,
  originHrefPattern: "/work/project",
} as const;

const WORK_TASKS = {
  moduleKey: "work",
  resourceKey: "work.tasks",
  scopeTypes: STANDARD_SPACE_SCOPES,
  originHrefPattern: "/work/me",
} as const;

function route(method: ApiMethod, path: string, notes?: string) {
  return notes ? { method, path, notes } : { method, path };
}

const WORK_OKR_WORKFLOW_ACTIONS = WORK_GOAL_ACTION_DESCRIPTORS.map((descriptor) => ({
  ...WORK_TASKS,
  ...OPTIONAL_APPROVAL_AUTO,
  ...ASSESSMENT_WORKFLOW,
  ...descriptor,
  directPermissionAction: "update" as const,
}));

export const ADDITIONAL_BUSINESS_ACTION_REGISTRATIONS = [
  ...OPERATIONAL_BUSINESS_ACTION_REGISTRATIONS,
  {
    ...HR_PERFORMANCE,
    eligibility: "workflow_optional",
    flowType: "approval",
    separationPolicy: "auto_pass_if_authorized",
    submitPermissionAction: "submit",
    processPermissionAction: "approve",
    workflowCategoryKey: "assessment",
    key: "hr.performance.review.evaluate",
    label: "发起绩效评审",
    writeKind: "submit",
    targetKind: "HrPerformanceReview",
    apiRoutes: [
      route("POST", "/api/modules/hr/performance/submissions"),
      route("PUT", "/api/modules/hr/performance/submissions/:id"),
      route("POST", "/api/modules/hr/performance/submissions/:id/submit"),
      route("POST", "/api/modules/hr/performance/submissions/:id/approve"),
      route("POST", "/api/modules/hr/performance/submissions/:id/reject"),
    ],
    notes: "员工自评、直属上级评分、HR 最终评分共用 ApprovalRequest，最终通过时写入 HR-owned HrPerformanceReview。",
  },
  ...WORK_OKR_WORKFLOW_ACTIONS,
  {
    ...WORK_TASKS,
    eligibility: "workflow_optional",
    flowType: "approval",
    separationPolicy: "auto_pass_if_authorized",
    directPermissionAction: "update",
    submitPermissionAction: "submit",
    processPermissionAction: "approve",
    workflowCategoryKey: "collaboration",
    key: "work.tasks.collaboration.submit",
    label: "提交部门协作",
    writeKind: "submit",
    targetKind: "DepartmentCollaboration",
    settingsSortOrder: 501,
    apiRoutes: [
      route("POST", "/api/modules/work/tasks/collaborations"),
      route("PUT", "/api/modules/work/tasks/collaborations/:id"),
    ],
    notes: "默认零审批节点，提交后立即写入；管理员可配置审批节点或关闭流程后按 update 权限直接写入。",
  },
  {
    ...WORK_TASKS,
    ...PERMISSION_ONLY,
    key: "work.tasks.collaboration.respond",
    label: "响应部门协作",
    writeKind: "update",
    targetKind: "DepartmentCollaborationDepartment",
    directPermissionAction: "update",
    apiRoutes: [route("POST", "/api/modules/work/tasks/collaborations/:id/respond")],
    notes: "赋能部门接受或拒绝固定协作通道；响应事实由 DepartmentCollaborationDepartment 保存。",
  },
  {
    ...WORK_TASKS,
    ...OPTIONAL_APPROVAL_AUTO,
    ...ASSESSMENT_WORKFLOW,
    key: "work.tasks.objective_plan.save",
    label: "提交目标审查",
    writeKind: "save",
    targetKind: "WorkPlan",
    directPermissionAction: "update",
    settingsVisibility: "runtime_only",
    apiRoutes: [
      route("POST", "/api/modules/work/tasks/submissions"),
      route("POST", "/api/modules/work/tasks/submissions/:id/submit"),
    ],
    notes: "Legacy mixed objective approval runtime key. New target settings use department/personal objective submit action keys.",
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.project.create",
    label: "创建项目",
    writeKind: "create",
    targetKind: "Project",
    directPermissionAction: "create",
    apiRoutes: [route("POST", "/api/modules/work/projects")],
    notes: "Project writes are registered for visibility; no project workflow adapter is wired yet.",
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.project.update",
    label: "更新项目",
    writeKind: "update",
    targetKind: "Project",
    directPermissionAction: "update",
    apiRoutes: [route("PUT", "/api/modules/work/projects/:id")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.project.delete",
    label: "删除项目",
    writeKind: "delete",
    targetKind: "Project",
    directPermissionAction: "delete",
    apiRoutes: [route("DELETE", "/api/modules/work/projects/:id")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.member.create",
    label: "添加项目成员",
    writeKind: "create",
    targetKind: "EmployeeProject",
    directPermissionAction: "create",
    apiRoutes: [route("POST", "/api/modules/work/projects/members")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.member.update",
    label: "更新项目成员",
    writeKind: "update",
    targetKind: "EmployeeProject",
    directPermissionAction: "update",
    apiRoutes: [route("PUT", "/api/modules/work/projects/members/:id")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.member.delete",
    label: "删除项目成员",
    writeKind: "delete",
    targetKind: "EmployeeProject",
    directPermissionAction: "delete",
    apiRoutes: [route("DELETE", "/api/modules/work/projects/members/:id")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.phase.create",
    label: "创建项目阶段",
    writeKind: "create",
    targetKind: "ProjectPlanPhase",
    directPermissionAction: "create",
    apiRoutes: [route("POST", "/api/modules/work/projects/:id/plan-phases")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.phase.update",
    label: "更新项目阶段",
    writeKind: "update",
    targetKind: "ProjectPlanPhase",
    directPermissionAction: "update",
    apiRoutes: [route("PUT", "/api/modules/work/projects/:id/plan-phases/:phaseId")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.phase.delete",
    label: "删除项目阶段",
    writeKind: "delete",
    targetKind: "ProjectPlanPhase",
    directPermissionAction: "delete",
    apiRoutes: [route("DELETE", "/api/modules/work/projects/:id/plan-phases/:phaseId")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.planGantt.save",
    label: "保存项目甘特",
    writeKind: "save",
    targetKind: "ProjectPlanGantt",
    directPermissionAction: "update",
    apiRoutes: [
      route("PUT", "/api/modules/work/projects/:id/plan-gantt"),
      route("PUT", "/api/modules/work/projects/:id/plan-dependencies"),
    ],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.baseline.create",
    label: "创建项目计划基线",
    writeKind: "create",
    targetKind: "ProjectPlanBaseline",
    directPermissionAction: "create",
    apiRoutes: [route("POST", "/api/modules/work/projects/:id/plan-baselines")],
  },
  {
    ...WORK_PROJECTS,
    ...PERMISSION_ONLY,
    key: "work.projects.baseline.activate",
    label: "启用项目计划基线",
    writeKind: "revise",
    targetKind: "ProjectPlanBaseline",
    directPermissionAction: "revise",
    apiRoutes: [route("POST", "/api/modules/work/projects/:id/plan-baselines/:baselineId/activate")],
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.directory.create",
    label: "新建资料文件夹",
    writeKind: "create",
    targetKind: "LibraryDirectory",
    directPermissionAction: "configure",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/directories")],
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.directory.rename",
    label: "重命名资料文件夹",
    writeKind: "revise",
    targetKind: "LibraryDirectory",
    directPermissionAction: "configure",
    apiRoutes: [route("PATCH", "/api/modules/library/basic-info/directories")],
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.directory.delete",
    label: "删除资料文件夹",
    writeKind: "delete",
    targetKind: "LibraryDirectory",
    directPermissionAction: "configure",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/directories/delete")],
    notes: "Only an empty leaf logical directory can be deleted.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.import",
    label: "上传资料入库",
    writeKind: "import",
    targetKind: "LibraryDocument",
    directPermissionAction: "import",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/documents")],
    notes: "Creates a pending LibraryDocument and immutable V1, then runs the existing Markdown and PDF preview processors before human review.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.review",
    label: "确认资料入库",
    writeKind: "approve",
    targetKind: "LibraryDocumentReview",
    directPermissionAction: "import",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/documents/:id/review")],
    notes: "The importer explicitly confirms metadata, folder and tags after derived artifacts have been attempted.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.metadata.save",
    label: "保存资料元数据",
    writeKind: "save",
    targetKind: "LibraryDocumentMetadata",
    directPermissionAction: "update",
    apiRoutes: [route("PATCH", "/api/modules/library/basic-info/documents/:id", "Ordinary title/summary/tag/folder metadata fields require update.")],
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.archive",
    label: "归档资料文件",
    writeKind: "archive",
    targetKind: "LibraryDocument",
    directPermissionAction: "archive",
    apiRoutes: [route("DELETE", "/api/modules/library/basic-info/documents/:id")],
    notes: "The lifecycle command owns archive/restore state transitions; metadata PATCH cannot write status.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.delete",
    label: "永久删除资料文件",
    writeKind: "delete",
    targetKind: "LibraryDocument",
    directPermissionAction: "configure",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/documents/:id/delete")],
    notes: "Permanent deletion is separate from archive, rejects evaluation-evidence references, and removes only document-owned runtime storage.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.confidentiality.configure",
    label: "调整资料保密等级",
    writeKind: "save",
    targetKind: "LibraryDocumentConfidentiality",
    directPermissionAction: "configure",
    apiRoutes: [route("PATCH", "/api/modules/library/basic-info/documents/:id", "confidentialityLevel changes require configure.")],
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.scan.import",
    label: "扫描资料入库",
    writeKind: "import",
    targetKind: "LibraryDocumentScan",
    directPermissionAction: "import",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/scan")],
    notes: "Scan reconciles files into LibraryDocument rows and versions; no page button is exposed in the current UI.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.generatedDocument.import",
    label: "生成资料入库",
    writeKind: "import",
    targetKind: "GeneratedLibraryDocument",
    directPermissionAction: "import",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/generated-sources/:key/generate")],
    notes: "Generated documents use the source default confidentiality level; overriding it is a field-level configure action checked by the library command builder.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.documentVersion.import",
    label: "上传资料新版本",
    writeKind: "import",
    targetKind: "LibraryDocumentVersion",
    directPermissionAction: "import",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/documents/:id/versions")],
    notes: "Each upload creates a new immutable binary version; metadata-only edits do not use this action.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.documentSet.export",
    label: "生成资料集合包",
    writeKind: "export",
    targetKind: "LibraryExportJob",
    directPermissionAction: "export",
    apiRoutes: [route("POST", "/api/modules/library/basic-info/exports")],
    notes: "Selection is frozen to immutable versionUid values and permission/confidentiality are checked at creation, worker execution and download.",
  },
  {
    ...LIBRARY_BASIC_INFO,
    ...PERMISSION_ONLY,
    key: "library.basicInfo.document.export",
    label: "下载资料文件",
    writeKind: "export",
    targetKind: "LibraryDocumentFile",
    directPermissionAction: "export",
    apiRoutes: [
      route("GET", "/api/modules/library/basic-info/documents/:id/download"),
      route("GET", "/api/modules/library/basic-info/documents/:id/versions/:versionId/download"),
      route("GET", "/api/modules/library/basic-info/:*"),
    ],
    notes: "GET export/download routes are permission-only and stay outside write workflow.",
  },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.account.create", label: "创建会计科目", writeKind: "create", targetKind: "FinanceAccount", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/finance/ledger/accounts")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.account.update", label: "更新会计科目", writeKind: "update", targetKind: "FinanceAccount", directPermissionAction: "update", apiRoutes: [route("PUT", "/api/modules/finance/ledger/accounts/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.account.delete", label: "删除会计科目", writeKind: "delete", targetKind: "FinanceAccount", directPermissionAction: "delete", apiRoutes: [route("DELETE", "/api/modules/finance/ledger/accounts/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.voucher.create", label: "创建凭证", writeKind: "create", targetKind: "FinanceVoucher", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/finance/ledger/vouchers")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.voucher.update", label: "更新凭证", writeKind: "update", targetKind: "FinanceVoucher", directPermissionAction: "update", apiRoutes: [route("PUT", "/api/modules/finance/ledger/vouchers/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.voucher.delete", label: "删除凭证", writeKind: "delete", targetKind: "FinanceVoucher", directPermissionAction: "delete", apiRoutes: [route("DELETE", "/api/modules/finance/ledger/vouchers/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.period.create", label: "创建会计期间", writeKind: "create", targetKind: "FinancePeriod", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/finance/ledger/periods")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.period.update", label: "更新会计期间", writeKind: "update", targetKind: "FinancePeriod", directPermissionAction: "update", apiRoutes: [route("PUT", "/api/modules/finance/ledger/periods/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.period.delete", label: "删除会计期间", writeKind: "delete", targetKind: "FinancePeriod", directPermissionAction: "delete", apiRoutes: [route("DELETE", "/api/modules/finance/ledger/periods/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.defaultBook.create", label: "初始化默认账套", writeKind: "create", targetKind: "FinanceLedgerDefaultBook", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/finance/ledger/init")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.balance.revise", label: "重算科目余额", writeKind: "update", targetKind: "FinanceAccountBalance", directPermissionAction: "revise", apiRoutes: [route("POST", "/api/modules/finance/ledger/balances")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.reclassRule.save", label: "保存重分类规则", writeKind: "save", targetKind: "FinanceReclassRule", directPermissionAction: "revise", apiRoutes: [route("PUT", "/api/modules/finance/ledger/reclass-rules")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.reclassAdjustment.save", label: "保存重分类调整", writeKind: "save", targetKind: "FinanceBalanceReclassAdjustment", directPermissionAction: "revise", apiRoutes: [route("PUT", "/api/modules/finance/ledger/reclass-adjustments")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.reclassResult.generate", label: "生成重分类结果", writeKind: "update", targetKind: "ReclassResult", directPermissionAction: "revise", apiRoutes: [route("POST", "/api/modules/finance/ledger/reclass-results")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.reclassResult.adjust", label: "调整重分类结果", writeKind: "update", targetKind: "ReclassResult", directPermissionAction: "revise", apiRoutes: [route("PATCH", "/api/modules/finance/ledger/reclass-results/:id")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.asset.create", label: "创建资产卡片", writeKind: "create", targetKind: "FinanceAssetCard", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/finance/ledger/assets")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.assetAdjustment.create", label: "补录折旧摊销调整", writeKind: "revise", targetKind: "FinanceAssetAdjustment", directPermissionAction: "revise", apiRoutes: [route("POST", "/api/modules/finance/ledger/asset-adjustments")] },
  { ...FINANCE_LEDGER, ...PERMISSION_ONLY, key: "finance.ledger.assetPeriod.recalculate", label: "重算折旧摊销期间", writeKind: "revise", targetKind: "FinanceAssetPeriodEntry", directPermissionAction: "revise", apiRoutes: [route("POST", "/api/modules/finance/ledger/asset-periods/recalculate")] },
  { ...FINANCE_BUDGET, ...PERMISSION_ONLY, key: "finance.budget.import", label: "导入预算数据", writeKind: "import", targetKind: "FinanceBudgetImport", directPermissionAction: "import", apiRoutes: [route("POST", "/api/modules/finance/budget")] },
  { ...FINANCE_BUDGET, ...PERMISSION_ONLY, key: "finance.budget.version.create", label: "创建预算版本", writeKind: "create", targetKind: "BudgetVersion", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/finance/budget/versions")] },
  { ...FINANCE_BUDGET, ...PERMISSION_ONLY, key: "finance.budget.version.activate", label: "启用预算版本", writeKind: "approve", targetKind: "BudgetVersion", directPermissionAction: "approve", apiRoutes: [route("POST", "/api/modules/finance/budget/versions/:id/activate")] },
  { ...FINANCE_COST, ...PERMISSION_ONLY, key: "finance.cost.import.delete", label: "删除成本导入批次", writeKind: "delete", targetKind: "FinanceCostImport", directPermissionAction: "delete", apiRoutes: [route("DELETE", "/api/modules/finance/cost/imports/:id")] },
  { ...FINANCE_IMPORT, ...PERMISSION_ONLY, key: "finance.import.confirm", label: "确认财务导入", writeKind: "import", targetKind: "FinanceImport", directPermissionAction: "import", apiRoutes: [route("POST", "/api/modules/finance/import/confirm")] },
  { ...INVENTORY_OPERATIONS, ...PERMISSION_ONLY, key: "inventory.operations.item.create", label: "创建物料卡片", writeKind: "create", targetKind: "InventoryItem", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/inventory/operations/items")] },
  { ...INVENTORY_OPERATIONS, ...PERMISSION_ONLY, key: "inventory.operations.document.create", label: "创建存货单据", writeKind: "create", targetKind: "InventoryDocument", directPermissionAction: "create", apiRoutes: [route("POST", "/api/modules/inventory/operations/documents")] },
  { ...INVENTORY_OPERATIONS, ...PERMISSION_ONLY, key: "inventory.operations.document.post", label: "过账存货单据", writeKind: "update", targetKind: "InventoryDocument", directPermissionAction: "update", apiRoutes: [route("POST", "/api/modules/inventory/operations/documents/:id/post")] },
  { ...INVENTORY_OPERATIONS, ...PERMISSION_ONLY, key: "inventory.operations.document.reverse", label: "冲销存货单据", writeKind: "reverse", targetKind: "InventoryDocument", directPermissionAction: "reverse", apiRoutes: [route("POST", "/api/modules/inventory/operations/documents/:id/reverse")] },
  { ...INVENTORY_OPERATIONS, ...PERMISSION_ONLY, key: "inventory.operations.closing.linkVoucher", label: "关联存货结转凭证", writeKind: "update", targetKind: "InventoryPeriodClose", directPermissionAction: "lock", apiRoutes: [route("POST", "/api/modules/inventory/operations/closing/link-voucher")] },
  {
    ...CAPITAL_SECURITIES_GOVERNANCE,
    ...PERMISSION_ONLY,
    key: "capitalSecurities.governance.organization.create",
    label: "新建治理组织",
    writeKind: "create",
    targetKind: "GovernanceOrganization",
    directPermissionAction: "create",
    apiRoutes: [route("POST", "/api/modules/capitalSecurities/governance/organizations")],
    notes: "Governance organization writes are in-place G-line Department mutations; no workflow adapter is wired.",
  },
  {
    ...CAPITAL_SECURITIES_GOVERNANCE,
    ...PERMISSION_ONLY,
    key: "capitalSecurities.governance.organization.save",
    label: "保存治理组织",
    writeKind: "save",
    targetKind: "GovernanceOrganization",
    directPermissionAction: "update",
    apiRoutes: [route("PUT", "/api/modules/capitalSecurities/governance/organizations")],
    notes: "Governance organization edits are direct saves on the selected organization detail panel.",
  },
] as const;
