// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createCompatibilityProxyHandler } from "@workspace/platform/server/api";

/** @deprecated Use the Library-owned deploy-unit endpoint. */
export const GET = createCompatibilityProxyHandler(
  "/api/modules/library/integrations/onlyoffice/documents",
  { sourcePathPrefix: "/api/integrations/onlyoffice/library-documents" },
);
