// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  getCostOperationalAnalysisRuntime,
  operationalAnalysisTemplateRuntimeInputSchema,
  operationalAnalysisTemplateRuntimeParamsSchema,
  operationalAnalysisTemplateRuntimeQuerySchema,
  runWorkspaceSourcesOperationalAnalysisTemplateRuntime,
} from "@workspace/finance/server/cost";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";
import { registerFinanceWorkSpaceAccessProvider } from "@workspace/finance/server/cost/work-space-access-provider";

registerFinanceWorkSpaceAccessProvider();

export const GET = createCommandRoute({
  paramsSchema: operationalAnalysisTemplateRuntimeParamsSchema,
  paramsError: "经营分析模板参数无效",
  querySchema: operationalAnalysisTemplateRuntimeQuerySchema,
  queryError: "经营分析筛选参数无效",
  buildCommand: ({ params, query, user }) => okCommand({
    userId: user.userId,
    scopeType: params.targetType,
    scopeId: params.targetId,
    templateId: params.templateId,
    filters: query,
  }),
  action: ({ userId, scopeType, scopeId, templateId, filters }) => getCostOperationalAnalysisRuntime(
    userId,
    { scopeType, scopeId },
    templateId,
    filters,
  ),
});

export const POST = createCommandRoute({
  paramsSchema: operationalAnalysisTemplateRuntimeParamsSchema,
  paramsError: "经营分析模板参数无效",
  bodySchema: operationalAnalysisTemplateRuntimeInputSchema,
  bodyError: "经营分析运行参数无效",
  buildCommand: ({ params, body, user, request }) => okCommand({
    userId: user.userId,
    scopeType: params.targetType,
    scopeId: params.targetId,
    templateId: params.templateId,
    revision: body.revision,
    filterValues: body.filterValues,
    viaApiKey: Boolean(request.headers.get("x-api-key")?.trim()),
  }),
  action: ({ userId, scopeType, scopeId, templateId, revision, filterValues, viaApiKey }, { request }) => (
    runWorkspaceSourcesOperationalAnalysisTemplateRuntime({
      userId,
      scope: { scopeType, scopeId },
      templateId,
      revision,
      filterValues,
      viaApiKey,
      signal: request.signal,
    })
  ),
});
