// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildSaveConsolidationControlDecisionRouteCommand,
  executeSaveConsolidationControlDecisionRouteCommand,
} from "@workspace/finance/server/statements/consolidation-route-commands";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const paramsSchema = z.object({ batchId: z.coerce.number().int().positive() });
const decisionTextSchema = z.object({
  expectedRevision: z.number().int().positive(),
  conclusion: z.string().trim().min(1).max(2000),
  evidence: z.string().trim().min(1).max(4000),
});

const controlDecisionSchema = z.discriminatedUnion("mode", [
  z.object({
    expectedRevision: z.number().int().positive(),
    mode: z.literal("setAll"),
    decision: z.enum(["completed", "requiresReview"]),
  }),
  decisionTextSchema.extend({
    mode: z.literal("notApplicable"),
    controlKey: z.enum([
    "elimination:investmentEquity",
    "elimination:nonControllingInterest",
    "elimination:intercompanyBalance",
    ]),
  }),
]);

export const PUT = createCommandRoute({
  paramsSchema,
  bodySchema: controlDecisionSchema,
  paramsError: "合并批次 ID 无效",
  bodyError: "合并控制结论参数无效",
  buildCommand: ({ params, body, user }) => buildSaveConsolidationControlDecisionRouteCommand(
    params.batchId,
    body,
    user.userId,
  ),
  action: executeSaveConsolidationControlDecisionRouteCommand,
});
