export type ActionGlyphIconKind =
  | "add"
  | "send"
  | "stop"
  | "edit"
  | "check"
  | "double-check"
  | "verified"
  | "cancel"
  | "x"
  | "copy"
  | "save"
  | "delete"
  | "delete-bin"
  | "delete-minus"
  | "view"
  | "eye-off"
  | "search"
  | "filter"
  | "refresh"
  | "reset"
  | "restore"
  | "link"
  | "unlink"
  | "settings"
  | "reclass"
  | "generate"
  | "print"
  | "lock"
  | "unlock"
  | "permission-organization"
  | "permission-derived"
  | "sort"
  | "more"
  | "download"
  | "upload"
  | "archive"
  | "list"
  | "history"
  | "panel-open"
  | "panel-close";

export type ActionGlyphRenderProps = {
  kind: ActionGlyphIconKind;
  className?: string;
};
