import type { CoreUiComponentRegistration } from "./component-registry-types";

export const foundation_registry_entries = [
  {
    name: "ActionGlyph",
    category: "common",
    subcategory: "common.action",
    description: "通用动作图标",
    example: "新增 glyph 时进入 ACTION_GLYPH_KINDS 和 ACTION_GLYPH_GROUPS，并在 ACTION_GLYPH_ORDER 写入 icon / group / subgroup / order。",
  },
  {
    name: "ACTION_GLYPH_KINDS",
    category: "common",
    subcategory: "common.foundation",
    description: "动作图标种类集合",
    example: "ActionGlyph 支持的 kind 闭包集合。",
  },
  {
    name: "ACTION_GLYPH_ORDER",
    category: "common",
    subcategory: "common.foundation",
    description: "动作图标排序配置",
    example: "定义各图标在 Toolbar 动作组中的出现顺序。",
  },
  {
    name: "ACTION_GLYPH_GROUPS",
    category: "common",
    subcategory: "common.foundation",
    description: "动作图标语义分组",
    example: "将图标按 create / edit / delete 等业务语义分组。",
  },
  {
    name: "ACTION_GLYPH_TOOLBAR_GROUPS",
    category: "common",
    subcategory: "common.foundation",
    description: "工具栏动作分组配置",
    example: "将图标分组映射到 Toolbar 的 primary / browse / extended 区域。",
  },
  {
    name: "getFieldInputClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段输入样式",
    example: "业务字段必须自渲染 input 时复用统一高度、边框和焦点态。",
  },
  {
    name: "getFieldShellClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段壳样式",
    example: "FieldShell / FieldInputShell 统一生成字段高度、边框、圆角、padding 和焦点环。",
  },
  {
    name: "getFieldGridCellClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格单元容器样式",
    example: "字段网格单元由 main row 与可选 helper row 组成，不直接写格子样式。",
  },
  {
    name: "getFieldGridMainRowClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格主行样式",
    example: "固定 label + value 行高，避免同行其它单元因 helper 错位。",
  },
  {
    name: "getFieldGridHelperRowClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格辅助行样式",
    example: "短提示文案嵌入 helper row，不影响 main row 行高。",
  },
  {
    name: "getFieldGridLabelClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格标签样式",
    example: "详情页字段标签以统一字号、字重和颜色展示。",
  },
  {
    name: "getFieldGridValueClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格值区样式",
    example: "详情页字段值和输入控件都落入同一值区样式。",
  },
  {
    name: "getFieldGroupTitleClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段分组标题样式",
    example: "员工资料中“身份”“联系与账号”等分组标题保持一致。",
  },
  {
    name: "getReadOnlyFieldClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "只读字段样式",
    example: "员工编码或系统计算值只读展示时保持表单视觉一致。",
  },
  {
    name: "getFieldValueClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段值文本样式",
    example: "ReadOnlyField variant='plain' 或纯展示值时使用统一字号、字重和颜色。",
  },
  {
    name: "getTagInputShellClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "标签输入外壳样式",
    example: "别名、标签或关键词输入区需要多个 chip 时复用容器样式。",
  },
  {
    name: "getTagInlineInputClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "标签内联输入样式",
    example: "员工别名标签末尾继续输入新别名时复用统一内联输入样式。",
  },
  {
    name: "getTagPillClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "标签项样式",
    example: "展示“重点客户”“GMP”这类可删除标签 chip。",
  },
  {
    name: "FIELD_CONTROL_HEIGHT",
    category: "common",
    subcategory: "common.foundation",
    description: "字段控件默认高度 token",
    example: "字段组件默认高度由 Core token 统一，不在业务侧手写 h-*。",
  },
  {
    name: "FIELD_CONTROL_PADDING_X",
    category: "common",
    subcategory: "common.foundation",
    description: "字段控件默认水平 padding token",
    example: "字段组件默认水平间距由 Core token 统一。",
  },
  {
    name: "FIELD_CONTROL_TEXT",
    category: "common",
    subcategory: "common.foundation",
    description: "字段控件默认字号 token",
    example: "输入、只读、选择控件使用同一字号 token。",
  },
  {
    name: "FIELD_LABEL_TEXT",
    category: "common",
    subcategory: "common.foundation",
    description: "字段标签默认文本 token",
    example: "字段标签统一字号、字重和颜色。",
  },
  {
    name: "FIELD_SHELL_CLASS",
    category: "common",
    subcategory: "common.foundation",
    description: "默认字段壳 class token",
    example: "单行字段壳使用 Core 默认样式。",
    composes: ["getFieldShellClassName"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
