import type { CoreUiComponentRegistration } from "./component-registry-types";

export const foundation_registry_entries = [
  {
    name: "ActionGlyph",
    category: "common",
    subcategory: "common.action",
    description: "通用动作图标",
  },
  {
    name: "ACTION_GLYPH_KINDS",
    category: "common",
    subcategory: "common.foundation",
    description: "动作图标种类集合",
  },
  {
    name: "ACTION_GLYPH_ORDER",
    category: "common",
    subcategory: "common.foundation",
    description: "动作图标排序配置",
  },
  {
    name: "ACTION_GLYPH_GROUPS",
    category: "common",
    subcategory: "common.foundation",
    description: "动作图标语义分组",
  },
  {
    name: "ACTION_GLYPH_TOOLBAR_GROUPS",
    category: "common",
    subcategory: "common.foundation",
    description: "工具栏动作分组配置",
  },
  {
    name: "getFieldInputClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段输入样式",
  },
  {
    name: "getFieldShellClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段壳样式",
  },
  {
    name: "getFieldGridCellClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格单元容器样式",
  },
  {
    name: "getFieldGridMainRowClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格主行样式",
  },
  {
    name: "getFieldGridHelperRowClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格辅助行样式",
  },
  {
    name: "getFieldGridLabelClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格标签样式",
  },
  {
    name: "getFieldGridValueClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段网格值区样式",
  },
  {
    name: "getFieldGroupTitleClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段分组标题样式",
  },
  {
    name: "getReadOnlyFieldClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "只读字段样式",
  },
  {
    name: "getFieldValueClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "字段值文本样式",
  },
  {
    name: "getTagInputShellClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "标签输入外壳样式",
  },
  {
    name: "getTagInlineInputClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "标签内联输入样式",
  },
  {
    name: "getTagPillClassName",
    category: "common",
    subcategory: "common.foundation",
    description: "标签项样式",
  },
  {
    name: "FIELD_CONTROL_HEIGHT",
    category: "common",
    subcategory: "common.foundation",
    description: "字段控件默认高度 token",
  },
  {
    name: "FIELD_CONTROL_PADDING_X",
    category: "common",
    subcategory: "common.foundation",
    description: "字段控件默认水平 padding token",
  },
  {
    name: "FIELD_CONTROL_TEXT",
    category: "common",
    subcategory: "common.foundation",
    description: "字段控件默认字号 token",
  },
  {
    name: "FIELD_LABEL_TEXT",
    category: "common",
    subcategory: "common.foundation",
    description: "字段标签默认文本 token",
  },
  {
    name: "FIELD_SHELL_CLASS",
    category: "common",
    subcategory: "common.foundation",
    description: "默认字段壳 class token",
    composes: ["getFieldShellClassName"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
