import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "NavigationSurface",
    category: "common",
    subcategory: "common.chrome",
    description: "页面导航 renderer / 正文导航 primitive",
    composes: ["TabBar", "Pagination", "SelectorPanel", "SelectionGrid", "DisclosureSectionHeader"],
  },
  {
    name: "Toolbar",
    category: "common",
    subcategory: "common.chrome",
    description: "PageSurface 内部统一工具栏 renderer",
    composes: ["ActionButton", "SearchInput", "SelectField", "ToolbarOptionGroup", "FieldValueFilter", "DropdownSurface"],
  },
  {
    name: "useFeedback",
    category: "feedback",
    subcategory: "feedback.service",
    description: "统一前端反馈 Hook",
    capabilities: [
      { name: "notify", description: "普通通知消息，Core 统一决定 toast 呈现。" },
      { name: "success", description: "成功反馈，不在业务里手写 Toast。" },
      { name: "error", description: "错误反馈，不在业务里手写错误弹层。" },
      { name: "confirm", description: "通用确认对话框。" },
      { name: "confirmDelete", description: "删除确认语义，Core 统一危险操作文案和样式。" },
    ],
    composes: ["FeedbackProvider", "ConfirmModal", "Toast"],
  },
  {
    name: "NumberCell",
    category: "data",
    subcategory: "data.cell",
    description: "数字单元格",
  },
  {
    name: "OptionPicker",
    category: "common",
    subcategory: "common.selection",
    description: "统一选项选择器，支持平铺枚举、常用项 + 更多搜索，以及先选分类再选值的分组模式。",
    composes: ["PickerShell", "SearchInput", "PickerOptionButton"],
  },
  {
    name: "PageContent",
    category: "page",
    subcategory: "page.frame",
    description: "页面内容容器",
  },
  {
    name: "PageSurface",
    category: "page",
    subcategory: "page.surface",
    description: "唯一页面薄壳 L1 Surface",
    declares: [
      { name: "kind", description: "页面布局语义：list / detail / split / analysis / settings。" },
      {
        name: "header",
        description: "页面标题、返回、说明和右侧动作。",
        children: [
          { name: "title", description: "页面标题。" },
          { name: "backHref", description: "返回链接。" },
          { name: "actions", description: "页面右上角动作容器。" },
        ],
      },
      {
        name: "navigation",
        description: "页面级 tabs / cards 导航。",
        children: [
          { name: "kind", description: "导航呈现：tabs / cards。" },
          { name: "items", description: "一级与二级导航项。" },
          { name: "active", description: "当前激活项。" },
        ],
      },
      {
        name: "toolbar",
        description: "搜索、筛选、刷新、导出、新建等页面级工具。",
        children: [
          { name: "items", description: "工具项列表，具体渲染交给 Toolbar。" },
          { name: "hidden", description: "隐藏页面工具栏。" },
        ],
      },
      {
        name: "body",
        description: "正文 block wrapper 与正文级空态/动作。",
        children: [
          { name: "blocks", description: "正文区块列表，只承载 wrapper，不展开各 Surface 细节。" },
          { name: "layout", description: "正文 block 排布：single / split。" },
          { name: "empty", description: "正文为空时的空态。" },
          { name: "commands", description: "正文上方的简短命令；复杂工具归 toolbar。" },
        ],
      },
      {
        name: "footer",
        description: "页面级分页。",
        children: [
          { name: "pagination", description: "页面底部分页声明。" },
        ],
      },
    ],
    composes: ["DatabasePageFrame", "AnalysisPageFrame", "WorkspaceSplitPage", "Toolbar", "BlockSurface", "NavigationSurface", "Pagination", "ModuleCard"],
  },
  {
    name: "PageShell",
    category: "page",
    subcategory: "page.frame",
    description: "页面顶部骨架",
  },
  {
    name: "Pagination",
    category: "common",
    subcategory: "common.chrome",
    description: "分页控件",
  },
  {
    name: "PanelCard",
    category: "common",
    subcategory: "common.block",
    description: "通用面板卡片",
  },
  {
    name: "RatingControl",
    category: "common",
    subcategory: "common.input",
    description: "星级评分",
  },
  {
    name: "SearchableOptionInput",
    category: "common",
    subcategory: "common.selection",
    description: "可搜索选项输入",
    composes: ["getFieldInputClassName"],
  },
  {
    name: "SearchInput",
    category: "common",
    subcategory: "common.input",
    description: "搜索输入框",
  },
  {
    name: "SectionCard",
    category: "common",
    subcategory: "common.block",
    description: "小节卡片",
    composes: ["PanelCard"],
  },
  {
    name: "VisualizationSurface",
    category: "visualization",
    subcategory: "visualization.surface",
    description: "L1 可视化正文 Surface",
    declares: [
      {
        name: "kind",
        description: "可视化类型：chart / gantt。",
        children: [
          { name: "chart", description: "轻量图表，使用 visual 声明。" },
          { name: "gantt", description: "甘特图，使用 gantt typed spec 声明。" },
        ],
      },
      {
        name: "visual",
        description: "轻量图表声明。",
        children: [
          { name: "barChart", description: "单序列条形图。" },
          { name: "groupedBarChart", description: "分组条形图。" },
          { name: "comparisonBars", description: "实际值与参考值对比。" },
          { name: "tree", description: "树形层级可视化。" },
        ],
      },
      { name: "gantt", description: "甘特图 typed spec：rows / periodStart / zoom / dependencies / onToggle。" },
      { name: "framed", description: "是否使用通用面板外框。" },
      { name: "title", description: "可视化标题。" },
    ],
    composes: ["PanelCard", "VisualizationSurfaceChart", "VisualizationGantt", "VisualizationSurfaceTypes"],
  },
  {
    name: "VisualizationSurfaceChart",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 轻量图表 renderer。",
    composes: [],
  },
  {
    name: "VisualizationSurfaceTypes",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 轻量图与甘特图 public spec types。",
    composes: [],
  },
  {
    name: "VisualizationGantt",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 甘特图 typed spec renderer。",
    composes: ["VisualizationGanttUtils"],
  },
  {
    name: "VisualizationGanttUtils",
    category: "visualization",
    subcategory: "visualization.surface",
    role: "internal",
    description: "VisualizationSurface 甘特图时间刻度与定位算法。",
    composes: [],
  },
  {
    name: "SelectionGrid",
    category: "common",
    subcategory: "common.selection",
    description: "页面内平铺选项网格",
  },
  {
    name: "SelectField",
    category: "common",
    subcategory: "common.input",
    description: "下拉选择字段",
    composes: ["FieldInputShell", "SearchInput", "DropdownSurface", "CheckboxField"],
  },
  {
    name: "SegmentedCodeInput",
    category: "common",
    subcategory: "common.input",
    description: "分段编码输入控件",
    composes: ["TextField"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
