import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "SelectorPanel",
    category: "common",
    subcategory: "common.selection",
    description: "选择器面板",
    example: "列表页左侧选择区：可选搜索框，mode=list/tree/grid；业务不直接 import SelectorList/SelectorTree/SelectorCard/SelectionGrid。",
    declares: [
      { name: "mode", description: "选择结构：list / tree / grid。" },
      { name: "items", description: "可选项数据和层级关系。" },
      { name: "value", description: "当前选中项或选中集合。" },
      { name: "search", description: "是否启用搜索、搜索占位和查询回调。" },
      { name: "emptyState", description: "无匹配或空数据状态。" },
    ],
    composes: ["PanelCard", "SearchInput", "SelectionGrid", "SelectorList", "SelectorTree", "EmptyStateCard"],
  },
  {
    name: "SwitchField",
    category: "common",
    subcategory: "common.input",
    description: "开关字段",
    example: "在行内编辑中切换“启用 / 停用”或“是 / 否”。",
  },
  {
    name: "TagListInput",
    category: "common",
    subcategory: "common.input",
    description: "标签列表输入",
    example: "业务页统一使用 TagListInput 展示可删除标签、自定义样式标签，并支持追加输入或选择器入口。",
    composes: [
      "RemovableTag",
      "TagPill",
      "getTagInputShellClassName",
      "getTagInlineInputClassName",
      "getTagPillClassName",
    ],
  },
  {
    name: "TagStringInput",
    category: "common",
    subcategory: "common.input",
    description: "字符串标签输入",
    example: "详情页字段把逗号或顿号分隔的别名字符串渲染为可增删标签。",
    composes: ["RemovableTag", "TagInlineTextField", "FieldShell"],
  },
  {
    name: "StructuredTable",
    category: "data",
    subcategory: "data.table",
    description: "结构化表格",
    example: "检验记录、键值摘要或纸面格式表格只传通用行列结构，不在业务包手写 table。",
  },
  {
    name: "TabBar",
    category: "common",
    subcategory: "common.chrome",
    description: "Tab 切换栏",
    example: "Core 内部用于 PageSurface.navigation kind='tabs'；页面不得再直接 import TabBar 拼布局。",
    composes: ["ActionButton"],
  },
  {
    name: "TableScrollFrame",
    category: "data",
    subcategory: "data.table",
    description: "表格滚动外壳",
    example: "宽表格在小屏幕中横向滚动，DataTable 本身只负责表格结构。",
    composes: ["DataTable"],
  },
  {
    name: "TextareaField",
    category: "common",
    subcategory: "common.input",
    description: "多行文本输入",
    example: "在人事备注、合同说明或资料描述中输入多行文本。",
  },
  {
    name: "TextField",
    category: "common",
    subcategory: "common.input",
    description: "通用文本输入",
    example: "设置弹窗中输入用户名、密码或短文本字段。",
    composes: ["FieldInputShell", "getFieldInputClassName"],
  },
  {
    name: "TimeField",
    category: "common",
    subcategory: "common.input",
    description: "时间输入框",
    example: "会议开始时间拆成日期字段和 09:30 时间字段，提交时组合为 2026-06-20T09:30。",
    composes: ["FieldInputShell", "getFieldInputClassName"],
  },
  {
    name: "Toast",
    category: "feedback",
    subcategory: "feedback.renderer",
    description: "底层提示组件（Core 内部使用）",
    example: "FeedbackProvider 内部渲染成功提示；普通业务页面使用 useFeedback.success/error。",
    composes: ["ConfirmModal"],
  },] as const satisfies readonly CoreUiComponentRegistration[];
