import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "ReadOnlyField",
    category: "common",
    subcategory: "common.input",
    description: "只读字段展示",
    example: "员工编码、系统计算值或凭证号只读展示，默认 input-like 统一表单视觉；传 variant='plain' 可渲染纯文本值。",
    composes: ["FieldInputShell", "getReadOnlyFieldClassName", "getFieldValueClassName"],
  },
  {
    name: "FieldInputShell",
    category: "common",
    subcategory: "common.input",
    description: "字段输入外壳",
    example: "百分比或带单位后缀的组合输入控件共享同一字段外壳样式，支持 prefix/suffix。",
    composes: ["FieldShell", "getFieldInputClassName"],
  },
  {
    name: "FieldShell",
    category: "common",
    subcategory: "common.input",
    description: "统一字段壳",
    example: "文本、只读、外键、选择和标签字段共享高度、边框、圆角、焦点环与 affix 布局。",
    composes: ["getFieldShellClassName"],
  },
  {
    name: "FieldControl",
    category: "form",
    subcategory: "form.input-adapter",
    description: "统一字段控件选择器",
    example: "详情页按 kind 渲染 text、readonly、fk、tags 或 select，不在业务页手拼字段壳。",
    composes: ["InputControl"],
  },
  {
    name: "InputControl",
    category: "common",
    subcategory: "common.input",
    description: "字段规格输入控件",
    example: "业务声明 valueType/control/options/format/mask/state 后，由 Core 内部 resolver 渲染文本、选项、FK、标签、日期或筛选输入。",
    declares: [
      { name: "control", description: "输入语义：text / number / boolean / choice / reference / temporal / file / collection / rating。" },
      { name: "valueType", description: "字段数据形状：string / number / boolean / date / time / datetime / file / reference / array。" },
      { name: "options", description: "选项来源：none / static / grouped / remote；remote 用于 FK/reference。" },
      { name: "format", description: "展示和输入格式：percent / currency / date / time / datetime。" },
      { name: "mask", description: "输入约束和模板；分段编码使用 mask.kind=editableSegment。" },
    ],
    composes: ["CalendarDateInput", "CheckboxField", "ChoiceGroup", "FileField", "FkFieldInput", "OptionPicker", "PercentField", "RatingControl", "ReadOnlyField", "SearchableOptionInput", "SegmentedCodeInput", "SelectField", "SwitchField", "TagStringInput", "TextField", "TextareaField", "TimeField"],
  },
  {
    name: "PercentField",
    category: "common",
    subcategory: "common.input",
    description: "百分比输入字段",
    example: "项目完成度、岗位工作占比等百分比字段，统一带 % 后缀和数字校验。",
    composes: ["FieldInputShell", "TextField"],
  },
  {
    name: "FieldGrid",
    category: "form",
    subcategory: "form.layout",
    description: "字段网格信息表",
    example: "项目详情、员工资料按 label/value 网格展示字段，支持 columns/span/hint 和只读/编辑字段混排；hint 不撑高同行，长说明使用 FieldGrid.Note。",
    composes: [
      "getFieldGridCellClassName",
      "getFieldGridMainRowClassName",
      "getFieldGridHelperRowClassName",
      "getFieldGridLabelClassName",
      "getFieldGridValueClassName",
      "getFieldGroupTitleClassName",
    ],
  },
  {
    name: "TagInlineTextField",
    category: "common",
    subcategory: "common.input",
    description: "标签内联文本输入",
    example: "在 TagListInput 末尾继续输入新别名或标签草稿。",
    composes: ["getTagInlineInputClassName"],
  },
  {
    name: "CreatePanel",
    category: "form",
    subcategory: "form.create",
    description: "新建入口封装（inline | block）",
    example: "业务页只传 variant 和统一回调，即可在列表顶部、卡片区复用同一套新建逻辑；弹窗是 block 的 presentation。",
    declares: [
      { name: "variant", description: "新建形态：inline / block。" },
      { name: "presentation", description: "block 的呈现方式：block / modal。" },
      { name: "trigger", description: "触发入口和按钮文案，不开放底层按钮样式。" },
      { name: "fields", description: "新建表单字段声明，交给 FormSurface/InputControl 渲染。" },
      { name: "submit", description: "提交回调、loading、disabled 等行为状态。" },
      { name: "state", description: "打开、关闭、错误和完成后的状态控制。" },
    ],
    composes: ["InlineCreatePanel", "BlockCreatePanel"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
