import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "Toolbar",
    accessLayer: "page-api",
    kind: "toolbar",
    description: "统一工具栏",
    example: "列表页顶部统一配置搜索、状态筛选、新建按钮和分页信息。",
    composes: ["ActionButton", "SearchInput", "SelectField", "ToolbarOptionGroup", "FieldValueFilter"],
  },
  {
    name: "useConfirm",
    accessLayer: "page-api",
    kind: "overlay",
    description: "确认弹窗 Hook",
    example: "const confirm = useConfirm(); await confirm({ message: '...' })",
    composes: ["ConfirmProvider"],
  },
  {
    name: "useConfirmDelete",
    accessLayer: "page-api",
    kind: "overlay",
    description: "删除确认 Hook",
    example: "const confirmDelete = useConfirmDelete(); await confirmDelete({ message: '...' })",
    composes: ["ConfirmProvider"],
  },
  {
    name: "useUnsavedChangesPrompt",
    accessLayer: "page-api",
    kind: "overlay",
    description: "未保存离开提示",
    example: "详情页只传 hasUnsavedChanges，AppShell 或页内 Tab 统一确认是否离开。",
    composes: ["ConfirmProvider", "useConfirm"],
  },
  {
    name: "NumberCell",
    accessLayer: "page-api",
    kind: "cell",
    description: "数字单元格",
    example: "在库存或财务表格中展示 1,280 这类数量值。",
  },
  {
    name: "OptionPicker",
    accessLayer: "page-api",
    kind: "picker",
    description: "统一选项选择器，支持平铺枚举、常用项 + 更多搜索，以及先选分类再选值的分组模式。",
    example: "从状态/角色这类少量枚举直接选择，或在职级、职称中先选序列再选具体值。",
    composes: ["PickerShell", "SearchInput", "PickerOptionButton"],
  },
  {
    name: "PageContent",
    accessLayer: "page-api",
    kind: "layout",
    description: "页面内容容器",
    example: "AppShell 下方包裹页面主体，统一最大宽度和上下留白。",
  },
  {
    name: "PageShell",
    accessLayer: "page-api",
    kind: "layout",
    description: "页面顶部骨架",
    example: "子页面显示返回按钮、标题、副标题和右侧主操作。",
  },
  {
    name: "Pagination",
    accessLayer: "page-api",
    kind: "navigation",
    description: "分页控件",
    example: "数据库表格底部展示第 2/5 页和总计 48 条。",
  },
  {
    name: "PanelCard",
    accessLayer: "page-api",
    kind: "layout",
    description: "通用面板卡片",
    example: "表单小节、详情块或数据分析块的基础容器。",
  },
  {
    name: "RatingControl",
    accessLayer: "page-api",
    kind: "form",
    description: "星级评分",
    example: "工作计划中展示或编辑重要度、紧急度评分。",
  },
  {
    name: "SearchableOptionInput",
    accessLayer: "page-api",
    kind: "picker",
    description: "可搜索选项输入",
    example: "学校、供应商或本地白名单实体通过中文、拼音和别名搜索后选择。",
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "SearchInput",
    accessLayer: "page-api",
    kind: "form",
    description: "搜索输入框",
    example: "输入“张”按姓名、编码、拼音搜索或筛选记录。",
  },
  {
    name: "SectionCard",
    accessLayer: "page-api",
    kind: "layout",
    description: "小节卡片",
    example: "资料详情页展示“基础信息”“权限设置”等小节。",
    composes: ["PanelCard"],
  },
  {
    name: "SelectionGrid",
    accessLayer: "page-api",
    kind: "picker",
    description: "页面内平铺选项网格",
    example: "直属岗位导航、少量枚举切换等场景，选项数量少时直接展示，不用 dropdown picker。",
  },
  {
    name: "SelectField",
    accessLayer: "page-api",
    kind: "form",
    description: "下拉选择字段",
    example: "从“现用 / 已归档 / 全部”中选择筛选范围，或用多选切换表格列显隐。",
    composes: ["FieldInputShell", "SearchInput", "DropdownSurface", "CheckboxField"],
  },
  {
    name: "SelectorPanel",
    accessLayer: "page-api",
    kind: "picker",
    description: "选择器面板",
    example: "列表页左侧选择区：可选搜索框，mode=list/tree；业务不直接 import SelectorList/SelectorTree/SelectorCard。",
    composes: ["PanelCard", "SearchInput", "SelectorList", "SelectorTree", "EmptyStateCard"],
  },
  {
    name: "SwitchField",
    accessLayer: "page-api",
    kind: "form",
    description: "开关字段",
    example: "在行内编辑中切换“启用 / 停用”或“是 / 否”。",
  },
  {
    name: "TagListInput",
    accessLayer: "page-api",
    kind: "form",
    description: "标签列表输入",
    example: "业务页统一使用 TagListInput 展示可删除标签、自定义样式标签，并支持追加输入或选择器入口。",
    composes: ["RemovableTag", "TagPill"],
    foundations: ["getTagInputShellClassName", "getTagInlineInputClassName", "getTagPillClassName"],
  },
  {
    name: "TagStringInput",
    accessLayer: "page-api",
    kind: "form",
    description: "字符串标签输入",
    example: "详情页字段把逗号或顿号分隔的别名字符串渲染为可增删标签。",
    composes: ["TagListInput"],
  },
  {
    name: "StructuredTable",
    accessLayer: "page-api",
    kind: "data",
    description: "结构化表格",
    example: "检验记录、键值摘要或纸面格式表格只传通用行列结构，不在业务包手写 table。",
  },
  {
    name: "TabBar",
    accessLayer: "page-api",
    kind: "navigation",
    description: "Tab 切换栏",
    example: "页面级用 variant='large' accordion 展示一级 Tab 及其子 Tab；工具栏紧凑手风琴用 variant='small' accordion；普通页内 Tab 用 variant='mid'；选择器弹层内小型分段 tabs 用 variant='micro'。",
    composes: ["ActionButton"],
  },
  {
    name: "TableScrollFrame",
    accessLayer: "page-api",
    kind: "data",
    description: "表格滚动外壳",
    example: "宽表格在小屏幕中横向滚动，DataTable 本身只负责表格结构。",
    composes: ["DataTable"],
  },
  {
    name: "TextareaField",
    accessLayer: "page-api",
    kind: "form",
    description: "多行文本输入",
    example: "在人事备注、合同说明或资料描述中输入多行文本。",
  },
  {
    name: "TextField",
    accessLayer: "page-api",
    kind: "form",
    description: "通用文本输入",
    example: "设置弹窗中输入用户名、密码或短文本字段。",
    composes: ["FieldInputShell"],
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "TimeField",
    accessLayer: "page-api",
    kind: "form",
    description: "时间输入框",
    example: "会议开始时间拆成日期字段和 09:30 时间字段，提交时组合为 2026-06-20T09:30。",
    composes: ["FieldInputShell"],
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "Toast",
    accessLayer: "page-api",
    kind: "feedback",
    description: "成功提示",
    example: "保存成功后显示绿色提示，失败时显示确认弹窗。",
    composes: ["ConfirmModal"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
