import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "AmountCell",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "cell",
    description: "金额单元格",
    example: "在财务表格中展示 ¥ 12,800.00，并保持金额列右对齐。",
    composes: ["NumberCell"],
  },
  {
    name: "DataSurface",
    accessLayer: "page-api",
    uiLevel: 1,
    kind: "data",
    description: "L1 正文数据 Surface",
    example: "业务页在 PageSurface.body.blocks 中通过 kind='table'/'structured'/'records'/'metrics'/'visual'/'raw' 声明正文数据展示；页面级 toolbar 和分页统一放到 PageSurface.toolbar/footer。",
    composes: ["DataTable", "TableScrollFrame", "StructuredTable", "DisclosureRecordCard", "MetricCard", "CodeBlock", "Badge", "NumberCell", "AmountCell", "InputControl", "SelectionGrid", "CommandButton", "EmptyStateCard", "PanelCard"],
  },
  {
    name: "AnalysisBlock",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "layout",
    description: "分析内容块",
    example: "在人事分析页包裹趋势图、KPI 和预警摘要。",
    composes: ["PanelCard", "Toolbar"],
  },
  {
    name: "AutoSizeTextField",
    accessLayer: "core-internal",
    kind: "form",
    description: "自适应文本输入",
    example: "HR 批量表格中编辑手机号或身份证号时，输入框随内容宽度伸缩。",
  },
  {
    name: "CalendarDateInput",
    accessLayer: "core-internal",
    kind: "form",
    description: "日期输入框",
    example: "在人事入职日期或合同截止日期字段中选择 2026-06-20。",
    composes: ["FieldInputShell"],
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "CheckboxChip",
    accessLayer: "core-internal",
    kind: "form",
    description: "复选标签",
    example: "岗位说明书模板里勾选需要展示的字段。",
    composes: ["CheckboxField"],
  },
  {
    name: "CheckboxField",
    accessLayer: "core-internal",
    kind: "form",
    description: "复选框",
    example: "在创建表单中勾选是否启用、是否默认或是否归档。",
  },
  {
    name: "ChoiceGroup",
    accessLayer: "core-internal",
    kind: "form",
    description: "纸面选择组",
    example: "纸面记录里选择“是 / 否”，业务只传选项和值。",
  },
  {
    name: "CodeBlock",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "data",
    description: "代码块展示",
    example: "API 接入指南中展示 Bearer Client secret 请求头。",
  },
  {
    name: "CommandButton",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "toolbar",
    description: "文字命令按钮",
    example: "业务页渲染“保存”“取消”“删除”“刷新”等文字动作，不再直接拼 getToolbarActionClassName。",
    foundations: ["getToolbarActionClassName"],
  },
  {
    name: "ConfirmModal",
    accessLayer: "core-internal",
    kind: "overlay",
    description: "底层确认弹窗（Core 内部 / 专用弹窗使用）",
    example: "专用 Agent 确认弹窗可组合 ConfirmModal；普通业务页面使用 useFeedback.confirm。",
    composes: ["ActionButton"],
    foundations: ["getToolbarActionClassName"],
  },
  { name: "FeedbackProvider", accessLayer: "core-internal", kind: "feedback", description: "统一反馈 Provider", example: "根布局安装 FeedbackProvider，业务页面只通过 useFeedback 发起提示和确认。", composes: ["ConfirmModal", "Toast"] },
  {
    name: "DataTable",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "data",
    description: "通用数据表格",
    example: "渲染科目、凭证明细、合同或资料库文件列表。",
    composes: ["ActionButton"],
    foundations: ["dataTableClassNames"],
  },
  {
    name: "DetailModal",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "overlay",
    description: "详情弹窗",
    example: "在资料库中打开文件详情或在审计页查看记录明细。",
  },
  {
    name: "DocumentSurface",
    accessLayer: "page-api",
    uiLevel: 2,
    kind: "layout",
    description: "文档纸面 Surface",
    example: "业务页通过 PageSurface document block 承载 A4/纸面文档，不再用 moduleView 承载报告页。",
    composes: ["PageSurface"],
  },
  {
    name: "DisclosureRecordCard",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "data",
    description: "可展开记录卡片",
    example: "审计历史里点击一条记录展开变更详情，并显示“还原到此版本”动作。",
  },
  {
    name: "DisclosureSectionHeader",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "navigation",
    description: "可折叠分组标题",
    example: "工作计划中切换“日常工作 / 其他工作 / 已归档”分组。",
  },
  {
    name: "DropdownMenu",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "overlay",
    description: "下拉菜单",
    example: "平台用户菜单展示“设置 / 登出”，业务只提供动作列表。",
    composes: ["DropdownSurface"],
  },
  {
    name: "EmptyStateCard",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "layout",
    description: "空状态卡片",
    example: "筛选后无结果时显示“暂无数据，调整筛选条件”。",
  },
  {
    name: "EntityDetailLayout",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "layout",
    description: "实体详情布局",
    example: "部门、岗位或项目详情页用 Fields、Metrics 和 Field 统一详情区字段排版。",
    composes: ["FieldGrid", "FieldControl"],
  },
  {
    name: "FkFieldInput",
    accessLayer: "core-internal",
    kind: "picker",
    description: "外键搜索输入",
    example: "搜索“张”后从员工候选项中选择一个负责人。",
    composes: ["FieldInputShell", "SearchInput"],
  },
  {
    name: "FieldValueFilter",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "picker",
    description: "字段值筛选",
    example: "显示“员工：张文孝”，点击后先选字段，再用 HR reference-options 搜索选择员工。",
    composes: ["InputControl", "SelectField", "PickerOptionButton"],
  },
  {
    name: "FileField",
    accessLayer: "core-internal",
    kind: "form",
    description: "文件选择字段",
    example: "在财务导入或余额核对中选择 Excel 文件，不在业务页手写原生 file input。",
  },
  {
    name: "FormField",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "form",
    description: "表单字段容器",
    example: "合同弹窗包裹合同名称，财务筛选条用 inline 布局包裹公司、年度等字段。",
  },
  {
    name: "FormSurface",
    accessLayer: "page-api",
    uiLevel: 1,
    kind: "form",
    description: "L1 正文表单 Surface",
    example: "业务页在 PageSurface.body.blocks 中通过 kind='fields'/'filters'/'modal'/'inline'/'detail'/'login' 和 fields spec 渲染表单、筛选或详情字段；页面级 toolbar 统一放到 PageSurface.toolbar。",
    composes: ["FieldGrid", "FormField", "InputControl", "ReadOnlyField", "TagListInput", "TextField", "TextareaField", "CalendarDateInput", "ChoiceGroup", "SelectField", "FileField", "HiddenDataField", "DetailModal", "CommandButton"],
  },
  {
    name: "FormShell",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "form",
    description: "表单外壳",
    example: "登录页、账号设置或导入配置表单只传字段和提交函数。",
  },
  {
    name: "Badge",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "status",
    description: "通用徽标",
    example: "显示状态标签“已启用”，或层级标签“L2”。",
  },
  {
    name: "HiddenDataField",
    accessLayer: "core-internal",
    kind: "form",
    description: "隐藏数据字段",
    example: "QC 纸面日期展示为中文年月日，同时提交 ISO 日期值。",
  }
] as const satisfies readonly CoreUiComponentRegistration[];
