import type { CoreUiComponentRegistration } from "./component-registry-types";

export const core_internal_registry_entries = [
  {
    name: "ActionButton",
    accessLayer: "core-internal",
    kind: "toolbar",
    description: "工具栏动作按钮",
    example: "Toolbar、DataTable 行动作和新建确认都传 kind=\"save\" / kind=\"cancel\" 这类 glyph 动作。",
    foundations: ["ActionGlyph", "getToolbarActionClassName"],
  },
  {
    name: "RefreshActionButton",
    accessLayer: "core-internal",
    kind: "toolbar",
    description: "工具栏刷新按钮",
    example: "Toolbar 的刷新入口统一显示刷新图标，而不是文字按钮。",
    composes: ["ActionButton"],
  },
  {
    name: "BlockCreatePanel",
    accessLayer: "core-internal",
    kind: "form",
    description: "块状新建面板",
    example: "项目阶段和项目任务这类多字段新增，不常驻表单，点击标题旁 + 后展开维护。",
    composes: ["SectionCard", "CreateStartButton", "CreateConfirmActions"],
  },
  {
    name: "CreateConfirmActions",
    accessLayer: "core-internal",
    kind: "form",
    description: "新建确认动作",
    example: "新建态标题旁展示取消和确认按钮，不在业务页手写 x/勾图标。",
    composes: ["ActionButton"],
  },
  {
    name: "CreateStartButton",
    accessLayer: "core-internal",
    kind: "form",
    description: "新建开始按钮",
    example: "列表、阶段或任务区进入新建态时，标题旁 + 高亮。",
    composes: ["ActionButton"],
  },
  {
    name: "DropdownSurface",
    accessLayer: "core-internal",
    kind: "overlay",
    description: "下拉浮层",
    example: "供 SelectField、DropdownMenu 等组件复用，业务不应直接使用。",
  },
  {
    name: "ToolbarOptionGroup",
    accessLayer: "core-internal",
    kind: "toolbar",
    description: "工具栏选项组",
    example: "在筛选栏里切换“全部 / 30天 / 90天 / 已到期”或“姓名 / 全部”。",
  },
  {
    name: "InlineCreatePanel",
    accessLayer: "core-internal",
    kind: "form",
    description: "内联新建面板",
    example: "在列表顶部展开新建员工、批次、部门或岗位表单，填写 required 字段后确认创建。",
    composes: ["CreateConfirmActions", "FormField"],
  },
  {
    name: "ModalCreatePanel",
    accessLayer: "core-internal",
    kind: "overlay",
    description: "弹窗新建面板",
    example: "合同列表点击新建后弹出完整表单，底部使用统一取消和保存动作。",
    composes: ["DetailModal", "ActionButton"],
    foundations: ["getToolbarActionClassName"],
  },
  {
    name: "ModuleCardBody",
    accessLayer: "core-internal",
    kind: "layout",
    description: "模块卡片主体",
    example: "ModuleCard 内部使用；业务统一使用 ModuleCard。",
    foundations: ["moduleCardColorClasses"],
  },
  {
    name: "PickerOptionButton",
    accessLayer: "core-internal",
    kind: "picker",
    description: "选择器选项按钮",
    example: "职级选择器里展示 M/P/T 下面的等级按钮；分组选择器顶部用占位变体展示“未设置”。",
  },
  {
    name: "PickerShell",
    accessLayer: "core-internal",
    kind: "picker",
    description: "选择器外壳",
    example: "组合搜索框、候选列表和无匹配提示的选择器外壳。",
    composes: ["SearchInput"],
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "TagPill",
    accessLayer: "core-internal",
    kind: "form",
    description: "标签内核",
    example: "作为 RemovableTag 和 TagListInput 的共同视觉内核，不直接暴露给业务。",
    foundations: ["getTagPillClassName"],
  },
  {
    name: "RemovableTag",
    accessLayer: "core-internal",
    kind: "form",
    description: "可删除标签",
    example: "TagListInput 内部使用；业务统一使用 TagListInput。",
    composes: ["TagPill", "TagRemoveButton"],
    foundations: ["getTagPillClassName"],
  },
  {
    name: "SelectorCard",
    accessLayer: "core-internal",
    kind: "picker",
    description: "选择卡片",
    example: "左侧列表中选择一个项目或员工记录。",
  },
  {
    name: "SplitWorkspace",
    accessLayer: "core-internal",
    kind: "layout",
    description: "左右分栏工作区",
    example: "左侧项目列表，右侧保持当前项目详情编辑区。",
    composes: ["Toolbar", "ActionButton"],
  },
  {
    name: "TagRemoveButton",
    accessLayer: "core-internal",
    kind: "form",
    description: "标签删除按钮",
    example: "RemovableTag 内部使用；业务统一使用 TagListInput。",
    composes: ["useConfirmDelete"],
  },
  {
    name: "TreeNodeBranch",
    accessLayer: "core-internal",
    kind: "layout",
    description: "树节点分支",
    example: "组织树中展示父部门和多个子部门节点。",
    composes: ["TreeNodeCard"],
  },
  {
    name: "TreeNodeCard",
    accessLayer: "core-internal",
    kind: "layout",
    description: "树节点卡片",
    example: "组织架构中展示“生产中心 / 一级部门 / 现用”。",
    composes: ["Badge"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
