import type { CoreUiComponentRegistration } from "./component-registry-types";

export const core_internal_registry_entries = [
  {
    name: "ActionButton",
    category: "common",
    subcategory: "common.action",
    description: "工具栏动作按钮",
    composes: ["ActionGlyph", "getToolbarActionClassName"],
  },
  {
    name: "RefreshActionButton",
    category: "common",
    subcategory: "common.action",
    description: "工具栏刷新按钮",
    composes: ["ActionButton"],
  },
  {
    name: "BlockCreatePanel",
    category: "form",
    subcategory: "form.create",
    description: "块状新建面板",
    composes: ["SectionCard", "CreateStartButton", "CreateConfirmActions"],
  },
  {
    name: "CreateConfirmActions",
    category: "common",
    subcategory: "common.action",
    description: "新建确认动作",
    composes: ["ActionButton"],
  },
  {
    name: "CreateStartButton",
    category: "common",
    subcategory: "common.action",
    description: "新建开始按钮",
    composes: ["ActionButton"],
  },
  {
    name: "DropdownSurface",
    category: "common",
    subcategory: "common.overlay",
    description: "下拉浮层",
  },
  {
    name: "ToolbarOptionGroup",
    category: "common",
    subcategory: "common.chrome",
    description: "工具栏选项组",
  },
  {
    name: "InlineCreatePanel",
    category: "form",
    subcategory: "form.create",
    description: "内联新建面板",
    composes: ["CreateConfirmActions", "FormField"],
  },
  {
    name: "ModuleCardBody",
    category: "common",
    subcategory: "common.block",
    description: "模块卡片主体",
    composes: ["moduleCardColorClasses"],
  },
  {
    name: "PickerOptionButton",
    category: "common",
    subcategory: "common.selection",
    description: "选择器选项按钮",
  },
  {
    name: "PickerShell",
    category: "common",
    subcategory: "common.selection",
    description: "选择器外壳",
    composes: ["SearchInput", "getFieldInputClassName"],
  },
  {
    name: "TagPill",
    category: "common",
    subcategory: "common.input",
    description: "标签内核",
    composes: ["getTagPillClassName"],
  },
  {
    name: "RemovableTag",
    category: "common",
    subcategory: "common.input",
    description: "可删除标签",
    composes: ["TagPill", "TagRemoveButton", "getTagPillClassName"],
  },
  {
    name: "SelectorCard",
    category: "common",
    subcategory: "common.selection",
    description: "选择卡片",
  },
  {
    name: "SelectorList",
    category: "common",
    subcategory: "common.selection",
    description: "选择列表渲染器",
    composes: ["SelectorCard", "EmptyStateCard"],
  },
  {
    name: "SelectorTree",
    category: "common",
    subcategory: "common.selection",
    description: "树形选择渲染器",
    composes: ["TreeNodeCard", "TreeNodeBranch"],
  },
  {
    name: "SplitWorkspace",
    category: "page",
    subcategory: "page.frame",
    description: "左右分栏工作区",
    composes: ["Toolbar", "ActionButton"],
  },
  {
    name: "TagRemoveButton",
    category: "common",
    subcategory: "common.input",
    description: "标签删除按钮",
  },
  {
    name: "TreeNodeBranch",
    category: "common",
    subcategory: "common.selection",
    description: "树节点分支",
    composes: ["TreeNodeCard"],
  },
  {
    name: "TreeNodeCard",
    category: "common",
    subcategory: "common.selection",
    description: "树节点卡片",
    composes: ["Badge"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
