import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "AmountCell",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "cell",
    description: "金额单元格",
    example: "在财务表格中展示 ¥ 12,800.00，并保持金额列右对齐。",
    composes: ["NumberCell"],
  },
  {
    name: "AnalysisBlock",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "layout",
    description: "分析内容块",
    example: "在人事分析页包裹趋势图、KPI 和预警摘要。",
    composes: ["PanelCard"],
  },
  {
    name: "AutoSizeTextField",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "自适应文本输入",
    example: "HR 批量表格中编辑手机号或身份证号时，输入框随内容宽度伸缩。",
  },
  {
    name: "CalendarDateInput",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "日期输入框",
    example: "在人事入职日期或合同截止日期字段中选择 2026-06-20。",
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "CheckboxChip",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "复选标签",
    example: "岗位说明书模板里勾选需要展示的字段。",
    composes: ["CheckboxField"],
  },
  {
    name: "CheckboxField",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "复选框",
    example: "在创建表单中勾选是否启用、是否默认或是否归档。",
  },
  {
    name: "ChoiceGroup",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "纸面选择组",
    example: "纸面记录里选择“是 / 否”，业务只传选项和值。",
  },
  {
    name: "CodeBlock",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "data",
    description: "代码块展示",
    example: "API 接入指南中展示 Bearer Client secret 请求头。",
  },
  {
    name: "CommandButton",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "toolbar",
    description: "文字命令按钮",
    example: "业务页渲染“保存”“取消”“删除”“刷新”等文字动作，不再直接拼 getToolbarActionClassName。",
    foundations: ["getToolbarActionClassName"],
  },
  {
    name: "ConfirmModal",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "overlay",
    description: "确认弹窗",
    example: "删除合同、归档项目或停用记录前显示确认文案和危险按钮。",
    composes: ["ActionButton"],
    foundations: ["getToolbarActionClassName"],
  },
  {
    name: "ConfirmProvider",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "overlay",
    description: "确认弹窗上下文",
    example: "页面调用 confirm()，由 Provider 统一渲染确认弹窗。",
    composes: ["ConfirmModal"],
  },
  {
    name: "DataTable",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "data",
    description: "通用数据表格",
    example: "渲染科目、凭证明细、合同或资料库文件列表。",
    composes: ["ActionButton"],
    foundations: ["dataTableClassNames"],
  },
  {
    name: "DetailModal",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "overlay",
    description: "详情弹窗",
    example: "在资料库中打开文件详情或在审计页查看记录明细。",
  },
  {
    name: "DisclosureRecordCard",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "data",
    description: "可展开记录卡片",
    example: "审计历史里点击一条记录展开变更详情，并显示“还原到此版本”动作。",
  },
  {
    name: "DisclosureSectionHeader",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "navigation",
    description: "可折叠分组标题",
    example: "工作计划中切换“日常工作 / 其他工作 / 已归档”分组。",
  },
  {
    name: "DropdownMenu",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "overlay",
    description: "下拉菜单",
    example: "平台用户菜单展示“设置 / 登出”，业务只提供动作列表。",
    composes: ["DropdownSurface"],
  },
  {
    name: "EmptyStateCard",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "layout",
    description: "空状态卡片",
    example: "筛选后无结果时显示“暂无数据，调整筛选条件”。",
  },
  {
    name: "FkFieldInput",
    tier: "shell",
    accessLayer: "page-api",
    kind: "picker",
    description: "外键搜索输入",
    example: "搜索“张”后从员工候选项中选择一个负责人。",
    composes: ["SearchInput"],
  },
  {
    name: "FieldValueFilter",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "picker",
    description: "字段值筛选",
    example: "显示“员工：张文孝”，点击后先选字段，再用 HR reference-options 搜索选择员工。",
    composes: ["SelectField", "SearchInput", "FkFieldInput", "PickerOptionButton"],
  },
  {
    name: "FileField",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "文件选择字段",
    example: "在财务导入或余额核对中选择 Excel 文件，不在业务页手写原生 file input。",
  },
  {
    name: "FormField",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "form",
    description: "表单字段容器",
    example: "合同弹窗包裹合同名称，财务筛选条用 inline 布局包裹公司、年度等字段。",
  },
  {
    name: "FormShell",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "form",
    description: "表单外壳",
    example: "登录页、账号设置或导入配置表单只传字段和提交函数。",
  },
  {
    name: "Badge",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "status",
    description: "通用徽标",
    example: "显示状态标签“已启用”，或层级标签“L2”。",
  },
  {
    name: "HiddenDataField",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "隐藏数据字段",
    example: "QC 纸面日期展示为中文年月日，同时提交 ISO 日期值。",
  },
  {
    name: "ReadOnlyField",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "只读字段展示",
    example: "员工编码、系统计算值或凭证号只读展示，保持表单视觉一致。",
    foundations: ["getReadOnlyFieldClassName"],
  },
  {
    name: "FieldInputShell",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "字段输入外壳",
    example: "百分比或带单位后缀的组合输入控件共享同一字段外壳样式。",
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "FieldGrid",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "form",
    description: "字段网格",
    example: "员工资料、合同资料或只读详情页按 label/value 网格展示字段，不在业务包直接拼字段网格 foundation。",
    foundations: [
      "getFieldGridCellClassName",
      "getFieldGridLabelClassName",
      "getFieldGridValueClassName",
      "getFieldGroupTitleClassName",
    ],
  },
  {
    name: "TagInlineTextField",
    tier: "primitive",
    accessLayer: "page-api",
    kind: "form",
    description: "标签内联文本输入",
    example: "在 TagListInput 末尾继续输入新别名或标签草稿。",
    foundations: ["getTagInlineInputClassName"],
  },
  {
    name: "CreatePanel",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "form",
    description: "新建入口封装",
    example: "业务页只传 variant 和统一回调，即可在列表顶部、卡片区或弹窗中复用同一套新建逻辑。",
    composes: ["InlineCreatePanel", "BlockCreatePanel", "ModalCreatePanel"],
  },
  {
    name: "MetricCard",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "layout",
    description: "指标卡片",
    example: "分析页展示“本月 128”“同比 +12%”“预警 3”。",
  },
  {
    name: "ModuleCard",
    tier: "assembly",
    accessLayer: "page-api",
    kind: "layout",
    description: "模块入口卡片",
    example: "设置首页或模块首页使用卡片展示功能入口，支持链接、点击和纯展示模式；平台通过 renderLink 接入 Next Link。",
    composes: ["ModuleCardBody"],
    foundations: ["getModuleCardClassName", "moduleCardColorClasses", "getToolbarActionClassName"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
