import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_frame_registry_entries = [
  {
    name: "AnalysisPageFrame",
    category: "page",
    subcategory: "page.frame",
    description: "分析页骨架",
    example: "人力分析或财务分析页面只传 tabs、metrics 和 AnalysisBlock 内容。",
    composes: ["PageContent", "TabBar"],
  },
  {
    name: "DatabasePageFrame",
    category: "page",
    subcategory: "page.frame",
    description: "数据库页骨架",
    example: "员工资料、财务科目、报表配置和注册表页面只传筛选区与 DataTable。",
    composes: ["PageContent", "TabBar", "Toolbar"],
  },
  {
    name: "ModuleGridPage",
    category: "page",
    subcategory: "page.blocks",
    description: "模块入口页骨架",
    example: "设置首页或模块首页使用卡片网格。",
    composes: ["PageContent"],
  },
  {
    name: "TemplateWorkbenchFrame",
    category: "page",
    subcategory: "page.blocks",
    description: "模板工作台骨架",
    example: "生产检验模板页把产品、阶段、检测项和业务反馈/预览动作映射进来，特化弹窗留在业务包设计。",
    composes: [
      "Toolbar",
      "SearchInput",
      "SelectorCard",
      "PanelCard",
      "Badge",
      "ActionButton",
      "EmptyStateCard",
      "getToolbarActionClassName",
    ],
  },
  {
    name: "page-style-preview",
    category: "page",
    subcategory: "page.blocks",
    description: "页面样式预览",
    example: "设置页从 page-style-preview/template-data 获取页面模板路由和分组。",
  },
  {
    name: "WorkspaceSplitPage",
    category: "page",
    subcategory: "page.frame",
    description: "主从分栏页面",
    example: "项目、部门岗位和资料库详情页左侧选择对象，右侧编辑详情。",
    composes: ["PageContent", "SplitWorkspace", "Toolbar", "ActionButton", "TabBar"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
