import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "AmountCell",
    category: "data",
    subcategory: "data.cell",
    description: "金额单元格",
    example: "在财务表格中展示 ¥ 12,800.00，并保持金额列右对齐。",
    composes: ["NumberCell"],
  },
  {
    name: "DataSurface",
    category: "data",
    subcategory: "data.surface",
    description: "L1 正文数据 Surface",
    example: "业务页在 PageSurface.body.blocks 中通过 kind='table'/'structured'/'records'/'metrics'/'visual'/'raw' 声明正文数据展示；页面级 toolbar 和分页统一放到 PageSurface.toolbar/footer。",
    composes: ["DataTable", "TableScrollFrame", "StructuredTable", "DisclosureRecordCard", "MetricCard", "CodeBlock", "Badge", "NumberCell", "AmountCell", "InputControl", "SelectionGrid", "CommandButton", "EmptyStateCard", "PanelCard"],
  },
  {
    name: "AnalysisBlock",
    category: "page",
    subcategory: "page.blocks",
    description: "分析内容块",
    example: "在人事分析页包裹趋势图、KPI 和预警摘要。",
    composes: ["PanelCard", "Toolbar"],
  },
  {
    name: "AutoSizeTextField",
    category: "common",
    subcategory: "common.input",
    description: "自适应文本输入",
    example: "HR 批量表格中编辑手机号或身份证号时，输入框随内容宽度伸缩。",
  },
  {
    name: "CalendarDateInput",
    category: "common",
    subcategory: "common.input",
    description: "日期输入框",
    example: "在人事入职日期或合同截止日期字段中选择 2026-06-20。",
    composes: ["FieldInputShell", "getFieldInputClassName"],
  },
  {
    name: "CheckboxChip",
    category: "common",
    subcategory: "common.input",
    description: "复选标签",
    example: "岗位说明书模板里勾选需要展示的字段。",
    composes: ["CheckboxField"],
  },
  {
    name: "CheckboxField",
    category: "common",
    subcategory: "common.input",
    description: "复选框",
    example: "在创建表单中勾选是否启用、是否默认或是否归档。",
  },
  {
    name: "ChoiceGroup",
    category: "common",
    subcategory: "common.input",
    description: "纸面选择组",
    example: "纸面记录里选择“是 / 否”，业务只传选项和值。",
  },
  {
    name: "CodeBlock",
    category: "common",
    subcategory: "common.display",
    description: "代码块展示",
    example: "API 接入指南中展示 Bearer Client secret 请求头。",
  },
  {
    name: "CommandButton",
    category: "common",
    subcategory: "common.action",
    description: "文字命令按钮",
    example: "业务页渲染“保存”“取消”“删除”“刷新”等文字动作，不再直接拼 getToolbarActionClassName。",
    composes: ["getToolbarActionClassName"],
  },
  {
    name: "ConfirmModal",
    category: "feedback",
    subcategory: "feedback.renderer",
    description: "底层确认弹窗（Core 内部 / 专用弹窗使用）",
    example: "专用 Agent 确认弹窗可组合 ConfirmModal；普通业务页面使用 useFeedback.confirm。",
    composes: ["ActionButton", "getToolbarActionClassName"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
