import type { CoreUiComponentRegistration } from "./component-registry-types";

export const foundation_registry_entries = [
  {
    name: "ActionGlyph",
    accessLayer: "foundation",
    kind: "toolbar",
    description: "通用动作图标",
    example: "新增 glyph 时进入 ACTION_GLYPH_KINDS 和 ACTION_GLYPH_GROUPS，并在 ACTION_GLYPH_ORDER 写入 icon / group / subgroup / order。",
    pseudoRegistered: true,
  },
  {
    name: "ACTION_GLYPH_KINDS",
    accessLayer: "foundation",
    kind: "toolbar",
    description: "动作图标种类集合",
    example: "ActionGlyph 支持的 kind 闭包集合。",
    pseudoRegistered: true,
  },
  {
    name: "ACTION_GLYPH_ORDER",
    accessLayer: "foundation",
    kind: "toolbar",
    description: "动作图标排序配置",
    example: "定义各图标在 Toolbar 动作组中的出现顺序。",
    pseudoRegistered: true,
  },
  {
    name: "ACTION_GLYPH_GROUPS",
    accessLayer: "foundation",
    kind: "toolbar",
    description: "动作图标语义分组",
    example: "将图标按 create / edit / delete 等业务语义分组。",
    pseudoRegistered: true,
  },
  {
    name: "ACTION_GLYPH_TOOLBAR_GROUPS",
    accessLayer: "foundation",
    kind: "toolbar",
    description: "工具栏动作分组配置",
    example: "将图标分组映射到 Toolbar 的 primary / browse / extended 区域。",
    pseudoRegistered: true,
  },
  {
    name: "getFieldInputClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "字段输入样式",
    example: "业务字段必须自渲染 input 时复用统一高度、边框和焦点态。",
    pseudoRegistered: true,
  },
  {
    name: "getFieldGridCellClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "字段网格单元样式",
    example: "员工详情页的字段网格单元复用该 token，不在业务页重写格子样式。",
    pseudoRegistered: true,
  },
  {
    name: "getFieldGridLabelClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "字段网格标签样式",
    example: "详情页字段标签以统一字号、字重和颜色展示。",
    pseudoRegistered: true,
  },
  {
    name: "getFieldGridValueClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "字段网格值区样式",
    example: "详情页字段值和输入控件都落入同一值区样式。",
    pseudoRegistered: true,
  },
  {
    name: "getFieldGroupTitleClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "字段分组标题样式",
    example: "员工资料中“身份”“联系与账号”等分组标题保持一致。",
    pseudoRegistered: true,
  },
  {
    name: "getReadOnlyFieldClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "只读字段样式",
    example: "员工编码或系统计算值只读展示时保持表单视觉一致。",
    pseudoRegistered: true,
  },
  {
    name: "getTagInputShellClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "标签输入外壳样式",
    example: "别名、标签或关键词输入区需要多个 chip 时复用容器样式。",
    pseudoRegistered: true,
  },
  {
    name: "getTagInlineInputClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "标签内联输入样式",
    example: "员工别名标签末尾继续输入新别名时复用统一内联输入样式。",
    pseudoRegistered: true,
  },
  {
    name: "getTagPillClassName",
    accessLayer: "foundation",
    kind: "form",
    description: "标签项样式",
    example: "展示“重点客户”“GMP”这类可删除标签 chip。",
    pseudoRegistered: true,
  },
  {
    name: "getToolbarActionClassName",
    accessLayer: "foundation",
    kind: "toolbar",
    description: "工具栏动作样式",
    example: "业务优先使用 CommandButton 或 Toolbar 渲染文字动作；仅在 Toolbar custom 区域等少量自定义挂载点直接使用。",
    pseudoRegistered: true,
  },
  {
    name: "dataTableClassNames",
    accessLayer: "foundation",
    kind: "data",
    description: "表格样式配方",
    example: "业务自渲染表格结构时复用 DataTable 同一套样式 token。",
    pseudoRegistered: true,
  },
  {
    name: "moduleCardColorClasses",
    accessLayer: "foundation",
    kind: "layout",
    description: "模块卡片颜色",
    example: "设置首页的功能卡片按人力资源、财务等分类显示统一颜色。",
    pseudoRegistered: true,
  },
  {
    name: "getModuleCardClassName",
    accessLayer: "foundation",
    kind: "layout",
    description: "模块卡片样式",
    example: "设置首页功能卡片按人力资源、财务等分类使用统一颜色变体。",
    foundations: ["moduleCardColorClasses"],
    pseudoRegistered: true,
  },
] as const satisfies readonly CoreUiComponentRegistration[];
