import type { CoreUiComponentRegistration } from "./component-registry-types";

export const page_api_registry_entries = [
  {
    name: "ReadOnlyField",
    accessLayer: "core-internal",
    kind: "form",
    description: "只读字段展示",
    example: "员工编码、系统计算值或凭证号只读展示，默认 input-like 统一表单视觉；传 variant='plain' 可渲染纯文本值。",
    composes: ["FieldInputShell"],
    foundations: ["getReadOnlyFieldClassName", "getFieldValueClassName"],
  },
  {
    name: "FieldInputShell",
    accessLayer: "core-internal",
    kind: "form",
    description: "字段输入外壳",
    example: "百分比或带单位后缀的组合输入控件共享同一字段外壳样式，支持 prefix/suffix。",
    composes: ["FieldShell"],
    foundations: ["getFieldInputClassName"],
  },
  {
    name: "FieldShell",
    accessLayer: "core-internal",
    kind: "form",
    description: "统一字段壳",
    example: "文本、只读、外键、选择和标签字段共享高度、边框、圆角、焦点环与 affix 布局。",
    foundations: ["getFieldShellClassName"],
  },
  {
    name: "FieldControl",
    accessLayer: "core-internal",
    kind: "form",
    description: "统一字段控件选择器",
    example: "详情页按 kind 渲染 text、readonly、fk、tags 或 select，不在业务页手拼字段壳。",
    composes: ["InputControl"],
  },
  {
    name: "InputControl",
    accessLayer: "page-api",
    kind: "form",
    description: "字段规格输入控件",
    example: "业务声明 valueType/editor/options/format/state 后，由 Core 渲染文本、选项、FK、标签、日期或筛选输入。",
    composes: ["CalendarDateInput", "CheckboxField", "FileField", "FkFieldInput", "OptionPicker", "PercentField", "RatingControl", "ReadOnlyField", "SearchableOptionInput", "SegmentedCodeInput", "SelectField", "SwitchField", "TagStringInput", "TextField", "TextareaField", "TimeField"],
  },
  {
    name: "PercentField",
    accessLayer: "core-internal",
    kind: "form",
    description: "百分比输入字段",
    example: "项目完成度、岗位工作占比等百分比字段，统一带 % 后缀和数字校验。",
    composes: ["FieldInputShell", "TextField"],
  },
  {
    name: "FieldGrid",
    accessLayer: "core-internal",
    uiLevel: 3,
    kind: "form",
    description: "字段网格信息表",
    example: "项目详情、员工资料按 label/value 网格展示字段，支持 columns/span/hint 和只读/编辑字段混排；hint 不撑高同行，长说明使用 FieldGrid.Note。",
    foundations: [
      "getFieldGridCellClassName",
      "getFieldGridMainRowClassName",
      "getFieldGridHelperRowClassName",
      "getFieldGridLabelClassName",
      "getFieldGridValueClassName",
      "getFieldGroupTitleClassName",
    ],
  },
  {
    name: "TagInlineTextField",
    accessLayer: "core-internal",
    kind: "form",
    description: "标签内联文本输入",
    example: "在 TagListInput 末尾继续输入新别名或标签草稿。",
    foundations: ["getTagInlineInputClassName"],
  },
  {
    name: "CreatePanel",
    accessLayer: "page-api",
    kind: "form",
    description: "新建入口封装（inline | block | modal | detail）",
    example: "业务页只传 variant 和统一回调，即可在列表顶部、卡片区、弹窗或右侧详情 pane 中复用同一套新建逻辑。",
    composes: ["InlineCreatePanel", "BlockCreatePanel", "ModalCreatePanel", "DetailCreatePanel"],
  },
] as const satisfies readonly CoreUiComponentRegistration[];
