// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { executeFinanceAssetReferenceOptionsCommand } from "@workspace/finance/server/assets/reference-options";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";
import { referenceOptionsQuerySchema } from "@workspace/platform/server/reference-options";

export const GET = createCommandRoute({
  querySchema: referenceOptionsQuerySchema,
  queryError: "资产引用候选项参数无效",
  buildCommand: ({ query, user, searchParams }) => okCommand({
    fkKey: query.fkKey,
    keyword: query.keyword,
    lifecycleScope: query.lifecycleScope,
    userId: user.userId,
    params: Object.fromEntries(searchParams.entries()),
  }),
  action: executeFinanceAssetReferenceOptionsCommand,
});
