// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createProtectedModulePage } from "@workspace/platform/server/protected-page";
import { BudgetTab } from "@workspace/finance/ui";

export default createProtectedModulePage({
  route: "/finance/budget",
  title: "预算管理",
  backHref: "/finance",
  render: ({ user }) => <BudgetTab user={user} />,
});
