// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  buildUploadErpDiligenceEvidenceRouteCommand,
  ErpDiligenceEvidenceUploadSchema,
  uploadErpDiligenceEvidenceAttachment,
} from "@workspace/administration/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";

export const POST = createCommandRoute({
  bodyParser: "formData",
  bodySchema: ErpDiligenceEvidenceUploadSchema,
  bodyError: "样表附件上传参数无效",
  buildCommand: ({ body, user }) => buildUploadErpDiligenceEvidenceRouteCommand(body, user.userId),
  action: uploadErpDiligenceEvidenceAttachment,
});
