export {
  formatHrMajorItems,
  getHrMajorPickerOptions,
  getHrMajorPickerValue,
  HR_ATTENDANCE_TYPES,
  HR_COMMON_ETHNICITIES,
  HR_CONTRACT_TYPES,
  HR_EDUCATIONS,
  HR_EMPLOYMENT_FORMS,
  HR_EMPLOYMENT_TITLES,
  HR_ETHNICITIES,
  HR_INSURANCE_STATUSES,
  HR_LEGAL_RELATIONS,
  HR_MAJOR_GROUPS,
  HR_OFFICE_LOCATIONS,
  HR_PERSONNEL_TYPES,
  HR_POLITICS,
  HR_PROFESSIONAL_TITLE_GROUPS,
  HR_PROFESSIONAL_TITLES,
  HR_RANKS,
  isAllowedHrOption,
  isValidHrMajorItem,
  normalizeHrMajorItems,
  normalizeProfessionalTitle,
  parseHrMajorPickerValue,
  serializeHrMajorItems,
} from "@workspace/hr/constants/field-options";
export type { HRMajorItem, HRProfessionalTitleOption } from "@workspace/hr/constants/field-options";
