// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import ModuleHomePage from "@workspace/platform/server/module-home-page";

export default async function FinancePage() {
  return <ModuleHomePage moduleKey="finance" />;
}
