// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { okCommand } from "@workspace/platform/server/domain-validation";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { loadBudgetOverview } from "@workspace/finance/server/budget/service";
import { budgetQuerySchema } from "@workspace/finance/server/budget/schemas";

export const GET = createCommandRoute({
  querySchema: budgetQuerySchema,
  queryError: "参数无效",
  buildCommand: ({ query }) => okCommand(query as Parameters<typeof loadBudgetOverview>[0]),
  action: (command) => loadBudgetOverview(command),
});
