// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { loadConsolidatedReportOutput } from "@workspace/finance/server/statements/consolidated-output-service";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const paramsSchema = z.object({ batchId: z.coerce.number().int().positive() });

export const GET = createCommandRoute({
  paramsSchema,
  paramsError: "合并批次 ID 无效",
  buildCommand: ({ params }) => okCommand({ batchId: params.batchId }),
  action: ({ batchId }) => loadConsolidatedReportOutput(batchId),
});
