// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { requireRouteAccess } from "@workspace/platform/server/auth";
import { emptyWorkDepartmentHomeData, getDepartmentHomeOverview, listWorkTaskSpaces } from "@workspace/work/server";
import { WorkDepartmentHomePageView } from "@workspace/work/ui";

export default async function WorkDepartmentEntryPage() {
  const user = await requireRouteAccess("/work/me");
  const [overview, navigation] = await Promise.all([
    getDepartmentHomeOverview({ userId: user.id }),
    listWorkTaskSpaces(user.id),
  ]);

  return <WorkDepartmentHomePageView
    user={user}
    data={overview.ok ? overview.data : emptyWorkDepartmentHomeData()}
    navigation={navigation}
  />;
}
