schema_version: 1
template_id: appearance_visual
products:
  allopurinol:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  atenolol:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品适量，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品适量，目测，本品为
  berberine_tannate:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  clarithromycin:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，取本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品内容物，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品内容物，目测，本品为
  compound_rutin:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  diammonium_glycyrrhizinate:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，取本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品内容物为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品内容物为
  hydrochlorothiazide:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  isosorbide_dinitrate:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  methimazole:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  pantoprazole:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置光线充足的地方，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  simvastatin:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  spironolactone:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
  terazosin:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品置于光线充足的地方，目测，取本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品内容物，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品内容物，目测，本品为
  verapamil:
    intermediate:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    packaging:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
    finished:
      appearance:
        操作方法模板: appearance_visual
        操作方法参数:
          operation_prefix: 取本品，目测，本品为
