// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { requireRouteAccess } from "@workspace/platform/server/auth";
import { listCompanyDocuments } from "@workspace/docs/server/company-documents";
import { DocsCompanyPage as CompanyDocumentsPage } from "@workspace/docs/ui";

export default async function DocsCompanyPage() {
  const user = await requireRouteAccess("/docs/company");
  const documents = await listCompanyDocuments();
  return <CompanyDocumentsPage user={user} documents={documents} />;
}
