// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildScanReclassRulesCommand,
  buildSaveReclassRuleChangeSetRouteCommand,
  executeScanReclassRulesCommand,
  executeSaveReclassRuleChangeSetRouteCommand,
} from "@workspace/finance/server/ledger/route-commands";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const scanRulesQuerySchema = z.object({
  policyVersionId: z.coerce.number().int().positive().optional(),
});

const saveRulesSchema = z.object({
  policyVersionId: z.number().int().positive(),
  changes: z.array(z.object({
    sourceGroupAccountId: z.number().int().positive(),
    abnormalSide: z.enum(["debit", "credit", "both"]),
    targetGroupAccountId: z.number().int().positive().nullable(),
    basis: z.enum(["account_net", "counterparty_gross"]).nullish(),
  })).min(1).max(500),
});

export const GET = createCommandRoute({
  querySchema: scanRulesQuerySchema,
  buildCommand: ({ query }) => buildScanReclassRulesCommand(query.policyVersionId),
  action: executeScanReclassRulesCommand,
});

export const PUT = createCommandRoute({
  bodySchema: saveRulesSchema,
  bodyError: "changes 为必填",
  buildCommand: ({ body, user }) => buildSaveReclassRuleChangeSetRouteCommand({ ...body, userId: user.userId }),
  action: executeSaveReclassRuleChangeSetRouteCommand,
});
