DROP INDEX IF EXISTS "FinanceConsolidationEntryLine_companyId_statementType_lineC_idx";

ALTER INDEX "FinanceConsolidationEntryLine_entitySnapshotId_statementType_li"
  RENAME TO "FinanceConsolidationEntryLine_entitySnapshotId_statementTyp_idx";
