/** Closed semantic action vocabulary shared by Core UI and non-UI registries. */
export const ACTION_GLYPH_KINDS = [
  "add",
  "send",
  "stop",
  "edit",
  "revise",
  "withdraw",
  "check",
  "double-check",
  "approve",
  "reject",
  "verified",
  "cancel",
  "x",
  "copy",
  "save",
  "delete",
  "delete-bin",
  "delete-minus",
  "view",
  "eye-off",
  "back",
  "search",
  "filter",
  "refresh",
  "reset",
  "restore",
  "link",
  "unlink",
  "share",
  "settings",
  "reclass",
  "generate",
  "print",
  "lock",
  "unlock",
  "permission-organization",
  "permission-derived",
  "sort",
  "move-up",
  "move-down",
  "more",
  "download",
  "upload",
  "archive",
  "list",
  "history",
  "assistant",
  "tree-expand",
  "tree-collapse",
  "panel-open",
  "panel-close",
] as const;

export type ActionGlyphKind = (typeof ACTION_GLYPH_KINDS)[number];
export type ActionGlyphIconAlias = "back" | "create" | "open";
