// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { executeBudgetAnalysisCommand } from "@workspace/finance/server/analysis/route-commands";
import { createCommandRoute } from "@workspace/platform/server/api-route";import { okCommand } from "@workspace/platform/server/domain-validation";

const budgetAnalysisQuerySchema = z.object({
  year: z.coerce.number().int().min(2000).max(2099),
  companyCode: z.string().optional(),
});

export const GET = createCommandRoute({
  querySchema: budgetAnalysisQuerySchema,
  buildCommand: ({ query }) => okCommand(query),
  action: executeBudgetAnalysisCommand,
});
