// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  executeTaxReferenceOptionsCommand,
  taxReferenceOptionsQuerySchema,
} from "@workspace/finance/server/tax/reference-options";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

export const GET = createCommandRoute({
  querySchema: taxReferenceOptionsQuerySchema,
  queryError: "税务引用候选项参数无效",
  buildCommand: ({ query }) => okCommand(query),
  action: (command) => executeTaxReferenceOptionsCommand(command),
});
