// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { organizationArchiveLifecycleMetaFromRequest, updatePosition } from "@workspace/hr/server";
import { routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const archiveBodySchema = z.object({
  archived: z.boolean(),
  version: z.number().int().min(0),
  effectiveOn: z.string().optional(),
  reason: z.string().optional().nullable(),
});

export const POST = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "ID 无效",
  bodySchema: archiveBodySchema,
  bodyError: "参数错误",
  buildCommand: ({ request, params, body, user }) => okCommand({
    id: params.id,
    archived: body.archived,
    userId: user.userId,
    lifecycle: organizationArchiveLifecycleMetaFromRequest(request, body),
  }),
  action: ({ id, archived, lifecycle, userId }) => updatePosition(id, { isArchived: archived, lifecycle }, userId),
});
