// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { organizationStructureLifecycleMetaFromRequest, updatePosition } from "@workspace/hr/server";
import { readRequestExpectedVersion, routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const archiveBodySchema = z.object({
  archived: z.boolean(),
  effectiveOn: z.string().optional(),
  reason: z.string().optional().nullable(),
});

export const POST = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "ID 无效",
  bodySchema: archiveBodySchema,
  bodyError: "参数错误",
  buildCommand: ({ request, params, body, user }) => okCommand({
    id: params.id,
    archived: body.archived,
    userId: user.userId,
    lifecycle: organizationStructureLifecycleMetaFromRequest(request, {
      expectedSequence: readRequestExpectedVersion(request),
      effectiveOn: body.effectiveOn,
      kind: body.archived ? "end-date" : "schedule",
      reason: body.reason,
    }),
  }),
  action: ({ id, archived, lifecycle, userId }) => updatePosition(id, { isArchived: archived, lifecycle }, userId),
});
