// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { registerDeployUnitRuntime } from "@workspace/platform/server/deploy-unit-runtime";

export async function register() {
  await registerDeployUnitRuntime("work");
  if (process.env.NEXT_RUNTIME !== "nodejs") return;
  if (process.env.NEXT_PHASE === "phase-production-build") return;
  const { startProjectNotificationScheduler } = await import(
    "@workspace/work/server/project-notification-scheduler"
  );
  startProjectNotificationScheduler();
}
