// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";
import { z } from "zod";

import { jsonErrorResponse } from "@workspace/platform/server/api";
import { requireAdminApiAccess } from "@workspace/platform/server/auth";
import {
  canManageWorkflowBusinessAction,
  getWorkflowAdminAccess,
  hasWorkflowAdminAccess,
} from "@workspace/platform/server/workflow-admin-access";
import { listWorkflowLedgerRequests } from "@workspace/platform/server/workflow-ledger";

const workflowLedgerQuerySchema = z.object({
  businessActionKey: z.string().trim().optional().catch(undefined),
  status: z.string().trim().optional().catch(undefined),
  query: z.string().trim().optional().catch(undefined),
  page: z.coerce.number().int().min(0).optional().catch(0),
  pageSize: z.coerce.number().int().min(10).max(100).optional().catch(50),
}).passthrough();

async function requireWorkflowLedgerAdmin(request: Request) {
  const auth = await requireAdminApiAccess(request);
  if (!auth.ok) return auth;
  const access = await getWorkflowAdminAccess(auth.user.userId);
  if (!hasWorkflowAdminAccess(access)) return { ok: false as const, response: jsonErrorResponse("无权限", 403) };
  return { ...auth, access };
}

export async function GET(request: Request) {
  const auth = await requireWorkflowLedgerAdmin(request);
  if (!auth.ok) return auth.response;

  const url = new URL(request.url);
  const parsed = workflowLedgerQuerySchema.safeParse(Object.fromEntries(url.searchParams.entries()));
  if (!parsed.success) return jsonErrorResponse("流程台账查询参数无效", 400);
  if (
    parsed.data.businessActionKey &&
    !canManageWorkflowBusinessAction(auth.access, parsed.data.businessActionKey)
  ) return jsonErrorResponse("无权限查看该流程", 403);

  return NextResponse.json(await listWorkflowLedgerRequests({
    ...parsed.data,
    allowedBusinessActionKeys: auth.access.allowedBusinessActionKeys,
  }));
}
