// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { buildHrAuditLogCommand, executeHrAuditLogCommand } from "@workspace/hr/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";const auditLogQuerySchema = z.object({
  entityType: z.string().min(1),
  date: z.string().optional(),
  dates: z.string().optional(),
  page: z.coerce.number().int().min(1).catch(1),
  pageSize: z.coerce.number().int().min(1).max(200).catch(50),
});

export const GET = createCommandRoute({
  querySchema: auditLogQuerySchema,
  queryError: "缺少 entityType",
  buildCommand: ({ query }) => buildHrAuditLogCommand(query),
  action: executeHrAuditLogCommand,
});
