// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { requireRouteAccess } from "@workspace/platform/server/auth";
import { DocsEditorTemplateDetailPage } from "@workspace/docs/ui";

export default async function DocsEditorTemplateDetailRoute({
  params,
}: {
  params: Promise<{ templateId: string }>;
}) {
  const { templateId } = await params;
  const user = await requireRouteAccess("/docs/editor");
  return DocsEditorTemplateDetailPage({ templateId: decodeURIComponent(templateId), user });
}
