// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  buildCapitalSecuritiesWorkspaceAnalysisSourceCatalog,
  canDiscoverCapitalSecuritiesWorkspaceAnalysisSource,
  loadCapitalSecuritiesWorkspaceAnalysisSource,
} from "@workspace/capital-securities/server";
import { createWorkspaceAnalysisSourceRpcHandler } from "@workspace/platform/server/workspace-analysis-source-rpc";

export const POST = createWorkspaceAnalysisSourceRpcHandler({
  ownerUnitId: "capital-securities",
  allowedCallerUnitIds: ["finance"],
  sourceCatalog: buildCapitalSecuritiesWorkspaceAnalysisSourceCatalog(),
  canDiscover: canDiscoverCapitalSecuritiesWorkspaceAnalysisSource,
  executeSource: loadCapitalSecuritiesWorkspaceAnalysisSource,
});
