import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import test from "node:test";

import {
  collectRegisteredGeneratedSourceTargets,
  collectSourceFiles,
  type GeneratedSourceRegistration,
  isGeneratedSource,
  isRegisteredGeneratedSourcePath,
} from "./source-files";

test("source discovery includes handwritten generated directories and root instrumentation", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "source-files-"));
  try {
    const generatedDirectory = path.join(root, "packages/hr/ui/generated");
    await mkdir(generatedDirectory, { recursive: true });
    await writeFile(path.join(generatedDirectory, "RosterGeneratedTab.tsx"), "export const tab = true;\n", "utf8");
    await writeFile(path.join(root, "instrumentation.ts"), "export function register() {}\n", "utf8");

    assert.deepEqual(await collectSourceFiles(root), [
      "instrumentation.ts",
      "packages/hr/ui/generated/RosterGeneratedTab.tsx",
    ]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("registered generated roots index actual source targets and explain missing output", async () => {
  const root = await mkdtemp(path.join(tmpdir(), "generated-targets-"));
  try {
    await mkdir(path.join(root, "generated/prisma/models"), { recursive: true });
    await writeFile(path.join(root, "generated/prisma/client.ts"), "export const client = true;\n", "utf8");
    await writeFile(path.join(root, "generated/prisma/models/index.ts"), "export {};\n", "utf8");
    await writeFile(path.join(root, "generated/prisma/README.md"), "generated output\n", "utf8");

    const targets = await collectRegisteredGeneratedSourceTargets(root);
    assert.deepEqual([...targets].sort(), [
      "generated/prisma/client.ts",
      "generated/prisma/models/index.ts",
    ]);
    await assert.rejects(
      collectRegisteredGeneratedSourceTargets(root, [], [{
        prefix: "generated/missing/",
        verificationCommand: "npm run missing:generate",
      }]),
      /generated\/missing\/; run npm run missing:generate/,
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("only registered generated source with its exact marker is excluded", () => {
  const registration = {
    path: "packages/example/generated-contract.ts",
    marker: "// Auto-generated by scripts/generate-example.ts",
    verificationCommand: "npm run example:generate",
  } satisfies GeneratedSourceRegistration;
  assert.ok(registration.verificationCommand);
  assert.equal(isRegisteredGeneratedSourcePath(registration.path.replace(/\.ts$/, ""), [registration]), true);
  assert.equal(isRegisteredGeneratedSourcePath("generated/prisma"), true);
  assert.equal(isRegisteredGeneratedSourcePath("generated/prismatic"), false);
  assert.equal(isGeneratedSource(registration.path, `${registration.marker}\nexport {};\n`, [registration]), true);
  assert.equal(isGeneratedSource("packages/hr/ui/generated/Handwritten.ts", "export const value = true;\n"), false);
  assert.throws(
    () => isGeneratedSource("packages/work/generated/hidden.ts", "// Generated file\nexport {};\n"),
    /generated source is not registered/,
  );
  assert.throws(
    () => isGeneratedSource(registration.path, "// Auto-generated by another generator\nexport {};\n", [registration]),
    /registered generated source marker mismatch/,
  );
});
