// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
export default function HRLoading() {
  return (
    <div className="flex min-h-screen items-center justify-center">
      <p className="text-gray-500">加载中...</p>
    </div>
  );
}
