// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  getMarketIntelligenceSnapshot,
  searchMarketStockCatalog,
} from "@workspace/capital-securities/server";
import { createApiRouteHandler } from "@workspace/platform/server/api-route";

const querySchema = z.object({
  catalog: z.literal("stocks").optional(),
  q: z.string().trim().max(80).optional(),
  market: z.enum(["CN", "HK", "US"]).optional(),
  ids: z.string().trim().max(1_000).optional(),
  stocks: z.string().trim().max(4_000).optional().transform((value, context) => {
    if (!value) return [] as unknown[];
    try {
      const parsed: unknown = JSON.parse(value);
      if (Array.isArray(parsed)) return parsed;
    } catch {
      // Report the same bounded query-shape error below.
    }
    context.addIssue({ code: "custom", message: "股票订阅参数必须是数组" });
    return z.NEVER;
  }),
}).strict();

export const GET = createApiRouteHandler({
  querySchema,
  queryError: "市场订阅参数无效",
  handler: async ({ query }) => query.catalog === "stocks"
    ? searchMarketStockCatalog({ query: query.q ?? "", market: query.market })
    : getMarketIntelligenceSnapshot({
      instrumentIds: query.ids?.split(",") ?? [],
      stocks: query.stocks,
    }),
});
