methods:
  HPLC简表:
    色谱:
    - name: 对照1-峰面积
      type: number
      attr: fillable
    - name: 对照2-峰面积
      type: number
      attr: fillable
    - name: 对照平均峰面积
      type: number
      attr: calculated
      formula: (对照1-峰面积 + 对照2-峰面积) / 2
    - name: 对照RSD
      unit: '%'
      type: number
      attr: calculated
      formula: SQRT(((对照1-峰面积 - 对照平均峰面积)^2 + (对照2-峰面积 - 对照平均峰面积)^2) / 1) / 对照平均峰面积 * 100
    - name: 样1-峰面积
      type: number
      attr: fillable
    - name: 样1-平均峰面积
      type: number
      attr: calculated
      formula: 样1-峰面积
    - name: 样1-含量
      unit: '%'
      type: number
      attr: fillable
    - name: 样2-峰面积
      type: number
      attr: fillable
    - name: 样2-平均峰面积
      type: number
      attr: calculated
      formula: 样2-峰面积
    - name: 样2-含量
      unit: '%'
      type: number
      attr: fillable
    - name: 平均含量
      unit: '%'
      type: number
      attr: calculated
      formula: (样1-含量 + 样2-含量) / 2
    - name: RD
      unit: '%'
      type: number
      attr: calculated
      formula: ABS(样1-含量 - 样2-含量) / 平均含量 * 100
  HPLC:
    称重:
    - name: 对照含量
      unit: '%'
      type: number
      attr: fillable
    - name: 平均片重
      unit: g
      type: number
      attr: fillable
    - name: 对照1-毛重
      unit: mg
      type: number
      attr: fillable
    - name: 对照1-皮重
      unit: mg
      type: number
      attr: fillable
    - name: 对照1-净重
      unit: mg
      type: number
      attr: calculated
      formula: 对照1-毛重 - 对照1-皮重
    - name: 对照2-毛重
      unit: mg
      type: number
      attr: fillable
    - name: 对照2-皮重
      unit: mg
      type: number
      attr: fillable
    - name: 对照2-净重
      unit: mg
      type: number
      attr: calculated
      formula: 对照2-毛重 - 对照2-皮重
    - name: 样1-毛重
      unit: mg
      type: number
      attr: fillable
    - name: 样1-皮重
      unit: mg
      type: number
      attr: fillable
    - name: 样1-净重
      unit: mg
      type: number
      attr: calculated
      formula: 样1-毛重 - 样1-皮重
    - name: 样2-毛重
      unit: mg
      type: number
      attr: fillable
    - name: 样2-皮重
      unit: mg
      type: number
      attr: fillable
    - name: 样2-净重
      unit: mg
      type: number
      attr: calculated
      formula: 样2-毛重 - 样2-皮重
    色谱:
    - name: 色谱柱
      type: text
      attr: prefilled
    - name: 对照1-峰面积1
      type: number
      attr: fillable
    - name: 对照1-单位峰面积1
      type: number
      attr: calculated
      formula: 对照1-峰面积1 / 对照1-净重
    - name: 对照1-峰面积2
      type: number
      attr: fillable
    - name: 对照1-单位峰面积2
      type: number
      attr: calculated
      formula: 对照1-峰面积2 / 对照1-净重
    - name: 对照1-峰面积3
      type: number
      attr: fillable
    - name: 对照1-单位峰面积3
      type: number
      attr: calculated
      formula: 对照1-峰面积3 / 对照1-净重
    - name: 对照2-峰面积1
      type: number
      attr: fillable
    - name: 对照2-单位峰面积1
      type: number
      attr: calculated
      formula: 对照2-峰面积1 / 对照2-净重
    - name: 对照2-峰面积2
      type: number
      attr: fillable
    - name: 对照2-单位峰面积2
      type: number
      attr: calculated
      formula: 对照2-峰面积2 / 对照2-净重
    - name: 对照2-峰面积3
      type: number
      attr: fillable
    - name: 对照2-单位峰面积3
      type: number
      attr: calculated
      formula: 对照2-峰面积3 / 对照2-净重
    - name: 对照平均单位峰面积
      type: number
      attr: calculated
      formula: (对照1-单位峰面积1 + 对照1-单位峰面积2 + 对照1-单位峰面积3 + 对照2-单位峰面积1 + 对照2-单位峰面积2 + 对照2-单位峰面积3) / 6
    - name: 对照RSD
      unit: '%'
      type: number
      attr: calculated
      formula: SQRT(((对照1-单位峰面积1 - 对照平均单位峰面积)^2 + (对照1-单位峰面积2 - 对照平均单位峰面积)^2 + (对照1-单位峰面积3 - 对照平均单位峰面积)^2 + (对照2-单位峰面积1 - 对照平均单位峰面积)^2 + (对照2-单位峰面积2 - 对照平均单位峰面积)^2 + (对照2-单位峰面积3 - 对照平均单位峰面积)^2) / 5) / 对照平均单位峰面积 * 100
    - name: 样1-峰面积1
      type: number
      attr: fillable
    - name: 样1-峰面积2
      type: number
      attr: fillable
    - name: 样1-平均峰面积
      type: number
      attr: calculated
      formula: (样1-峰面积1 + 样1-峰面积2) / 2
    - name: 样1-RD
      unit: '%'
      type: number
      attr: calculated
      formula: ABS(样1-峰面积1 - 样1-峰面积2) / 样1-平均峰面积 * 100
    - name: 样1-含量
      unit: '%'
      type: number
      attr: calculated
      formula: 样1-平均峰面积 * 2 * 对照含量 * 平均片重 * 1000 / (样1-净重 * 对照平均单位峰面积 * 25) * 100
    - name: 样2-峰面积1
      type: number
      attr: fillable
    - name: 样2-峰面积2
      type: number
      attr: fillable
    - name: 样2-平均峰面积
      type: number
      attr: calculated
      formula: (样2-峰面积1 + 样2-峰面积2) / 2
    - name: 样2-RD
      unit: '%'
      type: number
      attr: calculated
      formula: ABS(样2-峰面积1 - 样2-峰面积2) / 样2-平均峰面积 * 100
    - name: 样2-含量
      unit: '%'
      type: number
      attr: calculated
      formula: 样2-平均峰面积 * 2 * 对照含量 * 平均片重 * 1000 / (样2-净重 * 对照平均单位峰面积 * 25) * 100
    - name: 平均含量
      unit: '%'
      type: number
      attr: calculated
      formula: (样1-含量 + 样2-含量) / 2
    - name: RD
      unit: '%'
      type: number
      attr: calculated
      formula: ABS(样1-含量 - 样2-含量) / 平均含量 * 100
  含量均匀度简表:
    测定:
    - repeat:
        count: 10
        fields:
        - name: 样{序号}-含量
          unit: '%'
          type: number
          attr: fillable
    - name: 平均含量
      unit: '%'
      type: number
      attr: calculated
      formula: (样1-含量 + 样2-含量 + 样3-含量 + 样4-含量 + 样5-含量 + 样6-含量 + 样7-含量 + 样8-含量 + 样9-含量 + 样10-含量) / 10
    - name: S
      type: number
      attr: calculated
      formula: SQRT(((样1-含量 - 平均含量)^2 + (样2-含量 - 平均含量)^2 + (样3-含量 - 平均含量)^2 + (样4-含量 - 平均含量)^2 + (样5-含量 - 平均含量)^2 + (样6-含量 - 平均含量)^2 + (样7-含量 - 平均含量)^2 + (样8-含量 - 平均含量)^2 + (样9-含量 - 平均含量)^2 + (样10-含量 - 平均含量)^2) / 9)
    - name: A_2.2S
      type: number
      attr: calculated
      formula: ABS(100 - 平均含量) + 2.2 * S
  含量均匀度:
    extends: HPLC
    extra:
    - repeat:
        count: 10
        fields:
        - name: 样{序号}-OD
          type: number
          attr: fillable
        - name: 样{序号}-含量
          unit: '%'
          type: number
          attr: fillable
    - name: 平均含量
      unit: '%'
      type: number
      attr: calculated
      formula: (样1-含量 + 样2-含量 + 样3-含量 + 样4-含量 + 样5-含量 + 样6-含量 + 样7-含量 + 样8-含量 + 样9-含量 + 样10-含量) / 10
    - name: S
      type: number
      attr: calculated
      formula: SQRT(((样1-含量 - 平均含量)^2 + (样2-含量 - 平均含量)^2 + (样3-含量 - 平均含量)^2 + (样4-含量 - 平均含量)^2 + (样5-含量 - 平均含量)^2 + (样6-含量 - 平均含量)^2 + (样7-含量 - 平均含量)^2 + (样8-含量 - 平均含量)^2 + (样9-含量 - 平均含量)^2 + (样10-含量 - 平均含量)^2) / 9)
    - name: A_2.2S
      type: number
      attr: calculated
      formula: ABS(100 - 平均含量) + 2.2 * S
