methods:
  微生物限度-计数法:
    需氧菌:
    - name: 培养基
      type: text
      attr: prefilled
    - name: 培养温度
      unit: ℃
      type: number
      attr: fillable
    - name: 培养天数
      unit: 天
      type: number
      attr: fillable
    - name: 稀释度
      type: select
      options:
      - '1:10'
      - 1:100
      - 1:1000
      attr: fillable
    - name: 稀释倍数
      type: number
      attr: fillable
      note: 与稀释度对应，1:10 填 10，1:100 填 100，1:1000 填 1000
    - name: 皿数
      type: number
      attr: fillable
    - name: 菌落数1
      type: number
      attr: fillable
    - name: 菌落数2
      type: number
      attr: fillable
    - name: 平均菌落数
      type: number
      attr: calculated
      formula: (菌落数1 + 菌落数2) / 2
    - name: 需氧菌总数
      unit: cfu/g
      type: number
      attr: calculated
      formula: 平均菌落数 * 稀释倍数
    霉菌酵母菌:
    - name: 培养基
      type: text
      attr: prefilled
    - name: 培养温度
      unit: ℃
      type: number
      attr: fillable
    - name: 培养天数
      unit: 天
      type: number
      attr: fillable
    - name: 稀释倍数
      type: number
      attr: fillable
      note: 与稀释度对应，1:10 填 10，1:100 填 100，1:1000 填 1000
    - name: 皿数
      type: number
      attr: fillable
    - name: 菌落数1
      type: number
      attr: fillable
    - name: 菌落数2
      type: number
      attr: fillable
    - name: 平均菌落数
      type: number
      attr: calculated
      formula: (菌落数1 + 菌落数2) / 2
    - name: 霉菌酵母菌总数
      unit: cfu/g
      type: number
      attr: calculated
      formula: 平均菌落数 * 稀释倍数
  微生物限度-控制菌:
    大肠埃希菌:
    - name: 阳性对照
      type: select
      options:
      - 阳性
      - 阴性
      attr: fillable
    - name: 阴性对照
      type: select
      options:
      - 阳性
      - 阴性
      attr: fillable
    - name: 供试品结果
      type: select
      options:
      - 检出
      - 未检出
      attr: fillable
