methods:
  水分:
  - name: 称样1
    unit: g
    type: number
    attr: fillable
  - name: 水分1
    unit: '%'
    type: number
    attr: fillable
  - name: 称样2
    unit: g
    type: number
    attr: fillable
  - name: 水分2
    unit: '%'
    type: number
    attr: fillable
  - name: 平均水分
    unit: '%'
    type: number
    attr: calculated
    formula: (水分1 + 水分2) / 2
  - name: RD
    unit: '%'
    type: number
    attr: calculated
    formula: ABS(水分1 - 水分2) / 平均水分 * 100
  崩解时限:
  - name: 介质体积
    unit: ml
    type: number
    attr: fillable
  - name: 介质温度
    unit: ℃
    type: number
    attr: prefilled
    value: 37
  - name: 标准时限
    unit: 分钟
    type: number
    attr: prefilled
  - repeat:
      count: 6
      fields:
      - name: 片{序号}-崩解时间
        unit: 分秒
        type: text
        attr: fillable
      - name: 片{序号}-结果
        type: select
        options:
        - 符合
        - 不符合
        attr: fillable
  目测:
  - name: 外观描述
    type: text
    attr: fillable
