// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { okCommand } from "@workspace/platform/server/domain-validation";import { createCommandRoute } from "@workspace/platform/server/api-route";
import { listBudgetVersions, createBudgetVersion } from "@workspace/finance/server/budget/budget-version";
import {
  budgetVersionQuerySchema,
  createBudgetVersionSchema,
} from "@workspace/finance/server/budget/schemas";

export const GET = createCommandRoute({
  querySchema: budgetVersionQuerySchema,
  queryError: "参数无效",
  buildCommand: ({ query }) => okCommand(query),
  action: async (command) => ({
    versions: await listBudgetVersions(command.year, command.companyCode),
  }),
});

export const POST = createCommandRoute({
  bodySchema: createBudgetVersionSchema,
  bodyError: "year 和 name 为必填",
  buildCommand: ({ body }) => okCommand(body),
  action: async (command) => ({ version: await createBudgetVersion(command) }),
});
