// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { okCommand } from "@workspace/platform/server/domain-validation";import { createCommandRoute } from "@workspace/platform/server/api-route";
import { costQuerySchema, listCostAnalysis, getCostAnalysisSummary } from "@workspace/finance/server/cost";

export const GET = createCommandRoute({
  querySchema: costQuerySchema,
  queryError: "参数无效",
  buildCommand: ({ query }) => okCommand(query),
  action: async (command) => {
    const [list, summary] = await Promise.all([
      listCostAnalysis(command),
      getCostAnalysisSummary(command),
    ]);
    return { success: true, ...list, summary };
  },
});
