export {
  copyTemplate,
  deleteDraft,
  getEditorBootstrap,
  getTemplate,
  listSpaces,
  listTemplates,
  markPublished,
  requestPublish,
  saveDraft,
  updatePermissions,
} from "./service";
export {
  copyDocumentTemplate,
  createDocumentTemplate,
  deleteDocumentTemplateDraft,
  DocsEditorServiceError,
  getDocsEditorBootstrap,
  getDocumentTemplate,
  listDocumentTemplateSpaces,
  listDocumentTemplates,
  markDocumentTemplatePublished,
  requestDocumentTemplatePublish,
  saveDocumentTemplateDraft,
  updateDocumentTemplatePermissions,
} from "./facade";
export type {
  DocsEditorBootstrapDto,
  DocsEditorPermissionRole,
  DocsEditorSpaceDto,
  DocsEditorSpaceKind,
  DocsEditorTemplateDetailDto,
  DocsEditorTemplateListItemDto,
  DocsEditorTemplateStatus,
  DocumentTemplateBootstrapDto,
  DocumentTemplateDetailDto,
  DocumentTemplateListItemDto,
  DocumentTemplatePermissionDto,
  DocumentTemplateRole,
  DocumentTemplateSpaceDto,
  DocumentTemplateSpaceKind,
  DocumentTemplateStatus,
} from "./types";
