// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { listOpenApiConsoleData, withOpenApiConsoleAccess } from "@workspace/platform/server/open-api";

export const GET = withOpenApiConsoleAccess(async () => {
  return Response.json(await listOpenApiConsoleData());
});
