import * as fs from "node:fs";
import * as path from "node:path";
import * as ts from "typescript";
import { registeredCoreUiComponentNames } from "../packages/core/ui/component-registry";

const previewDir = path.resolve(__dirname, "../packages/core/showcase/previews");
const files = fs
  .readdirSync(previewDir)
  .filter((file) => file.endsWith("-previews.tsx"));

const registryNames = registeredCoreUiComponentNames;
const previewCaseByName: Record<string, string[]> = {};

for (const file of files) {
  const sourcePath = path.join(previewDir, file);
  const sourceText = fs.readFileSync(sourcePath, "utf8");
  const sourceFile = ts.createSourceFile(
    sourcePath,
    sourceText,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX,
  );

  ts.forEachChild(sourceFile, (node) => {
    let componentName: string | null = null;
    let body: ts.Node | undefined;

    if (ts.isFunctionDeclaration(node) && node.name?.text.endsWith("Preview")) {
      componentName = node.name.text.slice(0, -"Preview".length);
      body = node.body;
    } else if (ts.isVariableStatement(node)) {
      for (const declaration of node.declarationList.declarations) {
        if (!ts.isIdentifier(declaration.name)) continue;
        const name = declaration.name.text;
        if (!name.endsWith("Preview")) continue;
        const initializer = declaration.initializer;
        if (
          initializer &&
          (ts.isArrowFunction(initializer) || ts.isFunctionExpression(initializer))
        ) {
          componentName = name.slice(0, -"Preview".length);
          body = initializer.body;
        }
      }
    }

    if (!componentName || !body || !registryNames.has(componentName)) return;

    const cases = new Set<string>();
    function visit(child: ts.Node) {
      if (ts.isJsxElement(child) || ts.isJsxSelfClosingElement(child)) {
        const opening = ts.isJsxElement(child) ? child.openingElement : child;
        const tagName = opening.tagName;
        if (ts.isIdentifier(tagName) && registryNames.has(tagName.text)) {
          if (tagName.text !== componentName) {
            cases.add(tagName.text);
            // 只统计顶层引用的注册组件；注册组件内部再嵌套的子组件不算“额外案例”
            opening.attributes.properties.forEach((attr) => visit(attr));
            return;
          }
          // 根预览组件本身不计入，但继续遍历它的子树，找到它下面直接使用的其他组件
        }
      }
      ts.forEachChild(child, visit);
    }
    visit(body);

    if (cases.size > 0) {
      previewCaseByName[componentName] = [...cases].sort();
    }
  });
}

const entries = Object.entries(previewCaseByName).sort(([a], [b]) =>
  a.localeCompare(b),
);
const lines = entries.map(
  ([name, cases]) =>
    `  "${name}": [${cases.map((c) => `"${c}"`).join(", ")}],`,
);
const output = `// Auto-generated by scripts/generate-preview-cases.ts
// Lists extra Core UI components referenced inside each live preview.
export const previewCaseByName: Record<string, readonly string[]> = {
${lines.join("\n")}
};
`;

const outputPath = path.join(previewDir, "preview-cases.ts");
fs.writeFileSync(outputPath, output, "utf8");
console.log(`Generated preview cases for ${entries.length} previews -> ${outputPath}`);
