#!/usr/bin/env tsx

import fs from "node:fs";
import path from "node:path";
import type { ActionContractMetadata } from "../packages/platform/action-contract";
import { listActionContractMetadata } from "../packages/platform/action-contract-registry";

const OUTPUT_PATH = path.resolve(import.meta.dirname, "../docs/generated/action-contracts.md");

function cell(value: unknown) {
  return String(value ?? "—")
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, "<br>");
}

function routes(contract: ActionContractMetadata) {
  const values = [
    contract.api.commandRoute ? `command: ${contract.api.commandRoute}` : null,
    ...(contract.api.directRoutes ?? []).map((route) => `direct: ${route}`),
    ...(contract.api.workflowRoutes ?? []).map((route) => `workflow: ${route}`),
  ].filter((value): value is string => Boolean(value));
  return [...new Set(values)].join("<br>") || "—";
}

function domain(contract: ActionContractMetadata) {
  const bindings = "bindings" in contract.domain && contract.domain.bindings
    ? contract.domain.bindings
    : [contract.domain];
  return bindings.map((binding) => {
    const validator = binding.validatorKey ? `validate=${binding.validatorKey}` : "validate=identity";
    if ("commitKey" in binding) return `${validator}<br>commit=${binding.commitKey}`;
    return `${validator}<br>execute=${binding.executeKey}`;
  }).join("<br>---<br>");
}

function persistence(contract: ActionContractMetadata) {
  if (!contract.persistence) return "none (read-only export)";
  const value = contract.persistence;
  return [
    `strategy=${value.strategy}`,
    value.activeEntity ? `active=${value.activeEntity}` : null,
    value.draftEntity ? `draft=${value.draftEntity}` : null,
    `mode=${value.commitMode}`,
  ].filter(Boolean).join("<br>");
}

function semantics(contract: ActionContractMetadata) {
  if (contract.kind === "lifecycle") {
    return [
      `operation=${contract.lifecycle.operation}`,
      `reference=${contract.lifecycle.referencePolicy}`,
      `audit=${contract.lifecycle.auditPolicy}`,
    ].join("<br>");
  }
  if (contract.kind === "governance") {
    return [
      `subject=${contract.governance.subject}`,
      `scope=${contract.governance.scope}`,
      `audit=${contract.governance.auditPolicy}`,
    ].join("<br>");
  }
  if (contract.kind === "exchange") {
    return [
      `direction=${contract.exchange.direction}`,
      `transport=${contract.exchange.transport}`,
      `result=${contract.exchange.result}`,
      "atomicity" in contract.exchange ? `atomicity=${contract.exchange.atomicity}` : null,
    ].filter(Boolean).join("<br>");
  }
  return `payload=${contract.payload.cardinality}/${contract.payload.shape}<br>target=${contract.payload.target}`;
}

function workflow(contract: ActionContractMetadata) {
  if (contract.workflow.kind === "not_applicable") return `not_applicable<br>${contract.workflow.reason}`;
  return [
    contract.workflow.kind,
    `default=${contract.workflow.defaultExecutionMode}`,
    `canDisable=${contract.workflow.canDisable}`,
    `whenDisabled=${contract.workflow.whenDisabled}`,
    `entry=${contract.workflow.entrySemantics}`,
    `nodes=${contract.workflow.defaultDefinition.nodes.length}`,
  ].join("<br>");
}

function moduleKey(contract: ActionContractMetadata) {
  return contract.resource.moduleKey ?? contract.key.split(".")[0] ?? "other";
}

export function renderActionContractDocs(contracts: readonly ActionContractMetadata[]) {
  const sorted = [...contracts].sort((left, right) => left.key.localeCompare(right.key));
  const groups = new Map<string, ActionContractMetadata[]>();
  for (const contract of sorted) groups.set(moduleKey(contract), [...groups.get(moduleKey(contract)) ?? [], contract]);
  const kindCounts = new Map<string, number>();
  const workflowCounts = new Map<string, number>();
  for (const contract of sorted) {
    const semanticKind = contract.kind === "exchange" ? `${contract.kind}:${contract.exchange.direction}` : contract.kind;
    kindCounts.set(semanticKind, (kindCounts.get(semanticKind) ?? 0) + 1);
    workflowCounts.set(contract.workflow.kind, (workflowCounts.get(contract.workflow.kind) ?? 0) + 1);
  }

  const lines = [
    "<!-- AUTO-GENERATED by scripts/generate-action-contract-docs.ts. DO NOT EDIT. -->",
    "",
    "# ActionContract Registry",
    "",
    `**${sorted.length} contracts** across ${groups.size} modules.`,
    "",
    `Kinds: ${[...kindCounts].map(([key, count]) => `${key}=${count}`).join(" · ")}`,
    "",
    `Workflow: ${[...workflowCounts].map(([key, count]) => `${key}=${count}`).join(" · ")}`,
    "",
    "Contract facts come from `packages/platform/action-contract-registry.ts` and its composed registries. Route bindings and referenced runtime symbols are enforced by `npm run action-contract:check`.",
    "",
  ];

  for (const [group, entries] of [...groups].sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`## ${group}`, "");
    lines.push("| Action | Kind / target | Resource | Routes | Domain binding | Persistence / semantics | Workflow |");
    lines.push("|---|---|---|---|---|---|---|");
    for (const contract of entries) {
      lines.push(`| ${cell(`\`${contract.key}\`<br>${contract.label}`)} | ${cell(`${contract.kind}<br>${contract.targetKind ?? "—"}`)} | ${cell(`\`${contract.resource.resourceKey}\`<br>direct=${contract.resource.directPermissionAction ?? "—"}`)} | ${cell(routes(contract))} | ${cell(domain(contract))} | ${cell(`${persistence(contract)}<br>---<br>${semantics(contract)}`)} | ${cell(workflow(contract))} |`);
    }
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

function main() {
  const rendered = renderActionContractDocs(listActionContractMetadata());
  if (process.argv.includes("--check")) {
    const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : "";
    if (current !== rendered) {
      process.stderr.write("Generated ActionContract documentation is stale. Run `npm run docs:action-contracts`.\n");
      process.exit(1);
    }
    process.stdout.write("✓ Generated ActionContract documentation is current.\n");
    return;
  }
  fs.writeFileSync(OUTPUT_PATH, rendered, "utf8");
  process.stdout.write(`Generated ${path.relative(process.cwd(), OUTPUT_PATH)} (${listActionContractMetadata().length} contracts).\n`);
}

if (import.meta.url === `file://${process.argv[1]}`) main();
