#!/usr/bin/env tsx

import "dotenv/config";
import fs from "node:fs";
import path from "node:path";

const REPO_ROOT = path.resolve(import.meta.dirname, "..");
const CATALOG_OUTPUT = path.join(REPO_ROOT, "docs/generated/agent-doc-catalog.md");
const PRODUCT_GUIDES = new Map([
  ["business-code-rules", path.join(REPO_ROOT, "docs/product/business-code-rules.md")],
  ["external-related-parties", path.join(REPO_ROOT, "docs/product/external-related-parties.md")],
  ["hr-employment-contracts", path.join(REPO_ROOT, "docs/product/hr-employment-contracts.md")],
]);

function renderCatalog() {
  return `<!-- AUTO-GENERATED by scripts/generate-production-agent-docs.ts. DO NOT EDIT. -->

# Workspace Agent 文档目录

## 目录

| 需要解决的问题 | 文档 key | 先调用 |
|---|---|---|
| 不知道有哪些生产文档 | \`agent-doc-catalog\` | \`GET /api/modules/docs/company/documents\` |
| 不确定 API、认证、写入确认或展示模板创建 | \`api-agent-guide\` | \`GET /api/modules/docs/company/documents/api-agent-guide\` |
| 不确定 resource/action、继承或 BusinessAction 绑定 | \`permission-actions\` | \`GET /api/modules/docs/company/permission-actions\` |
| 不确定业务编码规则 | \`business-code-rules\` | \`GET /api/modules/docs/company/documents/business-code-rules\` |
| 不确定关联方身份与维护边界 | \`external-related-parties\` | \`GET /api/modules/docs/company/documents/external-related-parties\` |
| 不确定员工用工关系、协议或社保语义 | \`hr-employment-contracts\` | \`GET /api/modules/docs/company/documents/hr-employment-contracts\` |

## Agent 查询方式

1. 先调用 \`GET /api/modules/docs/company/documents\`，只读取文档目录，不一次加载全部正文。
2. 对目标 paper 文档调用 \`GET /api/modules/docs/company/documents/:key\`，取得章节 key、层级和摘要。
3. 已知章节时追加 \`?section=:sectionKey\`，只取这一节正文；只知道关键词时使用 \`?q=:query\` 搜索章节摘要。
4. 权限问题优先使用 \`/api/modules/docs/company/permission-actions\` 的结构化过滤参数，不要扫描整本权限手册。
5. 页面阅读入口是 \`/docs/company\`。所有入口都要求登录或有效个人 API Key，不是匿名公网文档。

## 使用边界

生产 Docs 发布产品用语、操作契约、API 调用顺序和权限知识，不发布源码路径、数据库表清单、迁移、部署、密钥、内部 RPC 或工程架构细节。文档只能帮助理解；当前用户 API Catalog、目标空间 contract、source discovery、RBAC 和 service guard 仍是每次调用的实时权威。

## 无法找到答案时

不要根据页面形态猜测“没有 API”或“只能由浏览器 Agent 操作”。先查 API Catalog，再查本目录和目标文档章节；仍没有登记时，明确报告缺少 contract 或文档，不得改用浏览器自动化、内部 URL 或源码路径绕过权限。
`;
}

function assertStartsWithDirectory(documentKey: string, markdown: string) {
  const source = markdown.replace(/^<!--.*?-->\s*/s, "");
  if (!/^# .+\n\n## 目录\n/m.test(source)) {
    throw new Error(`Production Agent document must start with ## 目录: ${documentKey}`);
  }
}

function configuredTargets(catalog: string) {
  const configuredRoot = process.env.WORKSPACE_CONFIG_DIR?.trim();
  if (!configuredRoot || !path.isAbsolute(configuredRoot)) return [];
  const root = fs.realpathSync(configuredRoot);
  const profilePath = path.join(root, "config/tenant/profile.json");
  if (!fs.existsSync(profilePath)) return [];
  const profile = JSON.parse(fs.readFileSync(profilePath, "utf8")) as {
    docs?: { companyDocuments?: Array<{ key?: string; source?: string; file?: string }> };
  };
  return (profile.docs?.companyDocuments ?? []).flatMap((document) => {
    if (!document.file || !document.key) return [];
    let content: string | null = null;
    if (document.source === "agent-doc-catalog") content = catalog;
    if (document.source === "product-guide") {
      const sourcePath = PRODUCT_GUIDES.get(document.key);
      if (!sourcePath) throw new Error(`Unknown product-guide document key: ${document.key}`);
      content = fs.readFileSync(sourcePath, "utf8");
    }
    if (content === null) return [];
    assertStartsWithDirectory(document.key, content);
    const target = path.resolve(root, document.file);
    if (target !== root && !target.startsWith(`${root}${path.sep}`)) {
      throw new Error(`Configured production Agent document escapes WORKSPACE_CONFIG_DIR: ${document.file}`);
    }
    return [{ key: document.key, target, content }];
  });
}

function main() {
  const catalog = renderCatalog();
  assertStartsWithDirectory("agent-doc-catalog", catalog);
  for (const [key, sourcePath] of PRODUCT_GUIDES) {
    assertStartsWithDirectory(key, fs.readFileSync(sourcePath, "utf8"));
  }
  const targets = [
    { key: "agent-doc-catalog", target: CATALOG_OUTPUT, content: catalog },
    ...configuredTargets(catalog),
  ];
  if (process.argv.includes("--check")) {
    const stale = targets.filter(({ target, content }) => (
      !fs.existsSync(target) || fs.readFileSync(target, "utf8") !== content
    ));
    if (stale.length) {
      process.stderr.write("Production Agent Docs are stale. Run `npm run docs:production-agent`.\n");
      stale.forEach(({ target }) => process.stderr.write(`- ${target}\n`));
      process.exit(1);
    }
    process.stdout.write("✓ Production Agent Docs are current and start with structured directories.\n");
    return;
  }
  targets.forEach(({ target, content }) => {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content, "utf8");
  });
  process.stdout.write(`Generated ${targets.map(({ target }) => path.relative(process.cwd(), target)).join(", ")}.\n`);
}

main();
