// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";

import { requireApiAccess } from "@workspace/platform/server/auth";
import { listCompanyDirectoryOptions } from "@workspace/platform/server/company-directory";

export async function GET(request: Request) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth.response;

  const activeOnly = new URL(request.url).searchParams.get("active") !== "0";
  const companies = await listCompanyDirectoryOptions(activeOnly);
  return NextResponse.json({ companies });
}
