// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import {
  buildHrRouteCommand,
  deleteEmployee,
} from "@workspace/hr/server";
import { readRequestExpectedVersion, routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";

export const DELETE = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "ID 无效",
  buildCommand: ({ request, user, params }) => buildHrRouteCommand({
    userId: user.userId,
    id: params.id,
    expectedVersion: readRequestExpectedVersion(request),
  }),
  action: deleteEmployee,
});
