// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import {
  buildSetConsolidationInclusionRouteCommand,
  setConsolidationInclusion,
} from "@workspace/capital-securities/server";
import { createCommandRoute } from "@workspace/platform/server/api-route";

const bodySchema = z.object({
  relationId: z.coerce.number().int().positive(),
  expectedVersion: z.coerce.number().int().positive(),
  included: z.boolean(),
  effectiveDate: z.string().date(),
});

export const POST = createCommandRoute({
  bodySchema,
  buildCommand: ({ body, user }) => buildSetConsolidationInclusionRouteCommand(body, user.userId),
  action: setConsolidationInclusion,
});
