// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";

import { jsonErrorResponse } from "@workspace/platform/server/api";
import { requireAdminApiAccess, isSuperAdmin } from "@workspace/platform/server/auth";
import {
  buildDataQualityAdminAction,
  dataQualityAdminActionSchema,
} from "@workspace/platform/server/data-quality-admin-command";
import { runDataQuality } from "@workspace/platform/server/data-quality";
import {
  buildDataQualityPolicyUpdate,
  dataQualityPolicyUpdateSchema,
  saveDataQualityPolicy,
} from "@workspace/platform/server/data-quality-policy";
import { refreshDataQualitySchedule } from "@workspace/platform/server/data-quality-scheduler";
import { sendDataQualityWecomGroupTest } from "@workspace/platform/server/data-quality-wecom";
import { getDataQualityWorkbench } from "@workspace/platform/server/data-quality-workbench";
import { domainIssueToResponse } from "@workspace/platform/server/domain-validation";

async function requireRoot(request: Request) {
  const auth = await requireAdminApiAccess(request);
  if (!auth.ok) return auth;
  if (!(await isSuperAdmin(auth.user.userId))) {
    return { ok: false as const, response: jsonErrorResponse("无权限", 403) };
  }
  return auth;
}

export async function GET(request: Request) {
  const auth = await requireRoot(request);
  if (!auth.ok) return auth.response;
  try {
    return NextResponse.json(await getDataQualityWorkbench());
  } catch (error) {
    return jsonErrorResponse(error instanceof Error ? error.message : "加载数据质量工作台失败", 500);
  }
}

export async function PUT(request: Request) {
  const auth = await requireRoot(request);
  if (!auth.ok) return auth.response;
  const parsed = dataQualityPolicyUpdateSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return jsonErrorResponse("数据质量策略参数无效", 400);
  try {
    const command = await buildDataQualityPolicyUpdate(parsed.data);
    if (!command.ok) return domainIssueToResponse(command.issue);
    const policy = await saveDataQualityPolicy(command.data);
    refreshDataQualitySchedule();
    return NextResponse.json({ policy });
  } catch (error) {
    return jsonErrorResponse(error instanceof Error ? error.message : "保存数据质量策略失败", 500);
  }
}

export async function POST(request: Request) {
  const auth = await requireRoot(request);
  if (!auth.ok) return auth.response;
  const parsed = dataQualityAdminActionSchema.safeParse(await request.json().catch(() => null));
  if (!parsed.success) return jsonErrorResponse("数据质量操作无效", 400);
  const command = buildDataQualityAdminAction(parsed.data);
  if (!command.ok) return domainIssueToResponse(command.issue);
  try {
    if (command.data.action === "test_wecom") {
      return NextResponse.json(await sendDataQualityWecomGroupTest());
    }
    return NextResponse.json(await runDataQuality({ trigger: "manual", requestedByUserId: auth.user.userId }));
  } catch (error) {
    return jsonErrorResponse(error instanceof Error ? error.message : "数据质量操作失败", 500);
  }
}
