// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { ErpDueDiligenceClient } from "@workspace/administration/ui";
import { evaluatePermissionAction, requireRouteAccess } from "@workspace/platform/server/auth";
import { renderAppShellPage } from "@workspace/platform/ui/app-shell-page";

export default async function AdministrationErpDiligencePage() {
  const user = await requireRouteAccess("/administration/erp-diligence");
  const [canEdit, canViewAll] = await Promise.all([
    evaluatePermissionAction(user.id, "administration.erpDiligence", "update"),
    evaluatePermissionAction(user.id, "administration.erpDiligence.viewAll", "read"),
  ]);

  return renderAppShellPage({
    title: "ERP流程尽调",
    backHref: "/administration",
    user,
    children: <ErpDueDiligenceClient user={user} canEdit={canEdit} canViewAll={canViewAll} />,
  });
}
