// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";
import {
  buildCreateTaxRouteCommand,
  buildUpdateTaxRouteCommand,
  executeCreateTaxRouteCommand,
  executeListTaxWorkspaceCommand,
  executeUpdateTaxRouteCommand,
} from "@workspace/finance/server/tax/route-commands";
import { taxCreateSchema, taxScopeSchema, taxUpdateSchema } from "@workspace/finance/server/tax/schemas";

export const GET = createCommandRoute({
  querySchema: taxScopeSchema,
  queryError: "税务工作区范围参数无效",
  buildCommand: ({ query }) => okCommand(query),
  action: executeListTaxWorkspaceCommand,
});

export const POST = createCommandRoute({
  bodySchema: taxCreateSchema,
  bodyError: "税务新增命令参数无效",
  buildCommand: ({ body, user }) => buildCreateTaxRouteCommand(body, user.userId),
  action: executeCreateTaxRouteCommand,
});

export const PUT = createCommandRoute({
  bodySchema: taxUpdateSchema,
  bodyError: "税务更新命令参数无效",
  buildCommand: ({ body, user }) => buildUpdateTaxRouteCommand(body, user.userId),
  action: executeUpdateTaxRouteCommand,
});
