export type WorkPlanCommandInput = {
  isSystemGenerated?: boolean;
  actorUserId?: number | null;
  ownerEligibilityUserId?: number | null;
  updateGuard?: "direct" | "workflow-approved";
  targetType: string;
  targetId: number;
  kind?: string;
  title?: string;
  description?: string;
  status?: string;
  krReviewOpensAt?: Date | string | null;
  ownerEmployeeId?: number | null;
  collaborationId?: number | null;
  okrCycleId?: number | null;
  sourcePlanId?: number | null;
  parentPeriodPlanId?: number | null;
  previousPeriodPlanId?: number | null;
  alignmentSourceType?: string | null;
  alignmentSourcePlanId?: number | null;
  alignmentSourceWorkItemId?: number | null;
  periodType?: string | null;
  actualStartDate?: Date | string | null;
  actualEndDate?: Date | string | null;
  plannedStartDate?: Date | string | null;
  plannedEndDate?: Date | string | null;
  isMilestone?: boolean;
  milestoneDate?: Date | string | null;
  sourceType?: string;
  sourceKind?: string | null;
  sourceMeetingId?: number | null;
  sourceMeetingDecisionId?: number | null;
  sourceMeetingActionCandidateId?: number | null;
  sourceDepartmentId?: number | null;
  linkedProjectId?: number | null;
  linkedProjectPhaseId?: number | null;
  sortOrder?: number;
};
