// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { evaluateHrDataQuality } from "@workspace/hr/server/data-quality";
import { dataQualityEvaluationRequestSchema } from "@workspace/platform/data-quality-contract";
import { jsonErrorResponse } from "@workspace/platform/server/api";
import { createInternalApiRoute } from "@workspace/platform/server/api-route";
import { isWorkspaceInternalRequestAuthorized } from "@workspace/platform/server/internal-unit-rpc";

export const POST = createInternalApiRoute({
  authorize: async ({ request }) => isWorkspaceInternalRequestAuthorized(
    request,
    await request.clone().text(),
    { allowedCallerUnitIds: ["workspace-shell"], audienceUnitId: "hr" },
  ),
  authorizeError: "数据质量巡检认证失败",
  handler: async ({ request }) => {
    const parsed = dataQualityEvaluationRequestSchema.safeParse(await request.json().catch(() => null));
    if (!parsed.success) return jsonErrorResponse("数据质量巡检请求无效", 400);
    return evaluateHrDataQuality();
  },
});
