产品名称: 克拉霉素 胶囊
阶段:
  intermediate:
    显示名: 中间体
    检验前确认:
      顶部信息:
        检品名称: 克拉霉素胶囊(中间体)
        包装情况: 桶、塑料袋
        检验目的: 性状、水分、含量
        请验部门: 固体制剂车间
      文件清单:
      - 名称: 《克拉霉素胶囊中间体质量标准》
        编码: MQS074013
      - 名称: 《克拉霉素胶囊中间体检验标准操作规程》
        编码: SOP073413
      - 名称: 《MA37-1CN型水分快速测定仪使用与维护标准操作规程》
        编码: SOP072098
      - 名称: 《电子天平（BS224S、BSA224S）使用与维护标准操作规程》
        编码: SOP072028
      - 名称: 《BT125D十万分之一电子天平使用与维护标准操作规程》
        编码: SOP072055
      - 名称: 《Waters e2695高效液相色谱仪标准操作规程》
        编码: SOP072068
      - 名称: 《Thermo Vanquish超高效液相色谱仪标准操作规程》
        编码: SOP072117
      确认项:
      - 名称: 仪器、设备是否在校验有效期内
      - 名称: 检验用具、物品是否齐全
      环境确认:
        符合要求: true
        不符合要求: true
    检测项:
    - 序号: '2.1'
      名称: 性状
      英文名: appearance
      实验环境模板: env_10_30_75
      标准规定模板: appearance_description
      标准规定参数:
        description: 本品应为白色或类白色颗粒或结晶性粉末
      结论名称: 性状
      结论含数值: false
      方法: 目测
      结论判定:
        rule: 符合标准规定
    - 序号: '2.2'
      名称: 水分
      英文名: moisture
      实验环境模板: env_10_30_70
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 快速水分测定仪
      标准规定模板: moisture_s_limit
      标准规定参数:
        limit: 5.0
      清场模板: standard_cleanup
      结论名称: 水分
      结论含数值: true
      结论判定:
        value_field: 平均水分
        unit: '%'
        rule: 平均水分 <= 5.0 && RD <= 2.0
      方法: 水分
    - 序号: '2.3'
      名称: 含量
      英文名: content
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 3
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 流动相
        - 色谱柱
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 克拉霉素对照品
      标准规定模板: content_assay_range
      标准规定参数:
        subject: 含克拉霉素（C38H69NO13计）
        lower: 93.0
        upper: 107.0
        phrase: 应为标示量的
      清场模板: standard_cleanup
      结论名称: 含量
      结论含数值: true
      结论判定:
        value_field: 平均含量
        unit: '%'
        rule: 平均含量 >= 93.0 && 平均含量 <= 107.0 && RD <= 2.0
      附加说明模板: data_page_attachment
      附加说明参数:
        items:
        - 图谱
        - 中间体检验报告单
      方法: HPLC
  packaging:
    显示名: 待包装品
    检验前确认:
      顶部信息:
        检品名称: 克拉霉素胶囊(待包装品)
        包装情况: 桶、塑料袋
        检验目的: 部分检查
        请验部门: 固体制剂车间
      文件清单:
      - 名称: 《克拉霉素胶囊质量标准》
        编码: MQS075013
      - 名称: 《克拉霉素胶囊检验标准操作规程》
        编码: SOP073513
      - 名称: 《电子天平（BS224S、BSA224S）使用与维护标准操作规程》
        编码: SOP072028
      - 名称: 《BT125D十万分之一电子天平使用与维护标准操作规程》
        编码: SOP072055
      - 名称: 《FADT-1202型自动溶出仪使用与维护保养标准操作规程》
        编码: SOP072100
      - 名称: 《RCZ-8N智能溶出试验仪使用与维护保养标准操作规程》
        编码: SOP072116
      - 名称: 《Waters e2695高效液相色谱仪标准操作规程》
        编码: SOP072068
      - 名称: 《Thermo Vanquish超高效液相色谱仪标准操作规程》
        编码: SOP072117
      确认项:
      - 名称: 仪器、设备是否在校验有效期内
      - 名称: 检验用具、物品是否齐全
      环境确认:
        符合要求: true
        不符合要求: true
    检测项:
    - 序号: '2.1'
      名称: 性状
      英文名: appearance
      实验环境模板: env_10_30_75
      标准规定模板: appearance_description
      标准规定参数:
        description: 本品内容物应为白色或类白色颗粒或结晶性粉末
      结论名称: 性状
      结论含数值: false
      方法: 目测
      结论判定:
        rule: 符合标准规定
    - 序号: '2.2'
      名称: 溶出度
      英文名: dissolution
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 溶出试验仪
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 醋酸盐缓冲液（pH5.0）
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 克拉霉素对照品
      标准规定模板: dissolution_release_limit
      标准规定参数:
        limit: 85
      清场模板: standard_cleanup
      结论名称: 溶出度
      结论含数值: false
      附加说明模板: data_page_attachment
      附加说明参数:
        items:
        - 原始数据
        - 图谱
      方法: 溶出度-HPLC
      结论判定:
        value_field: 平均溶出度
        unit: '%'
        rule: 平均溶出度 >= 85.0
    - 序号: '2.3'
      名称: 装量差异
      英文名: fill_variation
      实验环境模板: env_10_30_70
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
      标准规定模板: variation_difference_limit
      标准规定参数:
        basis: 平均粒重
        limit: 7.5
        difference_name: 装量差异
        max_over: 2
        unit: 粒
        one_unit: 一粒
      清场模板: standard_cleanup
      结论名称: 重量差异
      结论含数值: false
      方法: 装量差异
      结论判定:
        rule: 符合标准规定
    - 序号: '2.4'
      名称: 含量
      英文名: content
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 流动相
        - 色谱柱
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 克拉霉素对照品
      标准规定模板: content_assay_range
      标准规定参数:
        subject: 含克拉霉素（C38H69NO13计）
        lower: 93.0
        upper: 107.0
        phrase: 应为标示量的
      清场模板: standard_cleanup
      结论名称: 含量
      结论含数值: true
      附加说明模板: data_page_attachment
      附加说明参数:
        items:
        - 原始数据
        - 图谱
      方法: HPLC
      结论判定:
        value_field: 平均含量
        unit: '%'
        rule: 平均含量 >= 93.0 && 平均含量 <= 107.0 && RD <= 2.0
  finished:
    显示名: 成品
    检验前确认:
      顶部信息:
        检品名称: 克拉霉素胶囊
        包装情况: 铝塑包装
        检验目的: 全检
        请验部门: 固体制剂车间
      文件清单:
      - 名称: 《克拉霉素胶囊质量标准》
        编码: MQS075013
      - 名称: 《克拉霉素胶囊标准操作规程》
        编码: SOP073513
      - 名称: 《电子天平（BS224S、BSA224S）使用与维护标准操作规程》
        编码: SOP072028
      - 名称: 《BT125D十万分之一电子天平使用与维护标准操作规程》
        编码: SOP072055
      - 名称: 《FADT-1202型自动溶出仪使用与维护保养标准操作规程》
        编码: SOP072100
      - 名称: 《RCZ-8N智能溶出试验仪使用与维护保养标准操作规程》
        编码: SOP072116
      - 名称: 《Waters e2695高效液相色谱仪标准操作规程》
        编码: SOP072068
      - 名称: 《Thermo Vanquish超高效液相色谱仪标准操作规程》
        编码: SOP072117
      - 名称: 《微生物限度检验标准操作规程》
        编码: SOP073613
      - 名称: 《培养基使用标准操作规程》
        编码: SOP071007
      - 名称: 《检定用菌毒种使用标准操作规程》
        编码: SOP071004
      - 名称: 《LDZX-50KBS型立式压力蒸汽灭菌器使用、维护保养标准操作规程》
        编码: SOP072111
      - 名称: 《ZSP-S500型生化培养箱使用与维护标准操作规程》
        编码: SOP072083
      - 名称: 《ZSP-S250型生化培养箱使用与维护标准操作规程》
        编码: SOP072125
      - 名称: 《BHC-1100ⅡA2生物安全柜使用与保养维护标准操作规程》
        编码: SOP072044
      确认项:
      - 名称: 仪器、设备是否在校验有效期内
      - 名称: 检验用具、物品是否齐全
      环境确认:
        符合要求: true
        不符合要求: true
    检测项:
    - 序号: '2.1'
      名称: 性状
      英文名: appearance
      实验环境模板: env_10_30_75
      标准规定模板: appearance_description
      标准规定参数:
        description: 本品应为白色或类白色颗粒或结晶性粉末
      结论名称: 性状
      结论含数值: false
      方法: 目测
      结论判定:
        rule: 符合标准规定
    - 序号: '2.2'
      名称: 鉴别
      英文名: identification
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      标准规定模板: identification_retention_time
      清场模板: standard_cleanup
      结论名称: 鉴别
      结论含数值: false
      方法: 鉴别
      结论判定:
        rule: 符合标准规定
    - 序号: '2.3'
      名称: 有关物质
      英文名: related_substances
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      标准规定模板: related_substances_single_peak_limit
      标准规定参数:
        label: 单个杂质峰面积
        comparison: 对照溶液主峰面积
        multiple: 0.7
        limit: 3.5
      结论名称: 有关物质
      结论含数值: false
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 流动相
        - 色谱柱
      方法: 有关物质
      结论判定:
        rule: 符合标准规定
    - 序号: '2.4'
      名称: 溶出度
      英文名: dissolution
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 溶出试验仪
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 醋酸盐缓冲液（pH5.0）
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 克拉霉素对照品
      标准规定模板: dissolution_release_limit
      标准规定参数:
        limit: 85
      清场模板: standard_cleanup
      结论名称: 溶出度
      结论含数值: false
      方法: 溶出度-HPLC
      结论判定:
        value_field: 平均溶出度
        unit: '%'
        rule: 平均溶出度 >= 85.0
    - 序号: '2.5'
      名称: 装量差异
      英文名: fill_variation
      实验环境: null
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
      标准规定模板: variation_difference_limit
      标准规定参数:
        basis: 平均粒重
        limit: 7.5
        difference_name: 重量差异
        max_over: 2
        unit: 粒
        one_unit: 一粒
      清场模板: standard_cleanup
      结论名称: 重量差异
      结论含数值: false
      方法: 装量差异
      结论判定:
        rule: 符合标准规定
    - 序号: '2.6'
      名称: 含量
      英文名: content
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 克拉霉素对照品
      标准规定模板: content_assay_range
      标准规定参数:
        subject: 含克拉霉素（C38H69NO13计）
        lower: 93.0
        upper: 107.0
        phrase: 应为标示量的
      结论名称: 含量
      结论含数值: true
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 克拉霉素胶囊流动相
        - 色谱柱
      方法: HPLC简表
      结论判定:
        value_field: 平均含量
        unit: '%'
        rule: 平均含量 >= 93.0 && 平均含量 <= 107.0 && RD <= 2.0
    - 序号: '2.7'
      名称: 微生物限度检查
      英文名: microbial_limit
      实验环境模板: env_rows_only
      实验环境参数:
        多行: 2
      仪器设备: null
      试验材料模板: microbiology_limit_materials
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 大肠埃希菌
        - 第   代
      标准规定模板: microbial_limit_standard
      标准规定参数:
        sample_amount: 1
        sample_unit: g
        aerobic_limit: 10³
        yeast_mold_limit: 10²
      清场模板: standard_cleanup
      结论名称: 微生物限度
      结论含数值: false
      方法: 微生物限度-计数法
      结论判定:
        rule: 符合标准规定
