产品名称: 氢氯噻嗪片
阶段:
  intermediate:
    显示名: 中间体
    检验前确认:
      顶部信息:
        检品名称: 氢氯噻嗪片(中间体)
        包装情况: 桶、塑料袋
        检验目的: 性状、水分、含量
        请验部门: 固体制剂车间
      文件清单:
      - 名称: 《氢氯噻嗪片中间体质量标准》
        编码: MQS074001
      - 名称: 《氢氯噻嗪片中间体检验标准操作规程》
        编码: SOP073401
      - 名称: 《MA37-1CN型水分快速测定仪使用与维护标准操作规程》
        编码: SOP072098
      - 名称: 《电子天平（BS224S、BSA224S）使用与维护标准操作规程》
        编码: SOP072028
      - 名称: 《BT125D十万分之一电子天平使用与维护标准操作规程》
        编码: SOP072055
      - 名称: 《Waters e2695高效液相色谱仪标准操作规程》
        编码: SOP072068
      - 名称: 《Thermo Vanquish超高效液相色谱仪标准操作规程》
        编码: SOP072117
      确认项:
      - 名称: 仪器、设备是否在校验有效期内
      - 名称: 检验用具、物品是否齐全
      环境确认:
        符合要求: true
        不符合要求: true
    检测项:
    - 序号: '2.1'
      名称: 性状
      英文名: appearance
      实验环境模板: env_10_30_75
      标准规定模板: appearance_description
      标准规定参数:
        description: 本品应为白色颗粒
      结论名称: 性状
      结论含数值: false
      方法: 目测
      结论判定:
        rule: 符合标准规定
    - 序号: '2.2'
      名称: 水分
      英文名: moisture
      实验环境模板: env_10_30_70
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 快速水分测定仪
      标准规定模板: moisture_s_limit
      标准规定参数:
        limit: 4.0
      清场模板: standard_cleanup
      结论名称: 水分
      结论含数值: true
      结论判定:
        value_field: 平均水分
        unit: '%'
        rule: 平均水分 <= 4.0 && RD <= 2.0
      方法: 水分
    - 序号: '2.3'
      名称: 含量
      英文名: content
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 3
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
        - 氯噻嗪对照品
      标准规定模板: content_assay_range
      标准规定参数:
        subject: 含氢氯噻嗪（C7H8CIN3O4S2计）
        lower: 95.0
        upper: 105.0
        phrase: 应为标示量的
      结论名称: 含量
      结论含数值: true
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 含量流动相
        - 甲醇：乙腈（1:1）
        - 色谱柱
      方法: HPLC
      结论判定:
        value_field: 平均含量
        unit: '%'
        rule: 平均含量 >= 95.0 && 平均含量 <= 105.0 && RD <= 2.0
  packaging:
    显示名: 待包装品
    检验前确认:
      顶部信息:
        检品名称: 氢氯噻嗪片(待包装品)
        包装情况: 桶、塑料袋
        检验目的: 部分检查
        请验部门: 固体制剂车间
      文件清单:
      - 名称: 《氢氯噻嗪片质量标准》
        编码: MQS075001
      - 名称: 《氢氯噻嗪片检验标准操作规程》
        编码: SOP073501
      - 名称: 《电子天平（BS224S、BSA224S）使用与维护标准操作规程》
        编码: SOP072028
      - 名称: 《BT125D十万分之一电子天平使用与维护标准操作规程》
        编码: SOP072055
      - 名称: 《FADT-1202型自动溶出仪使用与维护保养标准操作规程》
        编码: SOP072100
      - 名称: 《RCZ-8N智能溶出试验仪使用与维护保养标准操作规程》
        编码: SOP072116
      - 名称: 《Waters e2695高效液相色谱仪标准操作规程》
        编码: SOP072068
      - 名称: 《Thermo Vanquish超高效液相色谱仪标准操作规程》
        编码: SOP072117
      - 名称: 《TU-1901双光束紫外可见分光光度计标准操作规程》
        编码: SOP072045
      确认项:
      - 名称: 仪器、设备是否在校验有效期内
      - 名称: 检验用具、物品是否齐全
      环境确认:
        符合要求: true
        不符合要求: true
    检测项:
    - 序号: '2.1'
      名称: 性状
      英文名: appearance
      实验环境模板: env_10_30_75
      标准规定模板: appearance_description
      标准规定参数:
        description: 本品应为白色片
      结论名称: 性状
      结论含数值: false
      方法: 目测
      结论判定:
        rule: 符合标准规定
    - 序号: '2.2'
      名称: 溶出度
      英文名: dissolution
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
      标准规定模板: dissolution_release_limit
      标准规定参数:
        limit: 70
      结论名称: 溶出度
      结论含数值: false
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 溶出试验仪
        - 紫外可见分光光度计
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 0.1mol/L盐酸溶液
      方法: 溶出度
      结论判定:
        value_field: 平均溶出度
        unit: '%'
        rule: 平均溶出度 >= 70.0
    - 序号: '2.3'
      名称: 含量均匀度
      英文名: content_uniformity
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 含量流动相
        - 甲醇：乙腈（1:1）
        - 色谱柱
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
        - 氯噻嗪对照品
      标准规定模板: content_uniformity_a_2_2s
      标准规定参数:
        factor: 2.2
        limit: 13.0
      清场模板: standard_cleanup
      结论名称: 含量均匀度
      结论含数值: false
      方法: 含量均匀度
      结论判定:
        value_field: A_2.2S
        unit: ''
        rule: A_2.2S <= 13.0
    - 序号: '2.4'
      名称: 含量
      英文名: content
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
        - 氯噻嗪对照品
      标准规定模板: content_assay_range
      标准规定参数:
        subject: 含氢氯噻嗪（C7H8CIN3O4S2计）
        lower: 95.0
        upper: 105.0
        phrase: 应为标示量的
      结论名称: 含量
      结论含数值: true
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 氢氯噻嗪片流动相
        - 甲醇：乙腈（1:1）
        - 色谱柱
      方法: HPLC
      结论判定:
        value_field: 平均含量
        unit: '%'
        rule: 平均含量 >= 95.0 && 平均含量 <= 105.0 && RD <= 2.0
  finished:
    显示名: 成品
    检验前确认:
      顶部信息:
        检验目的: 全检
        请验部门: 固体制剂车间
      文件清单:
      - 名称: 《氢氯噻嗪片质量标准》
        编码: MQS075001
      - 名称: 《氢氯噻嗪片标准操作规程》
        编码: SOP073501
      - 名称: 《电子天平（BS224S、BSA224S）使用与维护标准操作规程》
        编码: SOP072028
      - 名称: 《BT125D十万分之一电子天平使用与维护标准操作规程》
        编码: SOP072055
      - 名称: 《FADT-1202型自动溶出仪使用与维护保养标准操作规程》
        编码: SOP072100
      - 名称: 《RCZ-8N智能溶出试验仪使用与维护保养标准操作规程》
        编码: SOP072116
      - 名称: 《CS-2A型片剂脆碎度测定仪的使用与维护标准操作规程》
        编码: SOP072019
      - 名称: 《Waters e2695高效液相色谱仪标准操作规程》
        编码: SOP072068
      - 名称: 《Thermo Vanquish超高效液相色谱仪标准操作规程》
        编码: SOP072117
      - 名称: 《TU-1901双光束紫外可见分光光度计标准操作规程》
        编码: SOP072045
      - 名称: 《微生物限度检验标准操作规程》
        编码: SOP073613
      - 名称: 《培养基使用标准操作规程》
        编码: SOP071007
      - 名称: 《检定用菌毒种使用标准操作规程》
        编码: SOP071004
      - 名称: 《LDZX-50KBS型立式压力蒸汽灭菌器使用、维护保养标准操作规程》
        编码: SOP072111
      - 名称: 《ZSP-S500型生化培养箱使用与维护标准操作规程》
        编码: SOP072083
      - 名称: 《ZSP-S250型生化培养箱使用与维护标准操作规程》
        编码: SOP072125
      - 名称: 《BHC-1100ⅡA2生物安全柜使用与保养维护标准操作规程》
        编码: SOP072044
      确认项:
      - 名称: 仪器、设备是否在校验有效期内
      - 名称: 检验用具、物品是否齐全
      环境确认:
        符合要求: true
        不符合要求: true
    检测项:
    - 序号: '2.1'
      名称: 性状
      英文名: appearance
      实验环境模板: env_10_30_75
      标准规定模板: appearance_description
      标准规定参数:
        description: 本品应为白色片
      结论名称: 性状
      结论含数值: false
      方法: 目测
      结论判定:
        rule: 符合标准规定
    - 序号: '2.2'
      名称: 鉴别
      英文名: identification
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 紫外灯
      标准规定模板: identification_tlc_spot_match
      清场模板: standard_cleanup
      结论名称: 鉴别
      结论含数值: false
      方法: 鉴别-BPC
      结论判定:
        rule: 符合标准规定
    - 序号: '2.3'
      名称: 有关物质
      英文名: related_substances
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 流动相A
        - 流动相B
        - 混合溶剂
        - 色谱柱
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
        - 氯噻嗪对照品
      标准规定模板: related_substances_single_total_limits
      标准规定参数:
        comparison: 对照溶液主峰面积
        single_multiple: 2
        single_limit: 1.0
        total_multiple: 4
        total_limit: 2.0
      清场模板: standard_cleanup
      结论名称: 有关物质
      结论含数值: false
      附加说明模板: data_page_attachment
      附加说明参数:
        items:
        - 图谱
      方法: 有关物质
      结论判定:
        rule: 符合标准规定
    - 序号: '2.4'
      名称: 溶出度
      英文名: dissolution
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
      标准规定模板: dissolution_release_limit
      标准规定参数:
        limit: 70
      结论名称: 溶出度
      结论含数值: false
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 溶出试验仪
        - 紫外可见分光光度计
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 0.1mol/L盐酸溶液
      方法: 溶出度
      结论判定:
        value_field: 平均溶出度
        unit: '%'
        rule: 平均溶出度 >= 70.0
    - 序号: '2.5'
      名称: 含量均匀度
      英文名: content_uniformity
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
        - 氯噻嗪对照品
      标准规定模板: content_uniformity_a_2_2s
      标准规定参数:
        factor: 2.2
        limit: 13.0
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 含量流动相
        - 甲醇：乙腈（1:1）
        - 色谱柱
      结论名称: 含量均匀度
      结论含数值: false
      方法: 含量均匀度
      结论判定:
        value_field: A_2.2S
        unit: ''
        rule: A_2.2S <= 13.0
    - 序号: '2.6'
      名称: 脆碎度
      英文名: friability
      实验环境模板: env_10_30_70
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 脆碎度测试仪
      标准规定模板: friability_loss_limit
      标准规定参数:
        loss_limit: 0.9
        repeat_count: 2
      清场模板: standard_cleanup
      结论名称: 脆碎度
      结论含数值: false
      方法: 脆碎度
      结论判定:
        value_field: 平均减失率
        unit: '%'
        rule: 平均减失率 <= 0.9
    - 序号: '2.7'
      名称: 含量
      英文名: content
      实验环境模板: env_10_30_75
      实验环境参数:
        多行: 2
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 电子天平
        - 高效液相色谱仪
      试验材料模板: standard_material_list
      试验材料参数:
        items:
        - 含量流动相
        - 甲醇：乙腈（1:1）
        - 色谱柱
      标准品模板: standard_reference_list
      标准品参数:
        items:
        - 氢氯噻嗪对照品
        - 氯噻嗪对照品
      标准规定模板: content_assay_range
      标准规定参数:
        subject: 含氢氯噻嗪（C7H8CIN3O4S2计）
        lower: 95.0
        upper: 105.0
        phrase: 应为标示量的
      清场模板: standard_cleanup
      结论名称: 含量
      结论含数值: true
      结论判定:
        value_field: 平均含量
        unit: '%'
        rule: 平均含量 >= 95.0 && 平均含量 <= 105.0 && RD <= 2.0
      方法: HPLC
    - 序号: '2.8'
      名称: 微生物限度检查
      英文名: microbial_limit
      实验环境模板: env_rows_only
      实验环境参数:
        多行: 2
      标准规定模板: microbial_limit_standard
      标准规定参数:
        sample_amount: 1
        sample_unit: g
        aerobic_limit: 10³
        yeast_mold_limit: 10²
      结论名称: 微生物限度
      结论含数值: false
      清场模板: standard_cleanup
      仪器设备模板: standard_equipment_list
      仪器设备参数:
        items:
        - 立式压力蒸汽灭菌器
        - 生化培养箱
        - 生物安全柜
        - 净化台
        - 电子天平
      方法: 微生物限度-计数法
      结论判定:
        rule: 符合标准规定
