// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { NextResponse } from "next/server";

import { jsonErrorResponse } from "@workspace/platform/server/api";
import { isSuperAdmin, requireApiAccess } from "@workspace/platform/server/auth";
import { listSqlSettingsCatalog } from "@workspace/settings/server/sql-settings";
import {
  createSqlSettingOperation,
  SqlSettingOperationConflictError,
  SqlSettingOperationQueueError,
} from "@workspace/settings/server/sql-settings-operations";
import { SqlSettingOperationValidationError } from "@workspace/settings/server/sql-settings-operation-validation";
import { sqlSettingOperationSchema } from "@workspace/settings/server/sql-settings-route-schema";

async function requireRoot(request: Request) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth;
  if (!(await isSuperAdmin(auth.user.userId))) {
    return { ok: false as const, response: jsonErrorResponse("无权限", 403) };
  }
  return auth;
}

export async function GET(request: Request) {
  const auth = await requireRoot(request);
  if (!auth.ok) return auth.response;

  try {
    return NextResponse.json(await listSqlSettingsCatalog(), { headers: { "Cache-Control": "no-store" } });
  } catch (error) {
    if (error instanceof SqlSettingOperationQueueError) {
      return jsonErrorResponse(error.message, 503);
    }
    console.error("SQL settings catalog load failed", error);
    return jsonErrorResponse("加载 SQL 设置失败", 500);
  }
}

export async function PATCH(request: Request) {
  const auth = await requireRoot(request);
  if (!auth.ok) return auth.response;
  const idempotencyKey = request.headers.get("idempotency-key")?.trim() ?? "";
  if (!/^[A-Za-z0-9._:-]{8,128}$/.test(idempotencyKey)) {
    return jsonErrorResponse("缺少有效的 Idempotency-Key", 400);
  }
  const rawBody = await request.text();
  if (Buffer.byteLength(rawBody, "utf8") > 8_192) return jsonErrorResponse("请求体过大", 413);
  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return jsonErrorResponse("请求体必须是合法 JSON", 400);
  }
  const parsed = sqlSettingOperationSchema.safeParse(body);
  if (!parsed.success) return jsonErrorResponse(parsed.error.issues[0]?.message ?? "SQL 设置参数无效", 400);
  try {
    return NextResponse.json(await createSqlSettingOperation(parsed.data, auth.user.userId, idempotencyKey), {
      status: 202,
      headers: { "Cache-Control": "no-store" },
    });
  } catch (error) {
    if (error instanceof SqlSettingOperationConflictError) {
      return jsonErrorResponse(error.message, 409);
    }
    if (error instanceof SqlSettingOperationValidationError) {
      return jsonErrorResponse(error.message, 422);
    }
    if (error instanceof SqlSettingOperationQueueError) {
      return jsonErrorResponse(error.message, 503);
    }
    console.error("SQL settings operation create failed", error);
    return jsonErrorResponse("提交 SQL 设置操作失败", 500);
  }
}
