// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { authorize } from "@workspace/platform/server/auth";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { bindExecuteRefreshFinanceCloseRouteCommand, buildRefreshFinanceCloseRouteCommand } from "@workspace/finance/server/close/route-commands";
import { refreshFinanceCloseSchema } from "@workspace/finance/server/close/schemas";
import {
  inventoryClosingInspectionSchema,
  type InventoryClosingContract,
  type InventoryClosingScope,
} from "@workspace/platform/contracts/inventory-closing";
import { callWorkspaceInternalJson } from "@workspace/platform/server/internal-unit-rpc";

async function inspectInventoryClosing(scope: InventoryClosingScope, inspectionKind: "records" | "count_differences") {
  return inventoryClosingInspectionSchema.parse(await callWorkspaceInternalJson({
    callerUnitId: "finance",
    targetUnitId: "inventory",
    path: "/api/modules/inventory/internal/closing-inspection",
    body: { scope, inspectionKind },
    maxResponseBytes: 512 * 1024,
  }));
}

const inventoryClosingContract: InventoryClosingContract = {
  inspectPeriodRecords: (scope) => inspectInventoryClosing(scope, "records"),
  inspectPeriodCountDifferences: (scope) => inspectInventoryClosing(scope, "count_differences"),
};

const executeRefreshFinanceCloseRouteCommand = bindExecuteRefreshFinanceCloseRouteCommand(inventoryClosingContract);

export const POST = createCommandRoute({
  bodySchema: refreshFinanceCloseSchema,
  bodyError: "刷新关账运行参数无效",
  access: (userId) => authorize({ user: userId, resourceKey: "finance.ledger", action: "update" }),
  accessError: "无关账刷新权限",
  buildCommand: ({ body, user }) => buildRefreshFinanceCloseRouteCommand(body, user.userId),
  action: executeRefreshFinanceCloseRouteCommand,
});
