\set ON_ERROR_STOP on
ALTER ROLE workspace_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT CONNECT ON DATABASE workspace TO workspace_app;
\connect workspace
GRANT USAGE ON SCHEMA public TO workspace_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO workspace_app;
GRANT USAGE,SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO workspace_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO workspace_app;
REVOKE ALL ON TABLE public."_prisma_migrations" FROM workspace_app;
