// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { evaluatePermissionAction, requireRouteAccess } from "@workspace/platform/server/auth";
import { SettingsApiPage as PlatformSettingsApiPage } from "@workspace/settings/ui/settings";

export default async function SettingsHrGeneratedApiPage() {
  const user = await requireRouteAccess("/settings/api/hr-generated");
  const [canCreateClient, canRotateSecret, canGrantScopes] = await Promise.all([
    evaluatePermissionAction(user.id, "settings.api.manage", "create"),
    evaluatePermissionAction(user.id, "settings.api.manage", "revise"),
    evaluatePermissionAction(user.id, "settings.api.manage", "grant"),
  ]);
  return PlatformSettingsApiPage({ user, focusRegistrationKey: "hr.generated", canCreateClient, canRotateSecret, canGrantScopes });
}
