// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
/**
 * POST /api/agent — Agent 对话入口。
 * 只做认证、用户解析、按页面上下文选择已注册工具并调用 Platform agent handler。
 */
import { getSessionUserFromAuthPayload, requireApiAccess } from "@workspace/platform/server/auth";
import { handleParsedAgentMessageStreamRequest, parseAgentRequest, sourceCodeAgentTools } from "@workspace/platform/server/agent";
import { loadRemoteAgentTools } from "@workspace/platform/server/agent/remote-domain-rpc";
import { jsonErrorResponse } from "@workspace/platform/server/api";
import { docsEditorAgentTools } from "@workspace/platform/server/docs-editor";

export const runtime = "nodejs";
export const maxDuration = 900;

export async function POST(request: Request) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth.response;

  const user = await getSessionUserFromAuthPayload(auth.user);
  if (!user) return jsonErrorResponse("Unauthorized", 401);

  const parsed = await parseAgentRequest(request);
  if (!parsed.ok) return parsed.response;
  const pagePath = parsed.body.context?.path?.replace(/\/+$/, "") ?? "";
  const domainTools = await loadRemoteAgentTools();
  const tools = pagePath.endsWith("/finance/statements")
    ? domainTools.filter((tool) => tool.key === "finance.readStatementsPage")
    : [...sourceCodeAgentTools, ...domainTools, ...docsEditorAgentTools];

  return handleParsedAgentMessageStreamRequest(
    parsed,
    user,
    tools,
    request.signal,
  );
}
