// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
/**
 * POST /api/agent — Agent 对话入口。
 * 只做认证、用户解析，并把固定的三个标准业务 API connector 交给 Platform agent handler。
 */
import { getSessionUserFromAuthPayload, requireApiAccess } from "@workspace/platform/server/auth";
import {
  agentBusinessApiTools,
  handleParsedAgentMessageStreamRequest,
  parseAgentRequest,
} from "@workspace/platform/server/agent";
import { jsonErrorResponse } from "@workspace/platform/server/api";

export const runtime = "nodejs";
export const maxDuration = 900;

export async function POST(request: Request) {
  const auth = await requireApiAccess(request);
  if (!auth.ok) return auth.response;

  const user = await getSessionUserFromAuthPayload(auth.user);
  if (!user) return jsonErrorResponse("Unauthorized", 401);

  const parsed = await parseAgentRequest(request);
  if (!parsed.ok) return parsed.response;

  return handleParsedAgentMessageStreamRequest(
    parsed,
    user,
    agentBusinessApiTools,
    request.signal,
  );
}
