// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { requireRouteAccess } from "@workspace/platform/server/auth";

export default async function InvestorsLayout({ children }: { children: React.ReactNode }) {
  await requireRouteAccess("/capital-securities/investors");
  return children;
}
