// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { evaluatePermissionAction, requireRouteAccess } from "@workspace/platform/server/auth";
import { renderAppShellPage } from "@workspace/platform/ui/app-shell-page";
import { InvestorsClient } from "@workspace/capital-securities/ui";

export default async function InvestorsPage() {
  const user = await requireRouteAccess("/capital-securities/investors");
  const [canCreate, canUpdate, canDelete] = await Promise.all([
    evaluatePermissionAction(user.id, "capitalSecurities.investors", "create"),
    evaluatePermissionAction(user.id, "capitalSecurities.investors", "update"),
    evaluatePermissionAction(user.id, "capitalSecurities.investors", "delete"),
  ]);

  return renderAppShellPage({
    title: "投资人关系",
    backHref: "/capital-securities",
    user,
    children: <InvestorsClient canCreate={canCreate} canUpdate={canUpdate} canDelete={canDelete} />,
  });
}
