// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { readRequestExpectedVersion, routeIdParamsSchema } from "@workspace/platform/server/api";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { directCommandId } from "@workspace/platform/server/direct-command-meta";
import { okCommand } from "@workspace/platform/server/domain-validation";
import {
  ContractUpdateSchema,
  executeDeleteContractCommand,
  executeUpdateContractCommand,
} from "@workspace/administration/server";

export const PATCH = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  bodySchema: ContractUpdateSchema,
  paramsError: "无效ID",
  buildCommand: ({ params, body, request, user }) => okCommand({
    id: params.id,
    body,
    userId: user.userId,
    expectedVersion: readRequestExpectedVersion(request),
    idempotencyKey: directCommandId(request),
  }),
  action: executeUpdateContractCommand,
});

export const DELETE = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "无效ID",
  buildCommand: ({ params, request, user }) => okCommand({
    id: params.id,
    userId: user.userId,
    expectedVersion: readRequestExpectedVersion(request),
  }),
  action: executeDeleteContractCommand,
});
