// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { readRequestExpectedVersion, routeIdParamsSchema, updateFieldBodySchema } from "@workspace/platform/server/api";
import { failCommand, okCommand } from "@workspace/platform/server/domain-validation";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { deleteProjectMemberAction, updateProjectMemberFieldAction } from "@workspace/work/server";

export const PUT = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  bodySchema: updateFieldBodySchema,
  paramsError: "ID 无效",
  buildCommand: ({ user, params, body, request }) => {
    const idempotencyKey = request.headers.get("idempotency-key")?.trim();
    return idempotencyKey
      ? okCommand({
          userId: user.userId,
          recordId: params.id,
          body,
          expectedVersion: readRequestExpectedVersion(request),
          idempotencyKey,
        })
      : failCommand("缺少 Idempotency-Key 请求头");
  },
  action: updateProjectMemberFieldAction,
});

export const DELETE = createCommandRoute({
  paramsSchema: routeIdParamsSchema,
  paramsError: "ID 无效",
  buildCommand: ({ user, params, request }) => {
    const idempotencyKey = request.headers.get("idempotency-key")?.trim();
    return idempotencyKey
      ? okCommand({
          userId: user.userId,
          recordId: params.id,
          expectedVersion: readRequestExpectedVersion(request),
          idempotencyKey,
        })
      : failCommand("缺少 Idempotency-Key 请求头");
  },
  action: deleteProjectMemberAction,
});
