// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";

import { uploadInvestmentEnterpriseDocument } from "@workspace/capital-securities/server/investment-enterprise-documents";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { okCommand } from "@workspace/platform/server/domain-validation";

const uploadSchema = z.object({
  profileId: z.coerce.number().int().positive(),
  documentCategory: z.string().min(1).max(80),
  title: z.string().min(1).max(240),
  notes: z.string().max(2000).optional(),
  file: z.instanceof(File),
});

export const POST = createCommandRoute({
  accessError: "没有投资企业资料导入权限",
  bodyParser: "formData",
  bodySchema: uploadSchema,
  bodyError: "上传资料参数无效",
  buildCommand: ({ body, user }) => okCommand({ userId: user.userId, ...body }),
  action: uploadInvestmentEnterpriseDocument,
});
