sources:
  workspace_repo:
    type: codeup
    name: Workspace
    endpoint: https://codeup.aliyun.com/6a30d9d908f52788b1331bb3/illya317/Workspace.git
    branch: main
    branchesFilter: ^main$
    triggerEvents:
      - push
    certificate:
      type: serviceConnection
      serviceConnection: ad88bbsyzgcp8fkb

defaultWorkspace: workspace_repo

variables:
  - key: SERVER
    value: ubuntu@111.229.86.81
  - key: REMOTE_DIR
    value: /home/ubuntu/workspace
  - key: PM2_NAME
    value: workspace
  - key: REMOTE_WORKSPACE_CONFIG_DIR
    value: /home/ubuntu/.workspace
  - key: RUN_LOCAL_CHECKS
    value: "1"

stages:
  deploy_stage:
    name: Deploy
    jobs:
      deploy_job:
        name: Deploy To CVM
        runsOn:
          group: public/cn-beijing
          container: build-steps-public-registry.cn-beijing.cr.aliyuncs.com/build-steps/alinux3:latest
        steps:
          deploy_step:
            step: Command
            name: Run Deploy Script
            workspace: workspace_repo
            with:
              run: |
                bash ./ops/deploy.sh
