// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { z } from "zod";
import { okCommand } from "@workspace/platform/server/domain-validation";
import { createCommandRoute } from "@workspace/platform/server/api-route";
import { exportContracts } from "@workspace/administration/server";

const optionalText = z.preprocess(
  (value) => {
    const text = typeof value === "string" ? value.trim() : "";
    return text || undefined;
  },
  z.string().optional(),
);

const contractsExportQuerySchema = z.object({
  q: optionalText,
  location: optionalText,
  category: optionalText,
  status: optionalText,
});

export const GET = createCommandRoute({
  querySchema: contractsExportQuerySchema,
  buildCommand: ({ query }) => okCommand(query),
  action: exportContracts,
});
