// Generated by scripts/deploy/deploy-unit-app-generator.ts. Do not edit.
import { registerDeployUnitRuntime } from "@workspace/platform/server/deploy-unit-runtime";

export function register() {
  return registerDeployUnitRuntime("hr");
}
